### ISSUE TITLE
Retired items appear in menus

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#1]
Retired items still appear in the main list

**Comment by AngelaFaulding** [comment]
Mainly this is now OK, but can we be sure all items are in the right place as CHILDHOOD IMMUNISATION TYPE is missing from: Attributes: Ce and is showing as retired.

**Comment by AngelaFaulding** [comment]
CHILDHOOD IMMUNISATION TYPE is missing from: Attributes: Ce.
The Attribute link on the Data Element CHILDHOOD IMMUNISATION TYPE (COVER) goes to http://www.datadictionary.nhs.uk/data_dictionary/attributes/c/ce/childhood_immunisation_type_de.asp.

**Comment by AngelaFaulding** [comment]
CHILDHOOD IMMUNISATION TYPE is still missing from: Attributes: Ce.
The Attribute link on the Data Element CHILDHOOD IMMUNISATION TYPE (COVER) goes to http://www.datadictionary.nhs.uk/data_dictionary/attributes/c/ce/childhood_immunisation_type_de.asp.

**Comment by AngelaFaulding** [comment]
CHILDHOOD IMMUNISATION TYPE is now in the correct menu, issue closed.
