### ISSUE TITLE
Possibly incorrect data set definition: "NHS Continuing Healthcare Patient Level Data Set"

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#101]
The section "REFERRALS, ASSESSMENTS AND OUTCOMES" has duplicate field "CLINICAL COMMISSIONING GROUP ELIGIBILITY DECISION OUTCOME (NHS CONTINUING HEALTHCARE)" - the 20th and 29th fields in the section.  Not sure whether this is an error or not

**Comment by AngelaFaulding** [comment]
I will check, it sounds wrong.

**Comment by AngelaFaulding** [comment]
Jane is going to talk to DCB, this may need to be a DDCN.

**Comment by AngelaFaulding** [comment]
DDCN being produced to resolve this. This hasn't been resolved in time for the August release. Hopefully it could be fixed for the September release.

**Comment by AngelaFaulding** [comment]
Jane is progressing the DDCN. This hasn't been resolved for the September release. It will be incorporated when complete and assured.

**Comment by AngelaFaulding** [comment]
DDCN approved and incorporated. Will be in the November release.

**Comment by AngelaFaulding** [comment]
Fixed in DDCN 1790.
