### ISSUE TITLE
Duplicate Section Name: COSD Pathology

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#102]
In the COSD Pathology Data Set, there are currently two sections with name "PATHOLOGY DETAILS - CORE - PATHOLOGY" - is this correct?

https://www.datadictionary.nhs.uk/data_dictionary/messages/clinical_data_sets/data_sets/cancer_outcomes_and_services_data_set/cancer_outcomes_and_services_data_set_-_pathology_fr.asp?shownav=1

**Comment by AngelaFaulding** [comment]
I will call them Part 1 and Part 2.
I will fix in the August release.

**Comment by AngelaFaulding** [comment]
Updated in the August release to PATHOLOGY DETAILS PART 2 CORE - PATHOLOGY and PATHOLOGY DETAILS PART 1 CORE - PATHOLOGY, issue closed.
