### ISSUE TITLE
IMMUNOHISTOCHEMISTRY_NUCLEAR_EXPRESSION_INTACT_INDICATION_CODE - Needs "National Codes" label in DD

### ISSUE THREAD

**Issue by maxChappell** [NHSDigital/DataDictionaryPublication#103]
Next version of Likin's code will exclude this from ontoserver if label not present.

**Comment by AngelaFaulding** [comment]
National Codes: to be added.
This will be fixed in the August release.

**Comment by maxChappell** [comment]
This has been generated without the "National Codes" label in the June Release - enhanced run. Can you investigate why please @likin1 ?

**Comment by likin1** [comment]
Hi Maxine,

This is one of the cases mentioned in the excel sheet attached in defect 76. Your comment in the sheet says:-

"Add   National Codes text. Manual create earlier instance? Reported to Angela."

I had added a special case for this which is very much configurable.

**Comment by AngelaFaulding** [comment]
Being fixed.

**Comment by AngelaFaulding** [comment]
National Codes added in the August release, issue closed.
