### ISSUE TITLE
LANGUAGE CODE - should be fixed with issue 76 (web order)

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#104]
https://beta.datadictionary.nhs.uk/attributes/l/l/language_code.html
This is correct that it has no National Codes.

But the item shows:
Code | Description
Dummy Enumeration | Dummy

Can this be removed from this item? Or do I need to do something in Trevor to sort this?

**Comment by maxChappell** [comment]
Needs "National Codes:" label adding

**Comment by AngelaFaulding** [comment]
Cath says we shouldn't add National Codes.
Happy to discuss further.

**Comment by maxChappell** [comment]
That's fine from my perspective - it just means that we won't make fhir items for ontoserver to represent it.

**Comment by maxChappell** [comment]
Fixed on latest beta
