### ISSUE TITLE
Accommodate changes to Business Definition location

### ISSUE THREAD

**Issue by maxChappell** [NHSDigital/DataDictionaryPublication#106]
Some of the business definitions have been moved to a brand new folder - Web_Site_Content/**Supporting_Definitions** in the next release.

This affects processing by Likin's hyperlink de-referencing application AND the DITA generation processing (from which Steve grabs title case conversions and other metadata).

It may also affect Steve's processing (may need to add the folder explicitly to ensure that it is picked up and processed).

XML parameter file for Likin's applications has been updated to reflect this change and will be attached to this ticket.

**Comment by maxChappell** [comment]
[Parameters_v2.zip](https://github.com/NHSDigital/DataDictionaryPublication/files/5005946/Parameters_v2.zip)

**Comment by likin1** [comment]
Hi,

This has been fixed

**Comment by AngelaFaulding** [comment]
Pages still linking back to the old version, e.g. https://beta.datadictionary.nhs.uk/supporting_information/supporting_information/nhs_data_model_and_dictionary_service.html

**Comment by AngelaFaulding** [comment]
Still an issue so will fix in the October release

**Comment by AngelaFaulding** [comment]
Maxine - we are happy with this, do you need to do anything else?

**Comment by oughnic** [comment]
@maxChappell Can we close (assume yes if no reply by 5 October)

**Comment by maxChappell** [comment]
Don't close yet - part of general url changes mop-up activity
