### ISSUE TITLE
Data Sets Header Rows missing

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#108]
The blue header rows in data sets are the headings for a number of a number of groups, e.g COSDS has DIAGNOSTIC: CANCER PATHWAY CHOICE - CORE, DIAGNOSTIC: NON PRIMARY CANCER PATHWAY - CORE etc.
Without these the data set doesn't make any sense.

**Comment by maxChappell** [comment]
I can re-share the logic for understanding the headers.
