### ISSUE TITLE
Mandation information missing

### ISSUE THREAD

**Issue by maxChappell** [NHSDigital/DataDictionaryPublication#110]
See e.g. DIDS data set - imaging activity group. Mandation information missing (many data sets) M/R/O

**Comment by cach1** [comment]
request status update on this one - not sure why it is in September release - must be fixed for first go-live

**Comment by AngelaFaulding** [comment]
This is the text on the data set that I will patch in the September release.

**Comment by AngelaFaulding** [comment]
Patched in the September release, needs checking on the September beta version.

**Comment by AngelaFaulding** [comment]
Fixed
