### ISSUE TITLE
Hover text needed for lozenges for class, attribute etc.

### ISSUE THREAD

**Issue by maxChappell** [NHSDigital/DataDictionaryPublication#111]
Can the E for data element be changed to DE please too?

**Comment by oughnic** [comment]
This is two separate issues so needs to be split.

1. changing the styling is a CSS issue (and trivial).  I'll pick this up outside of this ticket.  @AngelaFaulding has final say on the e / de choice.
2. For the shortdesc for the map entries this feeds into the breaking up of the maps into bite-size chunks.  I'm minded to have dedicated topics for these and hang the detailed maps off those.

**Comment by AngelaFaulding** [comment]
We have had a few comments about the styling and would like e changing to de please.

**Comment by AngelaFaulding** [comment]
Nicholas decided it should stay as e so issue closed.
