### ISSUE TITLE
S Category Code (Att) - supplementary table - after code list is missing

### ISSUE THREAD

**Issue by maxChappell** [NHSDigital/DataDictionaryPublication#113]
For DD team to determine priority first - seems the table contents just present the same info for codes - just in a different format.

**Comment by cach1** [comment]
The original format was the 'missing' table and we added the 'normal' table so it would go through ontoserver.  Not urgent for go-live, next release would be good

**Comment by cach1** [comment]
To clarify for Maxine - the original format of this item was the 4 column table which is now missing - we corrected this for ontoserver by adding the standard format National Codes list, but we do need the 4 column table to appear in the description.
as above, not urgent for go-live

**Comment by maxChappell** [comment]
Need to work out mechanism for Likin code to flag to steve to pick up the rest

**Comment by AngelaFaulding** [comment]
Cath and are happy with this, so ticket closed.

Maxine - are you OK from an Ontoserver point of view?
