### ISSUE TITLE
Retired codes not displayed

### ISSUE THREAD

**Issue by maxChappell** [NHSDigital/DataDictionaryPublication#114]
See Care Professional Senior operating surgeon for cancer - the attribute itself is still active and should(?) show retired codes

**Comment by cach1** [comment]
item is CARE PROFESSIONAL SENIOR OPERATING SURGEON GRADE FOR CANCER (attr)

don't know why retired codes aren't showing though

**Comment by maxChappell** [comment]
Thank you James.
