### ISSUE TITLE
Data Elements with Permitted National Codes - but no National Codes defined

### ISSUE THREAD

**Issue by maxChappell** [NHSDigital/DataDictionaryPublication#115]
This means that they are not matching the common pattern and will not have term server content to represent these items.

GS1_APPLICATION_IDENTIFIER_(GLOBAL)
--
PERSON_GENOTYPIC_SEX_(NATIONAL_NEONATAL_DATA_SET)
WARD_DAY_PERIOD_AVAILABILITY_CODE
WARD_NIGHT_PERIOD_AVAILABILITY_CODE

**Comment by AngelaFaulding** [comment]
Being fixed.

**Comment by maxChappell** [comment]
Fix applied in DD. NHS D code updated to pass these in knitted txa class files, Assigned to Maxine - for testing. Also with James as now available in expanded xml file.
