### ISSUE TITLE
Codes appearing twice

### ISSUE THREAD

**Issue by maxChappell** [NHSDigital/DataDictionaryPublication#116]
Cancer Surgical Admission Type - National Codes appear twice on website.

DD team - can you add an "s" to "National Code" on the attribute - this is the likely cause

**Comment by maxChappell** [comment]
Also - Referral to treatment period status

**Comment by maxChappell** [comment]
Also Sickness Absence Indicator

**Comment by AngelaFaulding** [comment]
3 items fixed

**Comment by maxChappell** [comment]
Looks right on the website now
