### ISSUE TITLE
Links on home page

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#12]
Will there be links to:
- FAQS
- Help Pages (will there be a set of new help pages?)
- Links required on the front page, e.g. FAQs
- Do we need new Help Pages? The explanations of the items are still correct.
- No point in having the link to the Help Pages as it goes to DDV3

**Comment by oughnic** [comment]
New help and training pages transferred to a separate issue.

**Comment by AngelaFaulding** [comment]
This needs to be done by DMDS.

**Comment by AngelaFaulding** [comment]
To be done by Angie after meetings with Nicholas and Cath.
