### ISSUE TITLE
Additional fieldhead items not currently catered for

### ISSUE THREAD

**Issue by maxChappell** [NHSDigital/DataDictionaryPublication#120]
See Employee Local Identifier (de) as an example. Additional labels and values between format/length and National Codes (some of the extra fields have hyperlinks in labels and/or values).

We need this to get picked up too. Needs discussion with Oxford on how best to ensure this content gets picked up.

We could potentially add as extra txaclass file properties.

Need some indication of relative priority from DD team.

**Comment by AngelaFaulding** [comment]
Workforce data set Data Elements have extra rows for:
NWDS ID: 
NWDS Field Name:
ESR Field Name: 
These are not a showstopper. They are there for linkage purposes.

**Comment by maxChappell** [comment]
ODS codes will be turned into default codes in DD. NWDS items will need suppression by James' processing. Not to be implemented until the October DD release.

**Comment by AngelaFaulding** [comment]
There is a ticket for the ODS default code issue:
ODS Default Codes showing as National Codes #141
This is in the trunk and will be in the October release.

**Comment by maxChappell** [comment]
Can @jamesrwelch verify if suppression will be globally applied or specifically applied for the nwds items?

**Comment by oughnic** [comment]
Burned
