### ISSUE TITLE
Newborn Blood Spot Test Outcome Status (code) - has 2 $name properties

### ISSUE THREAD

**Issue by maxChappell** [NHSDigital/DataDictionaryPublication#124]
1 of them needs to be removed at source - please note which in here as it will affect ontoserver historic items too.

**Comment by AngelaFaulding** [comment]
Sorry Maxine I don't know what you mean?
There is one Attribute: NEWBORN BLOOD SPOT TEST OUTCOME STATUS and a number of linked Data Element: NEWBORN BLOOD SPOT TEST OUTCOME STATUS CODE (#####)
Please explain what you need me to do and to what item.

**Comment by maxChappell** [comment]
The attribute NEWBORN BLOOD SPOT TEST OUTCOME STATUS has 2 $name properties in the txaclass file - 1 of them needs to be removed

<property name="$name" value="NEWBORN_BLOOD_SPOT_TEST_OUTCOME_STATUS_CODE"/>
<property name="$name" value="NEWBORN_BLOOD_SPOT_TEST_OUTCOME_STATUS"/>

**Comment by maxChappell** [comment]
NEWBORN_BLOOD_SPOT_TEST_OUTCOME_STATUS vs NEWBORN_BLOOD_SPOT_TEST_OUTCOME_STATUS_CODE

**Comment by maxChappell** [comment]
We have also found similar on the data element ASA PHYSICAL STATUS CLASSIFICATION SYSTEM CODE

both carry the same name - but it is confusing processing

**Comment by maxChappell** [comment]
Will update this ticket with a more complete list

**Comment by AngelaFaulding** [comment]
Sorry I still don't get this.
This is what we have in the dictionary:
NEWBORN BLOOD SPOT TEST OUTCOME STATUS | Attribute |  
NEWBORN BLOOD SPOT TEST OUTCOME STATUS CODE (CONGENITAL HYPOTHYROIDISM) | Data Element |  
NEWBORN BLOOD SPOT TEST OUTCOME STATUS CODE (CYSTIC FIBROSIS) | Data Element |  
NEWBORN BLOOD SPOT TEST OUTCOME STATUS CODE (GLUTARIC ACIDURIA TYPE 1) | Data Element |  
NEWBORN BLOOD SPOT TEST OUTCOME STATUS CODE (HOMOCYSTINURIA) | Data Element |  
NEWBORN BLOOD SPOT TEST OUTCOME STATUS CODE (ISOVALERIC ACIDURIA) | Data Element |  
NEWBORN BLOOD SPOT TEST OUTCOME STATUS CODE (MAPLE SYRUP URINE DISEASE) | Data Element |  
NEWBORN BLOOD SPOT TEST OUTCOME STATUS CODE (MEDIUM CHAIN ACYL-COA DEHYDROGENASE DEFICIENCY) | Data Element |  
NEWBORN BLOOD SPOT TEST OUTCOME STATUS CODE (PHENYLKETONURIA) | Data Element |  
NEWBORN BLOOD SPOT TEST OUTCOME STATUS CODE (SICKLE CELL DISEASE) | Data Element

**Comment by maxChappell** [comment]
Fix in development to strip out identical duplicate properties and to strip out "incorrect" properties where there is a clash in values. Manual process to determine which item is correct/incorrect - needs DD team decision - any new ones will be output in a log file.
Decisions recorded in exception/parameter file for utility to strip/preserve as appropriate.

**Comment by maxChappell** [comment]
Will need to make sure that exception handling for this is incorporated into fhir gen work (next iteration for term server go-live).

However - this is now fixed for website publication.

**Comment by maxChappell** [comment]
When automating the publication pipeline - DD team will need to be made aware of any new property clashes as part of the process. identical duplicates are of no concern as they are now automatically stripped out.

**Comment by rajabr57** [comment]
11/5 - this needs to be put on Jenkins server

**Comment by maxChappell** [comment]
Completed. Can be closed now.
