### ISSUE TITLE
Simplify the package structure

### ISSUE THREAD

**Issue by oughnic** [NHSDigital/DataDictionaryPublication#129]
The current package structure in the data dictionary is mirrored in Mauro and the generated DITA.  This ticket is to determine whether to strip that structure down removing components for navigation

For example, move

- /attributes/**a/ar/**assignment_payscale_point_start_date to 
- /attributes/assignment_payscale_point_start_date

A decision is needed before the NHS Digital Terminology Server goes live in production.

**Comment by maxChappell** [comment]
URL's are now flattened in ontoserver and knitted files.

**Comment by oughnic** [comment]
@maxChappell Is this now complete
