### ISSUE TITLE
Ordering of CDS types landing page

### ISSUE THREAD

**Issue by cach1** [NHSDigital/DataDictionaryPublication#130]
within DD v3, this page https://www.datadictionary.nhs.uk/web_site_content/cds_supporting_information/commissioning_data_set_version_6-2_type_list.asp?shownav=1 provides a particular order for the CDS types within CDS V6-2.  Is it possible to replicate this in v3+?
Will need to discuss how this is done, we have a new CDS type 011 ECDS v6-2-3 publishing for release end of October...and a whole new CDS version (6-3) potentially April 21 (anticipating this will have a separate folder alongside 6-2 though - CDS versions dual run for a year or two generally).

**Comment by AngelaFaulding** [comment]
Link above not working. Correct link: https://v3.datadictionary.nhs.uk/web_site_content/cds_supporting_information/commissioning_data_set_version_6-2_type_list.asp?shownav=1
This will need resolving for the introduction of CDS 6-3.

**Comment by rajabr57** [comment]
5/5 - need James to advise on how to do this

**Comment by AngelaFaulding** [comment]
@jamesrwelch can be investigated with #268?

**Comment by AngelaFaulding** [comment]
Issue #268 was burned as the branch migration of CDS 6-3 was not done in time.

This still needs looking at as the landing page order for CDS 6-2 and CDS 6-3 still needs to match, e.g. https://v3.datadictionary.nhs.uk/web_site_content/cds_supporting_information/commissioning_data_set_version_6-2_type_list.asp?shownav=1

**Comment by rajabr57** [comment]
HI Angela

I’m confused (not difficult I know!!)

I thought that we had changed 268 to do a test run on Radiotherapy CR1736 and that this was done last week by Likin (albeit with some outstanding issues)

Is there a need now for another ticket to be raised in Jira regarding the CDS 6-2/6-3 issue?

Rachel

**Comment by AngelaFaulding** [comment]
Hi @rajabr57 . The landing page issue is for James to fix so does not need a Jira ticket.

**Comment by rajabr57** [comment]
Ah ok, thanks for the clarification Angie.

Rachel

**Comment by AngelaFaulding** [comment]
10/12/21 - should be able to do this in the data set folder when we have migrated to Mauro

**Comment by jamesrwelch** [comment]
Duplicate of #63?

**Comment by AngelaFaulding** [comment]
@jamesrwelch - is this #392?
If so I will close this ticket and #63.

**Comment by AngelaFaulding** [comment]
Issue closed as it is a duplicate of #392
