### ISSUE TITLE
Investigate why 8 knitted html files cannot be retrieved

### ISSUE THREAD

**Issue by maxChappell** [NHSDigital/DataDictionaryPublication#131]
Steve's processing is consistently missing 8 html files. html files are present though. Path and filename look correct.

    <DD_URL>https://v3.datadictionary.nhs.uk/data_dictionary/messages/clinical_data_sets/overviews/female_genital_mutilation_data_set_overview.asp</DD_URL>
      <error>
         <msg>no corresponding HTML found</msg>
         <path>file:/Users/steveharris/bitbucket/nhsdd-preprocessing/August_2020/knitted_htmlOutput/Data_Dictionary/Messages/Clinical_Data_Sets/Overviews/Female_Genital_Mutilation_Data_Set_Overview.htm</path>
      </error>

<DD_URL>https://v3.datadictionary.nhs.uk/data_dictionary/classes/r/referral_request_de.asp</DD_URL>
      <error>
         <msg>no corresponding HTML found</msg>
         <path>file:/Users/steveharris/bitbucket/nhsdd-preprocessing/August_2020/knitted_htmlOutput/Data_Dictionary/Classes/R/REFERRAL_REQUEST.htm</path>
      </error>

<DD_URL>https://v3.datadictionary.nhs.uk/data_dictionary/data_field_notes/t/tp/tprg-send_two_year_corrected_age_outcome_assessment_score_(communication_question_c)_de.asp</DD_URL>
      <error>
         <msg>no corresponding HTML found</msg>
         <path>file:/Users/steveharris/bitbucket/nhsdd-preprocessing/August_2020/knitted_htmlOutput/Data_Dictionary/Data_Field_Notes/T/TP/TPRG-SEND_TWO_YEAR_CORRECTED_AGE_OUTCOME_ASSESSMENT_SCORE_(COMMUNICATION_QUESTION_C).htm</path>
      </error>

<DD_URL>https://v3.datadictionary.nhs.uk/data_dictionary/data_field_notes/t/tp/tprg-send_two_year_corrected_age_outcome_assessment_score_(communication_question_b)_de.asp</DD_URL>
      <error>
         <msg>no corresponding HTML found</msg>
         <path>file:/Users/steveharris/bitbucket/nhsdd-preprocessing/August_2020/knitted_htmlOutput/Data_Dictionary/Data_Field_Notes/T/TP/TPRG-SEND_TWO_YEAR_CORRECTED_AGE_OUTCOME_ASSESSMENT_SCORE_(COMMUNICATION_QUESTION_B).htm</path>
      </error>

<DD_URL>https://v3.datadictionary.nhs.uk/data_dictionary/data_field_notes/s/set/sexual_health_and_hiv_activity_procedure_(snomed_ct)_de.asp</DD_URL>
      <error>
         <msg>no corresponding HTML found</msg>
         <path>file:/Users/steveharris/bitbucket/nhsdd-preprocessing/August_2020/knitted_htmlOutput/Data_Dictionary/Data_Field_Notes/S/Set/SEXUAL_HEALTH_AND_HIV_ACTIVITY_PROCEDURE_(SNOMED_CT).htm</path>
      </error>

<DD_URL>https://v3.datadictionary.nhs.uk/data_dictionary/data_field_notes/s/set/sexual_health_and_hiv_activity_health_issue_(snomed_ct)_de.asp</DD_URL>
      <error>
         <msg>no corresponding HTML found</msg>
         <path>file:/Users/steveharris/bitbucket/nhsdd-preprocessing/August_2020/knitted_htmlOutput/Data_Dictionary/Data_Field_Notes/S/Set/SEXUAL_HEALTH_AND_HIV_ACTIVITY_HEALTH_ISSUE_(SNOMED_CT).htm</path>
      </error>

<DD_URL>https://v3.datadictionary.nhs.uk/data_dictionary/nhs_business_definitions/d/day_care_facility_de.asp</DD_URL>
      <error>
         <msg>no corresponding HTML found</msg>
         <path>file:/Users/steveharris/bitbucket/nhsdd-preprocessing/August_2020/knitted_htmlOutput/Data_Dictionary/NHS_Business_Definitions/D/Day_Care_Facility.htm</path>
      </error>

<DD_URL>https://v3.datadictionary.nhs.uk/data_dictionary/nhs_business_definitions/e/educational_establishment_de.asp</DD_URL>
      <error>
         <msg>no corresponding HTML found</msg>
         <path>file:/Users/steveharris/bitbucket/nhsdd-preprocessing/August_2020/knitted_htmlOutput/Data_Dictionary/NHS_Business_Definitions/E/Educational_Establishment.htm</path>
      </error>

**Comment by maxChappell** [comment]
September release - expanded xml file from 15th Sep only misses 4 html files...
Data_Field_Notes/T/TP/TPRG-SEND_TWO_YEAR_CORRECTED_AGE_OUTCOME_ASSESSMENT_SCORE_(COMMUNICATION_QUESTION_C).htm

Data_Field_Notes/T/TP/TPRG-SEND_TWO_YEAR_CORRECTED_AGE_OUTCOME_ASSESSMENT_SCORE_(COMMUNICATION_QUESTION_B).htm

Data_Field_Notes/S/Set/SEXUAL_HEALTH_AND_HIV_ACTIVITY_PROCEDURE_(SNOMED_CT).htm

Data_Field_Notes/S/Set/SEXUAL_HEALTH_AND_HIV_ACTIVITY_HEALTH_ISSUE_(SNOMED_CT).htm

**Comment by maxChappell** [comment]
Angela has confirmed that the 4 that are now picked up ok had some form of edit between aug and sep releases. Patch in DD needed?

**Comment by AngelaFaulding** [comment]
I would say that the last four have failed as they have special characters:

SEXUAL HEALTH AND HIV ACTIVITY PROCEDURE (SNOMED CT) has:
(7138802 or <129152009)

SEXUAL HEALTH AND HIV ACTIVITY HEALTH ISSUE (SNOMED CT) has:
(<404684003 or <243796009)

TPRG-SEND TWO YEAR CORRECTED AGE OUTCOME ASSESSMENT SCORE (COMMUNICATION QUESTION C) has:
The question asks "Does the child have <5 meaningful words, vocalisations or signs?".

TPRG-SEND TWO YEAR CORRECTED AGE OUTCOME ASSESSMENT SCORE (COMMUNICATION QUESTION B) has:
The question asks "Does this child have difficulty with speech (<10 words/signs)?".

**Comment by maxChappell** [comment]
Thanks Angela. Root cause identified - all carry < signs that are not escaped in the html file. 

Resolution choices:
Patch in DD
Fix in knitted app
Fix at ingestion

To be agreed on call

**Comment by maxChappell** [comment]
Fix agreed on collab call with Oxford on 29/09.

Likin to apply specific patch at end of knitted txa and html file process - to search for the strings in the remaining four files and add &lt; escape. Can be done manually for october release.

**Comment by cach1** [comment]
interestingly, MURPHY ST JUDE STAGE  https://www.datadictionary.nhs.uk/attributes/murphy_st_jude_stage.html?hl=  (value 4) does work with these < > characters - is this because it is on ontoserver rather than in DD html?

**Comment by maxChappell** [comment]
Yes - Ontoserver makes the difference here.

**Comment by maxChappell** [comment]
October release - items appear to have come through fine. Not sure how. Will keep ticket open until after November release.
