### ISSUE TITLE
Links to http://www.datadictionary.nhs.uk/

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#132]
Nicholas said this morning that links to https://v3.datadictionary.nhs.uk/ were OK.

Some data elements and attributes link to http://www.datadictionary.nhs.uk/, e.g.
ADULT MENTAL HEALTH CARE CLUSTER CODE (INITIAL), https://beta.datadictionary.nhs.uk/data_elements/a/ad/adult_mental_health_care_cluster_code__initial_.html
REFERRAL TO TREATMENT PERIOD STATUS, https://modelcatalogue.cs.ox.ac.uk/datadictionary/data_elements/r/ref/referral_to_treatment_period_status.html

Maxine is this what you and Likin are fixing?

**Comment by maxChappell** [comment]
This is because we haven't re-run FHIR generation since the v3www change was applied.

Next piece for Likin -
Update url de-referencing for FHIR generation too.
Needs decision on ticket #129 first

**Comment by maxChappell** [comment]
FHIR gen has been re-run. Links look OK now to me
