### ISSUE TITLE
Reconcile Archive URL's from DD for FHIR gen and 3++ exposure of FHIR items

### ISSUE THREAD

**Issue by maxChappell** [NHSDigital/DataDictionaryPublication#134]
Will need to be completed before Term Server go-live.

04/01/21 - Run-through complete, testing to start now

**Comment by rajabr57** [comment]
11/5 - in progress (LG)

**Comment by GSChandel** [comment]
21/06 - in progress.

**Comment by maxChappell** [comment]
Decision made by NO that we won't add archive URL's into the R4 items - as there is no long term guarantee that the url's will remain resolvable in the long term.
