### ISSUE TITLE
Tidy up Title Case Conversions 

### ISSUE THREAD

**Issue by maxChappell** [NHSDigital/DataDictionaryPublication#135]
Some Acronyms are coming through as camel case - instead of uppercase. e.g. ASA in asa_physical_status_classification_system_code

Angela assigned - so any spotted can be added to this ticket.

**Comment by maxChappell** [comment]
GS1 vs Gs1 - (Supporting Definitions)

**Comment by maxChappell** [comment]
READ codes vs Read Codes

**Comment by maxChappell** [comment]
TRUD vs TRUD

**Comment by maxChappell** [comment]
All of the above are found under supporting definitions folder

**Comment by AngelaFaulding** [comment]
GS1 is OK in the text but the name is still Gs1. Also:
Gs1 Application Identifier (Global)
Gs1 Application Identifier (Internal)
Gs1 Global Service Relation Number

TRUD is OK in the text but the name is still Technology Reference Data Update Distribution (Trud).

Also still have names as:
International Classification of Diseases (Icd)
International Classification of Diseases for Oncology (Icd-o)
