### ISSUE TITLE
Preparatory items not working

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#137]
All items that have the property "isPrepatory" ticked as true are not displaying correctly.

The text should display as "This item is being used for development purposes and has not yet been approved." but the full item is showing, e.g. AMBULANCE CALL RESPONSE CATEGORY
https://www.datadictionary.nhs.uk/data_dictionary/attributes/a/age/ambulance_call_response_category_de.asp?shownav=1

https://modelcatalogue.cs.ox.ac.uk/datadictionary_sept/attributes/ambulance_call_response_category.html

**Comment by maxChappell** [comment]
Not a requirement I've previously been aware of

All we do is pass through the content as published..so this by definition shouldn't be happening..will need a discussion @AngelaFaulding

**Comment by AngelaFaulding** [comment]
Cath advised of this requirement along with all others.
The tick box results in the authored text to be replaced with text from a template.

**Comment by jamesrwelch** [comment]
Yep, sorry, I hadn't realised.  I'm getting those properties through in the XML so I can make the change in my next iteration.

**Comment by cach1** [comment]
Had a brief conversation with Maxine about this - at least one of the current Prep items has an associated codeset, which is now on ontoserver of course.....which gives it the wrong start date...not entirely sure if that matters for now, but needs further thought.  We need to decide if these get suppressed from ontoserver going forward.  We will need this functionality for 3++ going forward too.

**Comment by AngelaFaulding** [comment]
jameswelch  5:30 PM
If Steve's making the changes to reprieve the "National Codes" tag in the attribute definitions, I can update the pipeline to pull those out and present them.
If you want me to do the thing with the prep items, I'm ready to do that.

Cath Chilcott  5:46 PM
ok thankyou.  So the Prep items - we'll live with those for this release.  Not sure what the National Codes reprieve thing is exactly (or where the request came from) but if its just putting the words 'national codes' above the table in the attribute layout, not bothered about that for this release either

jameswelch  5:48 PM
Well once the words appear I’ll be able to pull the codes out of the definition and have them as modelled content, but yes, to the end user, the effect won’t be much more than you describe

**Comment by AngelaFaulding** [comment]
AMBULANCE CALL RESPONSE CATEGORY now has the prep text but the codes are still there.
The NHS Business Definitions have the text but the short description is showing, e.g. Community First Responder

**Comment by AngelaFaulding** [comment]
All OK except the PLICS overview, will be fixed in the October release

**Comment by maxChappell** [comment]
I will raise a separate ticket for handling this on ontoserver

**Comment by AngelaFaulding** [comment]
@maxChappell Shall I close this now as you have created a new issue for Ontoserver?
