### ISSUE TITLE
Need to decide if we want to distinguish between permitted and default codes on the website

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#140]
Code 9 on the Data Element is showing as "Default Code 1"
It should be "9 - Not Known (Not Recorded)"

**Comment by maxChappell** [comment]
Both of the above are on Ontoserver

Another Ontoserver example is Person Stated Gender Code (de) - the default code "X" is showing as a national code, rather than a default code.

Similar with Person Stated Gender Code (National Joint Registry) default code is a) listed as a national code and b) should be 0 - Not Known    - but code 0 is showing as "default code 1"

**Comment by maxChappell** [comment]
Non-Ontoserver examples:

Admission_Method_Code(Hospital_Provider_spell) - default code is showing correctly...but the National Codes from the attribute are not displayed. This "issue" is not a showstopper, having them visible would match the pattern with ontoserver content though (dispalyed as "Permitted Codes".

**Comment by maxChappell** [comment]
Another Non-ontoserver example is Employment Contract Nature. default codes (extra fieldhead) items are showing fine on the de - but list of codes from attribute not showing on the de. Think this is a 3+ refinement - because, just to complicate matters - these codes have additional headings.

**Comment by AngelaFaulding** [comment]
All except ADMISSION METHOD CODE (HOSPITAL PROVIDER SPELL) and Employment Contract Nature are fixed.

ADMISSION METHOD CODE (HOSPITAL PROVIDER SPELL) will be fixed in Together in the October release.

Employment Contract Nature is the Workforce issue.#145

**Comment by maxChappell** [comment]
Differentiation between National, Permitted and Default codes needs more work re Data Element Representations. Codes from the attribute are not consistently represented - see S category code and Person stated gender code

**Comment by maxChappell** [comment]
Needs a decision from cach1 or NO please

**Comment by AngelaFaulding** [comment]
Decision  by Cath: a separate table s required for permitted and default codes.
James to test next week.

**Comment by maxChappell** [comment]
Test Run completed by JW. 12/01/21

**Comment by AngelaFaulding** [comment]
James has completed a test (https://modelcatalogue.cs.ox.ac.uk/datadictionary_november) and will implement in the January release.
See #234 for further request to James.

**Comment by AngelaFaulding** [comment]
January release to be checked to ensure this works.

**Comment by AngelaFaulding** [comment]
The January release has National Codes, Permitted National Codes and Default Codes.
Thanks James
