### ISSUE TITLE
ODS Default Codes showing as National Codes

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#141]
ODS Default Codes are showing as National Codes, e.g. ORGANISATION IDENTIFIER (CODE OF PROVIDER)

The "ODS Default Codes:" reference will be replaced with "Default Codes" in the October release.

**Comment by maxChappell** [comment]
@oughnic and @cach1 - do any of these need to be in ontoserver for historical reasons?

**Comment by maxChappell** [comment]
Don't worry about historic fix for ontoserver - discussed with Cath on 27th October

**Comment by AngelaFaulding** [comment]
Maxine - can this now be closed as they appear OK on the October release?
