### ISSUE TITLE
Error on Cell Class Relationships

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#143]
The old dictionary has:
K | may be related to one or more CYTOLOGICAL ABNORMALITY
K | may be related to one and only one TISSUE
See https://v3.datadictionary.nhs.uk/data_dictionary/classes/c/cell_re.asp?shownav=1

The new version has:
Key | must be related to one and only one | CELL
Key | must be related to one or more | CELL
See https://www.datadictionary.nhs.uk/classes/cell.html

**Comment by AngelaFaulding** [comment]
The relationships on Tissue are correct:
Key | must be related to one or more | CELL
  | may be part of one or more | PERSON ORGAN
  | must be related to one or more | TISSUE TRANSPLANT

The relationships on CYTOLOGICAL ABNORMALITY are correct:
Key | must be related to one and only one | CELL
Key | may be related to one or more | CYTOLOGICAL ABNORMALITY

**Comment by maxChappell** [comment]
linked to #179

**Comment by AngelaFaulding** [comment]
This linked to #179 which James is looking

**Comment by rajabr57** [comment]
5/5 Awaiting update from James

**Comment by jamesrwelch** [comment]
Issue found and hopefully resolved for the June release

**Comment by AngelaFaulding** [comment]
The examples above are fixed so this issue is closed.
If anymore are found a new issue will be created.
