### ISSUE TITLE
XML_Schema_TRUD_Download. page missing (links on overviews of data sets which have a schema eg CDS, DIDS)

### ISSUE THREAD

**Issue by cach1** [NHSDigital/DataDictionaryPublication#144]
can't find XML_Schema_TRUD_Download. page in all items either - presume it should be a Supporting Information

**Comment by AngelaFaulding** [comment]
It is under data_dictionary/messages/message_documentation/xml_schema_download/xml_schema_trud_download.asp?shownav=1
Similar to the XML Schema Constraints pages.
Do you want me to move it?

**Comment by cach1** [comment]
no I think James should process it if he can - he is processing all the schema constraints pages on that page already

**Comment by maxChappell** [comment]
Can confirm item is available in the xml file

**Comment by maxChappell** [comment]
Item to reside in supporting information when processed.
maxine assigned to reconcile URL's

**Comment by AngelaFaulding** [comment]
I have moved this to Supporting Information for the November release.

**Comment by AngelaFaulding** [comment]
Links now working.
