### ISSUE TITLE
Test previews of the new version

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#147]
We need to be able to create previews of CRs in the new version for review by developers.
These are added to the test area on the website for developers to be able to review and sign off CRs.

The previews of the old dictionary are OK for team review but not for developers. How do we do this?

**Comment by oughnic** [comment]
This will be challenging to deliver.  @maxChappell may have an approach to share pre-release codes but that is tricky.  It may be better to fall back to using old processes initially and be clear that it is not accessible.

**Comment by oughnic** [comment]
@maxChappell  Probably best to remove 3+ Refinements label

**Comment by AngelaFaulding** [comment]
Issues closed as per Nicholas's comment.
