### ISSUE TITLE
National Code definitions - text following a link is being pushed to the next line

### ISSUE THREAD

**Issue by cach1** [NHSDigital/DataDictionaryPublication#149]
Example - SITUATION SCHEME IN USE
Happening throughout wherever text follows a link to something

**Comment by maxChappell** [comment]
Looks like this is an issue in the original html - looking at the ICD example (code 01 on Situation Scheme in Use) the anchor is closed in the middle of the label "ICD-10"

&amp;lt;a href=&amp;quot;http://www.datadictionary.nhs.uk/web_site_content/supporting_information/clinical_coding/international_classification_of_diseases_(icd).asp&amp;quot;&amp;gt;ICD**&amp;lt;/a&amp;gt;**-10

It should be &amp;lt;a href=&amp;quot;http://www.datadictionary.nhs.uk/web_site_content/supporting_information/clinical_coding/international_classification_of_diseases_(icd).asp&amp;quot;&amp;gt;ICD-10&amp;lt;/a&amp;gt;

**Comment by AngelaFaulding** [comment]
@maxChappell The name in Together is International_Classification_of_Diseases_(ICD).
The txaClass file name is International_Classification_of_Diseases_(ICD).txaClass20
How do you want me to change the item?

**Comment by rajabr57** [comment]
5/5 Awaiting update from James

**Comment by AngelaFaulding** [comment]
Example: https://www.datadictionary.nhs.uk/attributes/diagnosis_scheme_in_use.html

James to investigate

**Comment by jamesrwelch** [comment]
Issue found and hopefully resolved for the June release

**Comment by AngelaFaulding** [comment]
This is the same as #44 so issue closed.
