### ISSUE TITLE
Banner label for publications release/archive and preview

### ISSUE THREAD

**Issue by maxChappell** [NHSDigital/DataDictionaryPublication#150]
Team will need to be able to set a parameter at publication which populates blue banner on home page for previews, actual releases and for archive.
Parameter/capability to trigger use of different stylesheets for the different publication types.

**Comment by oughnic** [comment]
This is already in place (Archive publication is an example)
@maxChappell @AngelaFaulding Can we close?

**Comment by AngelaFaulding** [comment]
This is already in place, there is a separate ticket for previews when 3++ is live.
