### ISSUE TITLE
Treatment Function Code - exception handling for retired items in ontoserver

### ISSUE THREAD

**Issue by maxChappell** [NHSDigital/DataDictionaryPublication#152]
This item does not show retired items in the same way as the rest of the DD - so we are going to need to do some bespoke code so that statuses for concepts are correctly set on ontoserver - they are all active at present.

**Comment by maxChappell** [comment]
Code 990 - isn't showing as retired (grey) in october release @AngelaFaulding. Short discussion needed with you to agree mechanism for future retirements from this item. We will reconcile for historic content.

**Comment by AngelaFaulding** [comment]
It is in grey. You can see it in the old version at: https://v3.datadictionary.nhs.uk/data_dictionary/attributes/t/tran/treatment_function_code_de.asp?shownav=1

**Comment by maxChappell** [comment]
But it isn't in the 3+ website

**Comment by AngelaFaulding** [comment]
@maxChappell, do you need me to do anything as they grey font is in Together.

**Comment by maxChappell** [comment]
21/06/21 - coding complete - ready for review

**Comment by AngelaFaulding** [comment]
@maxChappell are you happy for this to be closed or is further work required?

**Comment by GSChandel** [comment]
Awaiting Testing

**Comment by GSChandel** [comment]
Scheduled for review on 14/07/2021

**Comment by maxChappell** [comment]
Historic retirements of codes appears to be correctly handled now and statuses are showing as retired for old style and new style of retired codes for this item.
