### ISSUE TITLE
SNOMED CT CODE

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#153]
I'm not sure who needs to fix this. I think the issue is that the item is the Format/ Length.

In 3+ Where Used, see https://www.datadictionary.nhs.uk/data_elements/snomed_ct_code.html, there are two Data Elements:

DISEASE OUTBREAK NOTIFICATION
SNOMED CT CODE

In the old version, see https://v3.datadictionary.nhs.uk/data_dictionary/data_field_notes/s/sk/snomed_ct_code_wu.asp?shownav=1, there are many Data Elements:

ACCESSIBLE INFORMATION COMMUNICATION SUPPORT CODE (SNOMED CT) 
ACCESSIBLE INFORMATION CONTACT METHOD CODE (SNOMED CT) 
ACCESSIBLE INFORMATION PROFESSIONAL REQUIRED CODE (SNOMED CT) 
ACCESSIBLE INFORMATION SPECIFIC INFORMATION FORMAT CODE (SNOMED CT) 
ACCOMMODATION STATUS (SNOMED CT) 
AIDS DEFINING ILLNESS CODE ADULT (SNOMED CT) 
ASSISTIVE TECHNOLOGY FINDING (SNOMED CT) 
CHLAMYDIA TEST RESULT (SNOMED CT) 
CODED ASSESSMENT TOOL TYPE (SNOMED CT) 
CODED FINDING (SNOMED CT) 
CODED OBSERVATION (SNOMED CT) 
COMORBIDITY (SNOMED CT) 
DIAGNOSIS (SNOMED CT ON ADMISSION TO NEONATAL CRITICAL CARE) 
DIAGNOSIS (SNOMED CT ON NEONATAL CRITICAL CARE DAILY CARE DATE) 
DIAGNOSIS (SNOMED CT RECORDED ON DISCHARGE FROM NEONATAL CRITICAL CARE) 
DIAGNOSIS (SNOMED CT) 
DIAGNOSTIC PROCEDURE (SNOMED CT) 
DISEASE OUTBREAK NOTIFICATION 
DISEASE OUTBREAK NOTIFICATION (SNOMED CT) 
DISEASE OUTBREAK NOTIFICATION DESCRIPTION 
EMERGENCY CARE ACUITY (SNOMED CT) 
EMERGENCY CARE ARRIVAL MODE (SNOMED CT) 
EMERGENCY CARE ATTENDANCE SOURCE (SNOMED CT) 
EMERGENCY CARE CHIEF COMPLAINT (SNOMED CT) 
EMERGENCY CARE CLINICAL INVESTIGATION (SNOMED CT) 
EMERGENCY CARE DIAGNOSIS (SNOMED CT) 
EMERGENCY CARE DIAGNOSIS QUALIFIER (SNOMED CT) 
EMERGENCY CARE DISCHARGE DESTINATION (SNOMED CT) 
EMERGENCY CARE DISCHARGE FOLLOW UP (SNOMED CT) 
EMERGENCY CARE DISCHARGE INFORMATION GIVEN (SNOMED CT) 
EMERGENCY CARE DISCHARGE STATUS (SNOMED CT) 
EMERGENCY CARE INJURY ACTIVITY STATUS (SNOMED CT) 
EMERGENCY CARE INJURY ACTIVITY TYPE (SNOMED CT) 
EMERGENCY CARE INJURY ALCOHOL OR DRUG INVOLVEMENT (SNOMED CT) 
EMERGENCY CARE INJURY INTENT (SNOMED CT) 
EMERGENCY CARE INJURY MECHANISM (SNOMED CT) 
EMERGENCY CARE PLACE OF INJURY (SNOMED CT) 
EMERGENCY CARE PROCEDURE (SNOMED CT) 
IMAGING CODE (SNOMED CT) 
INTERPRETER LANGUAGE (SNOMED CT) 
OCCUPATION MOTHER (SNOMED CT) 
PREFERRED SPOKEN LANGUAGE (SNOMED CT) 
PRIMARY PROCEDURE (SNOMED CT) 
PROCEDURE (SNOMED CT ON NEONATAL CRITICAL CARE DAILY CARE DATE) 
PROCEDURE (SNOMED CT RECORDED ON DISCHARGE FROM NEONATAL CRITICAL CARE) 
PROCEDURE (SNOMED CT) 
REFERRED TO SERVICE (SNOMED CT) 
SAFEGUARDING CONCERN (SNOMED CT) 
SAMPLE TEST RESULT ORGANISM TYPE (SNOMED CT) 
SEXUAL HEALTH SERVICE ATTENDANCE SOURCE (SNOMED CT) 
SNOMED CT CODE 
SOCIAL AND PERSONAL CIRCUMSTANCE (SNOMED CT) 
SPECIMEN TYPE (CHLAMYDIA TESTING SNOMED CT) 
THERAPEUTIC INDICATION CODE (SNOMED CT)

It is the same issue for:
DM+D CODE
See https://www.datadictionary.nhs.uk/data_elements/dm_d_code.html#element_dm_d_code.where_used and https://www.datadictionary.nhs.uk/data_elements/icd-10_code.html#element_icd-10_code.where_used

ICD-10 CODE
See https://v3.datadictionary.nhs.uk/data_dictionary/data_field_notes/i/icd-10_code_wu.asp?shownav=1 and https://v3.datadictionary.nhs.uk/version3test/web_root/data_elements/icd-10_code.html#element_icd-10_code.where_used

ICD-O CODE
https://v3.datadictionary.nhs.uk/data_dictionary/data_field_notes/i/icd-o_code_wu.asp?shownav=1 and https://www.datadictionary.nhs.uk/data_elements/icd-o_code.html#element_icd-o_code.where_used

OPCS-4 CODE
https://v3.datadictionary.nhs.uk/data_dictionary/data_field_notes/o/oc/opcs-4_code_wu.asp?shownav=1 and https://www.datadictionary.nhs.uk/data_elements/opcs-4_code.html#element_opcs-4_code.where_used

NICIP CODE
https://v3.datadictionary.nhs.uk/data_dictionary/data_field_notes/n/nhs/nicip_code_wu.asp?shownav=1 and https://www.datadictionary.nhs.uk/data_elements/nicip_code.html#element_nicip_code.where_used

READ CODE
https://v3.datadictionary.nhs.uk/data_dictionary/data_field_notes/r/read_code_wu.asp?shownav=1 and https://www.datadictionary.nhs.uk/data_elements/read_code.html#element_read_code.where_used

**Comment by maxChappell** [comment]
This is one for @jamesrwelch I'm afraid.

**Comment by AngelaFaulding** [comment]
@jamesrwelch . THERAPEUTIC INDICATION CODE (SNOMED CT) is still missing from https://www.datadictionary.nhs.uk/data_elements/snomed_ct_code.html.
The reason is that the Format / Length is still SNOMED_CT_CODE.
Can that be fixed please?

I have checked the others and the where used matches.

**Comment by AngelaFaulding** [comment]
Check if this is fixed in the January release

**Comment by AngelaFaulding** [comment]
This still isn't fixed in the January release.
THERAPEUTIC INDICATION CODE (SNOMED CT) still has "Format / Length - SNOMED_CT_CODE"(https://datadictionary.nhs.uk/data_elements/therapeutic_indication_code__snomed_ct_.html)
Therefore, THERAPEUTIC INDICATION CODE (SNOMED CT) is not listed on https://datadictionary.nhs.uk/data_elements/snomed_ct_code.html.

I don't know if this is a DMDS or Oxford issue.

**Comment by rajabr57** [comment]
5/5 Awaiting update from James

**Comment by AngelaFaulding** [comment]
James to fix in the June release

**Comment by jamesrwelch** [comment]
I've looked.  The THERAPEUTIC INDICATION CODE (SNOMED CT) seems to be the only one affected by this issue.  The format-length-link is not being provided in the XML file.  This is probably because all other instances are of the form `See X`, and this one is just `X`.  If this change was to be made at source, it might resolve the whole thing, and this would be the simplest way to do it

**Comment by AngelaFaulding** [comment]
This was identified in the DD-formatLengths document provided by James and has been included to be fixed in the next release. It was too late for the June release.

**Comment by AngelaFaulding** [comment]
OK in the August release so issue closed.
