### ISSUE TITLE
Broken Links in Published Version 3+

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#154]
There are a  number pages in Version 3 which no longer exist in Version 3+
Examples include:
https://v3.datadictionary.nhs.uk/data_dictionary/messages/cancer_outcomes_and_services_data_set_introduction.html
https://v3.datadictionary.nhs.uk/web_site_content/pages/help_pages/commissioning_data_sets_help.html
https://v3.datadictionary.nhs.uk/web_site_content/pages/help_pages/data_sets_introduction.html

These are contained on pages, e.g. 
https://www.datadictionary.nhs.uk/attributes/cancer_or_symptomatic_breast_referral_patient_status.html
https://www.datadictionary.nhs.uk/attributes/critical_care_activity_code.html
https://www.datadictionary.nhs.uk/nhs_business_definitions/data_coordination_board.html

This means that we have a number of broken links in the published Version 3+.

Is there any way we can identify all these pages and then decide how we need to address them in Together for Version 3+?

**Comment by AngelaFaulding** [comment]
Nicholas has said:  Do we need them now?  If so, we need to move the content somewhere to make them work nicely.

Can we move the introduction pages to Supporting Information and then the links will work and the information will still be there.

**Comment by maxChappell** [comment]
Seems all dataset "introduction" pages are not being ingested currently. Angela will provide a list of the pages.

**Comment by AngelaFaulding** [comment]
I will fix the links to the Help Pages.

**Comment by AngelaFaulding** [comment]
Missing introduction pages:

https://v3.datadictionary.nhs.uk/data_dictionary/messages/supporting_data_sets/overviews/plics_data_set_overview/patient_level_information_costing_system_acute_data_set_introduction.asp?shownav=1

https://v3.datadictionary.nhs.uk/data_dictionary/messages/clinical_data_sets/overviews/national_neonatal_data_set_overviews/national_neonatal_data_set_introduction.asp?shownav=1

https://v3.datadictionary.nhs.uk/data_dictionary/messages/clinical_data_sets/overviews/cancer_outcomes_and_services_data_set_overviews/cancer_outcomes_and_services_data_set_introduction.asp?shownav=1

https://v3.datadictionary.nhs.uk/data_dictionary/messages/clinical_content/overviews/national_joint_registry_data_set_overviews/national_joint_registry_data_set_introduction.asp?shownav=1

**Comment by AngelaFaulding** [comment]
Checked the November release.
CANCER OR SYMPTOMATIC BREAST REFERRAL PATIENT STATUS - this is no longer a broken link. It is just text but appears as a link.  See Re-introduce the introduction pages #162

CRITICAL CARE ACTIVITY CODE - is OK, now goes to Commissioning Data Sets Introduction.

Data Coordination Board - is OK, I fixed it in Together.

**Comment by AngelaFaulding** [comment]
Maxine - these are the latest set of broken links:
[Broken Links.docx](https://github.com/NHSDigital/DataDictionaryPublication/files/5658459/Broken.Links.docx)

**Comment by rajabr57** [comment]
5/5 Awaiting update from James

**Comment by AngelaFaulding** [comment]
Closed, duplicate of #162
