### ISSUE TITLE
Cover Data Set

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#155]
I'm not sure who can fix this.

Something strange has happened to the Cover Data Set, see
https://www.datadictionary.nhs.uk/data_sets/central_return_data_sets/cover_of_vaccination_evaluated_rapidly__cover__data_set.html#dataset_cover_of_vaccination_evaluated_rapidly__cover__data_set

It has:
Public Health England  is mandated to report on vaccine uptake figures for children aged one, two and five years for the Local Authority (upper tier) resident population for the Public Health Outcomes Framework (PHOF) indicator 3.03 Population vaccination coverage. https://www.phoutcomes.info/public-health-outcomes-framework#gid/1000043

It should be:
Public Health England is mandated to report on vaccine uptake figures for children aged one, two and five years for the Local Authority (upper tier) resident population for the Public Health Outcomes Framework (PHOF) indicator 3.03 Population vaccination coverage.
See https://v3.datadictionary.nhs.uk/data_dictionary/messages/central_return_data_sets/data_sets/cover_of_vaccination_evaluated_rapidly_(cover)_data_set_fr.asp?shownav=1

**Comment by maxChappell** [comment]
Have checked the v3 site - it's present there too (just somehow hidden). If you view the source on the frame the extra url is in there...so needs fixing at source (removal from txa file).
Search for string https://www.phoutcomes.info/public-health-outcomes-framework#gid/1000043

**Comment by AngelaFaulding** [comment]
The page is odd as it has this and span tags. I will fix for the November release.

**Comment by AngelaFaulding** [comment]
Fixed in the November release.
