### ISSUE TITLE
Link to Secondary Uses Service

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#156]
See https://datadictionary.nhs.uk/data_sets/cds_v6-2/cds_v6-2_type_010_-_accident_and_emergency_cds.html#dataset_cds_v6-2_type_010_-_accident_and_emergency_cds

There are a number of links to Secondary Uses Service on this page.
Some go to: https://datadictionary.nhs.uk/supporting_information/secondary_uses_service.html
Some go to: https://v3.datadictionary.nhs.uk/web_site_content/supporting_definitions/secondary_uses_service.html

The ones that go to https://v3.datadictionary.nhs.uk/web_site_content/supporting_definitions/secondary_uses_service.html result in broken links

**Comment by maxChappell** [comment]
Global fix needs to be applied at Likin's end of pipeline. Will add this to a master URL reconcilliation ticket (not yet raised)

Fix in this instance will be to change Supporting_Definition in URL's to Supporting_Information

**Comment by AngelaFaulding** [comment]
I have checked the October release and there are still broken links.

**Comment by maxChappell** [comment]
November release - XML Schema TRUD Download link is incorrect.

It should be https://datadictionary.nhs.uk/supporting_information/xml_schema_trud_download.html

But it is pointing to https://v3.datadictionary.nhs.uk/data_dictionary/messages/xml_schema_trud_download.html

Links to Secondary Uses Page ...all good in the introduction, but wrong under specification

Also noted - I cannot see this item in the CDS type list menus on 3+..

**Comment by maxChappell** [comment]
The page this was reported for no longer exists, so closing the ticket
