### ISSUE TITLE
Children of a referenceType blocking SVG of classes being developed

### ISSUE THREAD

**Issue by oughnic** [NHSDigital/DataDictionaryPublication#157]
@jamesrwelch has identified in trying to get the children of a ReferenceType,he is getting :
`For \"?children\" left-hand operand: Expected a node, but this has evaluated to an extended_hash+string (ox.softeng.metadatacatalogue.core.catalogue.linkable.component.datatype.DataType_$$_jvst11a_17 wrapped into f.e.b.StringModel):\n==> dataElement.dataType`

This may imply that the underlying XML is not generating correctly.

**Comment by AngelaFaulding** [comment]
21/12/21 - Is this needed for go live.

**Comment by AngelaFaulding** [comment]
Agreed this is Post Migration.

**Comment by AngelaFaulding** [comment]
James thinks this is fixed.
