### ISSUE TITLE
Potentially missing data

### ISSUE THREAD

**Issue by maxChappell** [NHSDigital/DataDictionaryPublication#159]
If you take a look at the all items index "A" - we have fewer items showing on the new site.
https://v3.datadictionary.nhs.uk/retired/web_site_content/pages/domains/a__and__e_arrival_mode_de.asp?shownav=1

does not exist on new site.

We don't seem to have access to the "domains" sub-folder (totally new folder to me), so have never been processing it...

Question is - do we need to rectify this?

**Comment by AngelaFaulding** [comment]
This is on the new site: https://datadictionary.nhs.uk/data_elements/retired/a_and_e_arrival_mode.html

Domains is a folder under the retired web site content pages folder structure. Have none of those folders been processed? I've checked a couple on V3+ and can't see them

**Comment by maxChappell** [comment]
V3 site all items has:

Item Name | Item Type |  
-- | -- | --
A and E ARRIVAL MODE (retired) | Data Element |  
A and E ARRIVAL MODE (retired) | **Domain**

New site doesn't have the domain item

**Comment by maxChappell** [comment]
I don't think we get these sub folders for processing - have checked the June 20 unmodified txaclass file zip - the folder isn't there

**Comment by maxChappell** [comment]
I don't have a more recent unmodifed set of txa files - i.e. pre pipeline processing

@likin1 when you get the release files for processing - do you have any content in a web_site_content/pages/domains folder?

Is the domains folder itself present?

**Comment by maxChappell** [comment]
Decision reached on collab call 22/10/2020 - NO decided not to bring these into mauro.
