### ISSUE TITLE
YEAR AND MONTH OF SYMPTOMS ONSET (IMPROVING ACCESS TO PSYCHOLOGICAL THERAPIES)

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#160]
Version 3 shows YEAR AND MONTH OF SYMPTOMS ONSET (IMPROVING ACCESS TO PSYCHOLOGICAL THERAPIES) linked to the attribute YEAR AND MONTH OF SYMPTOMS ONSET FOR IMPROVING ACCESS TO PSYCHOLOGICAL THERAPIES:
https://v3.datadictionary.nhs.uk/data_dictionary/data_field_notes/y/year_and_month_of_symptoms_onset_(improving_access_to_psychological_therapies)_dl.asp?shownav=1
This is what is shown in Together.

Why does Version 3+ show that it is linked to ACTIVITY DATE: https://datadictionary.nhs.uk/data_elements/year_and_month_first_started_antiretroviral_therapy.html

**Comment by jamesrwelch** [comment]
@AngelaFaulding Are you looking at the right elements?  The second link you've added is for Anti-retroviral Therapy.

**Comment by AngelaFaulding** [comment]
Sorry I will have a closer look. It was passed to me, so will investigate.
