### ISSUE TITLE
GUMCAD Sexually Transmitted Infection Surveillance System Data Set

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#161]
I think this is a question for James.

In the V3+ dictionary the GUMCAD Sexually Transmitted Infection Surveillance System Data Set looks like this. It has  groups in lower case, e.g. opposite sex partnership, male same sex partnership etc.
https://datadictionary.nhs.uk/data_sets/clinical_data_sets/gumcad_sexually_transmitted_infection_surveillance_system_data_set.html#dataset_gumcad_sexually_transmitted_infection_surveillance_system_data_set

This text has been taken from the group descriptions in V3
https://v3.datadictionary.nhs.uk/data_dictionary/messages/clinical_data_sets/data_sets/gumcad_sexually_transmitted_infection_surveillance_system_data_set_fr.asp?shownav=0

Can you make this look better, or do we need to fix this is Together?

**Comment by maxChappell** [comment]
Sub headings need Upper camel case - not urgent

To see the issue - search against the two linked pages for word "opposite"

**Comment by rajabr57** [comment]
5/5 Awaiting update from James

**Comment by AngelaFaulding** [comment]
James to fix in the June release?

**Comment by jamesrwelch** [comment]
I've applied a fix which I can see works for the GUMCAD dataset.  I believe this is the only one affected by this issue, but might be worth checking for others which do not match the same pattern as GUMCAD

**Comment by AngelaFaulding** [comment]
This has been fixed in the June release.
