### ISSUE TITLE
CDS V6-2 Type 200 - Admitted Patient Care

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#163]
See https://datadictionary.nhs.uk/data_sets/cds_v6-2/cds_v6-2_type_200_-_admitted_patient_care_-_unfinished_delivery_episode_cds.html
and
https://v3.datadictionary.nhs.uk/data_dictionary/messages/cds_v6-2/data_sets/cds_v6-2_type_200_-_admitted_patient_care_-_unfinished_delivery_episode_cds_fr.asp?shownav=1

In the second group on V3+ there is a broken link to CDS V6-2 Type 003 - Commissioning Data Set Message Header but this doesn't exist on V3

**Comment by AngelaFaulding** [comment]
The same has happened in CDS V6-2 Type 190 - Admitted Patient Care:
See https://datadictionary.nhs.uk/data_sets/cds_v6-2/cds_v6-2_type_190_-_admitted_patient_care_-_unfinished_general_episode_cds.html
and
https://v3.datadictionary.nhs.uk/data_dictionary/messages/cds_v6-2/data_sets/cds_v6-2_type_190_-_admitted_patient_care_-_unfinished_general_episode_cds_fr.asp?shownav=1

The issue is in: Data Group: CDS V6-2 Type 004 - CDS Message Trailer
Data Group: CDS V6-2 Type 004 - CDS Message Trailer
CDS V6-2 Type 004 - Commissioning Data Set Message Trailer

**Comment by AngelaFaulding** [comment]
And in



And in CDS V6-2 Type 140 - Admitted Patient Care, see https://datadictionary.nhs.uk/data_sets/cds_v6-2/cds_v6-2_type_140_-_admitted_patient_care_-_finished_delivery_episode_cds.html

Data Group: CDS V6-2 Type 002 - CDS Interchange Trailer
Data Group: CDS V6-2 Type 002 - CDS Interchange Trailer
CDS V6-2 Type 002 - Commissioning Data Set Interchange Trailer

**Comment by AngelaFaulding** [comment]
There is also a broken link in CDS V6-2 Type 110 - Elective Admission List to CDS V6-2 Type 005B - Commissioning Data Set Transaction Header Group - Bulk Update Protocol

**Comment by maxChappell** [comment]
Secondary uses service links (first data group has v3. prefix and html suffix) in first data group https://datadictionary.nhs.uk/data_sets/cds_v6-2/cds_v6-2_type_140_-_admitted_patient_care_-_finished_delivery_episode_cds.html

**Comment by AngelaFaulding** [comment]
The links now work but there are underscores in:
NHS_NUMBER_STATUS_INDICATOR_CODE
NHS_NUMBER_STATUS_INDICATOR_CODE_(BABY
Secondary_Uses_Service

**Comment by rajabr57** [comment]
5/5 Awaiting update from James

**Comment by AngelaFaulding** [comment]
Closed a duplicate of #173
