### ISSUE TITLE
CDS V6-2 Type 180 - Admitted Patient Care

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#164]
See https://datadictionary.nhs.uk/data_sets/cds_v6-2/cds_v6-2_type_180_-_admitted_patient_care_-_unfinished_birth_episode_cds.html
and 
https://v3.datadictionary.nhs.uk/data_dictionary/messages/cds_v6-2/data_sets/cds_v6-2_type_180_-_admitted_patient_care_-_unfinished_birth_episode_cds_fr.asp?shownav=1

On V3+ there is:
UNVERIFIED IDENTITY STRUCTURE
Must be used for all other values of the NHS_NUMBER_STATUS_INDICATOR_CODE_(MOTHER) NOT included in the above
and 
VERIFIED IDENTITY STRUCTURE
Must be used where the NHS_NUMBER_STATUS_INDICATOR_CODE_(MOTHER) National Code = 01 (Number present and verified)
This is a broken link, I thought it may because they in a header but others work OK, e.g. VERIFIED IDENTITY STRUCTURE
Must be used where the NHS NUMBER STATUS INDICATOR CODE

**Comment by maxChappell** [comment]
v3 prefix and html suffix

**Comment by AngelaFaulding** [comment]
The links now work but there are underscores in:
NHS_NUMBER_STATUS_INDICATOR_CODE
NHS_NUMBER_STATUS_INDICATOR_CODE_(MOTHER)
Secondary_Uses_Service

**Comment by maxChappell** [comment]
Search for an uinderscore to see issue

Connected to #173 and  #163

**Comment by rajabr57** [comment]
5/5  Awaiting update from James

**Comment by AngelaFaulding** [comment]
Closed as it is duplicate of #173
