### ISSUE TITLE
Re-name DM+D cannonical URL in FHIR items - to remove the "+"

### ISSUE THREAD

**Issue by maxChappell** [NHSDigital/DataDictionaryPublication#166]
Please replace the "+" with "plus"

**Comment by oughnic** [comment]
@maxChappell  @jamesrwelch 
Can we have a very clear set of all the rewrite rules (or transform on data migration and persist the rewritten value in Mauro) so that all consuming systems can be consistent.  Being selfish I'm thinking of template authors, but its universal.

**Comment by maxChappell** [comment]
This is the only change for FHIR cannonical url item names.

We have some rules for title case conversions and ACRONYM/Capitalisation rules that we push into mauro

**Comment by maxChappell** [comment]
Implemented as an undescore replacement.
