### ISSUE TITLE
Null Hyperlink labels in Hospital Episode Statistics

### ISSUE THREAD

**Issue by maxChappell** [NHSDigital/DataDictionaryPublication#167]
Null label found on knitted files and thus website. This ticket will be used to capture all found.

**Comment by maxChappell** [comment]
https://datadictionary.nhs.uk/nhs_business_definitions/hospital_episode_statistics.html

Cath and Angela assigned to check source in Together.

**Comment by maxChappell** [comment]
Also for row describing S10 https://datadictionary.nhs.uk/supporting_information/commissioning_data_set_business_rules.html

**Comment by AngelaFaulding** [comment]
I can see the issue on V3+ but this is OK on V3. I will relink the items and check the November release.

**Comment by oughnic** [comment]
> https://datadictionary.nhs.uk/nhs_business_definitions/hospital_episode_statistics.html
> 
> Cath and Angela assigned to check source in Together.

Not sure what class HES specialised.  I'm also sceptical that many people would describe HES as a database - more usually the data.  Perhaps a separate matter to review

**Comment by cach1** [comment]
I agree this item should be in Supporting Information not Business Definitions.  We can ask Dom Gair if he would like the definition updating

**Comment by AngelaFaulding** [comment]
I moved this to Supporting Definitions last week. I will check if the definition needs updating but I don't think it will be in time for the November release.

**Comment by AngelaFaulding** [comment]
The definition is taken from https://digital.nhs.uk/data-and-information/data-tools-and-services/data-services/hospital-episode-statistics.
It says "Hospital Episode Statistics (HES) is a database ....".
@cach1 Do we still need to check with Dom?

**Comment by cach1** [comment]
if the source is NHSD website them no, we don't - leave it please

**Comment by AngelaFaulding** [comment]
Thanks, will check the text is correct in the November release

**Comment by AngelaFaulding** [comment]
Hospital Episode Statistics still has a null and text missing.
See see https://datadictionary.nhs.uk/nhs_business_definitions/hospital_episode_statistics.html and https://v3.datadictionary.nhs.uk/web_site_content/supporting_definitions/hospital_episode_statistics.asp?shownav=1
Who can fix this?

**Comment by maxChappell** [comment]
We need to look at the supporting definitions/supporting information/business definitions splits....

The HES item resides in the supporting definitions folder - but has come through as a business definition. No clear pattern.

Correct hyperlink passed for the link that is showing as null (with v3 stripped out)

As of 01/12 - the HES item is the only captured and unresolved null hyperlink

**Comment by AngelaFaulding** [comment]
This still isn't correct.
V3 has:
Hospital Episode Statistics is a data warehouse containing details of all Admitted Patient Care, Outpatient Attendances and Accident and Emergency Attendances in England.

It includes private PATIENTS treated by the NHS, PATIENTS who were resident outside of England and care delivered by treatment centres (including those in the independent sector) funded by the NHS.

For further information on Hospital Episode Statistics, see the NHS Digital website at: Hospital Episode Statistics.


V3+ has Hospital Episode Statistics  is a data warehouse containing details of all Admitted Patient Care, Outpatient Attendances and Accident and Emergency Attendances in England. It includes private null, see the NHS Digital  website at: Hospital Episode Statistics.

**Comment by maxChappell** [comment]
Feb 21 - see https://modelcatalogue.cs.ox.ac.uk/datadictionary_february/supporting_information/hospital_episode_statistics.html

Null hyperlink now resolved
