### ISSUE TITLE
Remove/Migrate some old navigation content from Mauro publication

### ISSUE THREAD

**Issue by maxChappell** [NHSDigital/DataDictionaryPublication#168]
e.g. https://datadictionary.nhs.uk/supporting_information/supporting_information_introduction.html

**Comment by maxChappell** [comment]
Will need to ensure that old DD can still publish correctly - so most likely a pipeline change/mauro supression.

**Comment by AngelaFaulding** [comment]
This needs to stay for now but could be removed when we migrate to Mauro.
There are other menus that need looking at to see if they are needed when we author in Mauro.

**Comment by AngelaFaulding** [comment]
10/12/21 - This is similar to other tickets such as: Ordering of COSD Data Sets #63 and Ordering of CDS types landing page #130.
We should be able to do this in the data set folder when we have migrated to Mauro.
Ticket closed as it is covered elsewhere.
