### ISSUE TITLE
Set release month in publishing process automatically

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#169]
Set up the publishing process so the release month does not have to be updated manually.
Nicholas suggests this can be updated automatically from other information, e.g. release history date, date of publication.

**Comment by rajabr57** [comment]
5/5  Awaiting Nicholas to conmplete

**Comment by GSChandel** [comment]
It's done but needs confirming with @AngelaFaulding to close.

**Comment by AngelaFaulding** [comment]
@GSChandel I am not aware this has been done. I still have to do it manually. Can you please confirm why you say it is done?

**Comment by GSChandel** [comment]
Not done until it's automated.

**Comment by AngelaFaulding** [comment]
Confirmed with Nicholas that this isn't possible so will continue to be done manually. This is documented in the DMDS Work Instructions.
