### ISSUE TITLE
Underscores in url labels on web

### ISSUE THREAD

**Issue by cach1** [NHSDigital/DataDictionaryPublication#173]
On new dictionary there is a data group missing (and one incorrectly named) in CDS type 140, where it carries the Baby details at the bottom.  The Unverified Identity Structure is missing altogether, and the main group heading should be PATIENT IDENTITY (note - this may be because there is also a PATIENT IDENTITY group relating to the Mother at the top of this CDS type - if that's the case then fair enough - we are looking to potentially change this in CDS 6-3 anyway)

**Comment by cach1** [comment]
Hi @jamesrwelch is this one fixed for January release please?  We are currently working on CDS v6-2-3 and it being missing is causing confusion

**Comment by jamesrwelch** [comment]
@cach1 I've just had a look.  I can fix the table name in the code - the " 1".  But the missing table is due to an inconsistency in the HTML - the second "OR" is a row in the table, rather than a table in its own right.  It might be easier to fix the HTML than to re-write that bit of matching code.

**Comment by AngelaFaulding** [comment]
@jamesrwelch and @cach1 I have found where the "OR" is a row in the table, rather than a table.
I can fix that in the February release.
Is there anything else I need to fix?

**Comment by maxChappell** [comment]
Cause identified. Needs html change to fix. Should be fixed in Feb release.

**Comment by AngelaFaulding** [comment]
The groups are now OK in the data set.
However, there are three items on the page that have underscores:
NHS_NUMBER_STATUS_INDICATOR_CODE 
NHS_NUMBER_STATUS_INDICATOR_CODE_(BABY) 
Secondary_Uses_Service

The links work.
Can the underscores be removed?

**Comment by AngelaFaulding** [comment]
Other than Type 180, this is happening in other types (https://www.datadictionary.nhs.uk/data_sets/cds_v6-2/cds_v6-2_type_180_-_admitted_patient_care_-_unfinished_birth_episode_cds.html#dataset_cds_v6-2_type_180_-_admitted_patient_care_-_unfinished_birth_episode_cds), e.g.

https://www.datadictionary.nhs.uk/data_sets/cds_v6-2/cds_v6-2_type_020_-_outpatient_cds.html#dataset_cds_v6-2_type_020_-_outpatient_cds

https://www.datadictionary.nhs.uk/data_sets/cds_v6-2/cds_v6-2_type_021_-_future_outpatient_cds.html#dataset_cds_v6-2_type_021_-_future_outpatient_cds

https://www.datadictionary.nhs.uk/data_sets/cds_v6-2/cds_v6-2_type_030_-_elective_admission_list_-_end_of_period_census__standard__cds.html#dataset_cds_v6-2_type_030_-_elective_admission_list_-_end_of_period_census__standard__cds

https://www.datadictionary.nhs.uk/data_sets/cds_v6-2/cds_v6-2_type_040_-_elective_admission_list_-_end_of_period_census__old__cds.html#dataset_cds_v6-2_type_040_-_elective_admission_list_-_end_of_period_census__old__cds

https://www.datadictionary.nhs.uk/data_sets/cds_v6-2/cds_v6-2_type_050_-_elective_admission_list_-_end_of_period_census__new__cds.html#dataset_cds_v6-2_type_050_-_elective_admission_list_-_end_of_period_census__new__cds

https://www.datadictionary.nhs.uk/data_sets/cds_v6-2/cds_v6-2_type_060_-_elective_admission_list_-_event_during_period__add__cds.html#dataset_cds_v6-2_type_060_-_elective_admission_list_-_event_during_period__add__cds

https://www.datadictionary.nhs.uk/data_sets/cds_v6-2/cds_v6-2_type_070_-_elective_admission_list_-_event_during_period__remove__cds.html#dataset_cds_v6-2_type_070_-_elective_admission_list_-_event_during_period__remove__cds

https://www.datadictionary.nhs.uk/data_sets/cds_v6-2/cds_v6-2_type_070_-_elective_admission_list_-_event_during_period__remove__cds.html#dataset_cds_v6-2_type_070_-_elective_admission_list_-_event_during_period__remove__cds

https://www.datadictionary.nhs.uk/data_sets/cds_v6-2/cds_v6-2_type_080_-_elective_admission_list_-_event_during_period__offer__cds.html#dataset_cds_v6-2_type_080_-_elective_admission_list_-_event_during_period__offer__cds

https://www.datadictionary.nhs.uk/data_sets/cds_v6-2/cds_v6-2_type_090_-_elective_admission_list_-_event_during_period__available_or_unavailable__cds.html#dataset_cds_v6-2_type_090_-_elective_admission_list_-_event_during_period__available_or_unavailable__cds

**Comment by rajabr57** [comment]
5/5 Awaiting update from James

**Comment by AngelaFaulding** [comment]
James to look at to fix for the June release

**Comment by jamesrwelch** [comment]
Issue found and hopefully resolved for the June release

**Comment by AngelaFaulding** [comment]
Fixed in the June release. Issue closed.
