### ISSUE TITLE
Prepare for Term Server Go Live

### ISSUE THREAD

**Issue by GSChandel** [NHSDigital/DataDictionaryPublication#176]
07/01/21 - Maxine to talk to David about creating diagram with mapping between data dictionary and Mauro attributes

**Comment by maxChappell** [comment]
Full history run needs to be available for promotion to new Terminology production instance.

A) Full load to pick up any remaining bugs/gaps - w/c 14th Dec - DP Team
B) Quick test - send some existing items to UAT Term Server - w/c 14th Dec - DP Team or MC
C) Analyse content (Identify fixes needed and specify) - w/c 14th Dec and 21st Dec - MC
D) Implement fixes and re-run history for promotion to live - Early Jan 2021 - DP Team
E) Integration test (simple) with Mauro pipeline - Mid Jan 2021

**Comment by maxChappell** [comment]
A) Completed
C) Underway
E) Ongoing

**Comment by maxChappell** [comment]
B) LG working on this 11/01/21

**Comment by likin1** [comment]
forked the code to add the r4 libraries version 5.2.0

**Comment by likin1** [comment]
Hi I will be clearing down the term server and running the November release against r4 libraries

**Comment by AngelaFaulding** [comment]
21/12/21 - Maxine and Likin: could you please provide an update on this ticket? It said it was nearing completion on 11/5/21.

**Comment by maxChappell** [comment]
FHIR gen bugs are being worked on currently. STU3 to R4 transforms specified. Mechanisms for distinction between public, private and mauro test items agreed. Awaiting samples from James and Likin.

**Comment by likin1** [comment]
Maxine has finished the testing of stu3 to r4 and has handed me the results

**Comment by AngelaFaulding** [comment]
Meeting arranged for 2/2/22 with Maxine and Nigel

**Comment by PaulChapmanPM** [comment]
Jira ticket - [https://nhsd-jira.digital.nhs.uk/browse/DPNDA-273](url)

**Comment by GSChandel** [comment]
De-prioritised and to be reviewed post Branch Migration work.

**Comment by rajabr58** [comment]
Likin on leave until 19th April

**Comment by maxChappell** [comment]
Likelihood of some issues being cancelled due to decision to switch from semantic versioning to date based versioning only.

**Comment by AngelaFaulding** [comment]
Content was migrated.
