### ISSUE TITLE
Hyperlinks rendered but not active on Class/Attribute etc overview pages' narratives

### ISSUE THREAD

**Issue by maxChappell** [NHSDigital/DataDictionaryPublication#177]
See narrative at top of page for Class and Attributes etc - the hyperlinks are not active

e.g. https://datadictionary.nhs.uk/attributes_overview.html#attribute_overview

**Comment by oughnic** [comment]
This content is managed in Oxygen outside the Mauro capability.  A separate but related issue is that the examples are images, not DITA so need to switch to DITA content reuse.
For Nicholas and Angela to address

**Comment by AngelaFaulding** [comment]
Hyperlinks added to the overviews

**Comment by AngelaFaulding** [comment]
Hyperlinks added to all overviews in the January release.
