### ISSUE TITLE
Relationships in Classes not correct

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#179]
In version 3:
Each Patient may be the subject of one or more ACTIVITY
See https://v3.datadictionary.nhs.uk/data_dictionary/classes/p/patient_re.asp?shownav=1

In version 3+:
Each Patient must be the subject of one and only one ACTIVITY
See https://datadictionary.nhs.uk/classes/patient.html#class_patient.relationships

Why are these different?

Others on these pages are also different, e.g.
V3:    may be the donor of one or more TRANSPLANT ITEM
V3+: may be the donor of one and only one TRANSPLANT ITEM

I haven't checked any other items

**Comment by maxChappell** [comment]
Analysis underway to identify the pattern involved.

**Comment by rajabr57** [comment]
5/5 - waiting for James to investigate/fix

**Comment by AngelaFaulding** [comment]
James to look at fixing for the June release

**Comment by jamesrwelch** [comment]
Issue found and hopefully resolved for the June release

**Comment by AngelaFaulding** [comment]
The examples above are fixed so this issue is closed.
If anymore are found a new issue will be created.
