### ISSUE TITLE
Attribute summary incomplete

### ISSUE THREAD

**Issue by maxChappell** [NHSDigital/DataDictionaryPublication#180]
See https://datadictionary.nhs.uk/attributes/address_prefix.html compared to https://v3.datadictionary.nhs.uk/data_dictionary/attributes/a/add/address_prefix_de.asp?shownav=1

Looks like the summary extraction stopped at first full stop.

**Comment by maxChappell** [comment]
Could be fixed by removing the full stop after the eg OR may be fixed by oxford - but would be wary of that option. as it could mean that some of the other summaries get too large. Please advise.

**Comment by AngelaFaulding** [comment]
I'll fix this in the January release.

**Comment by oughnic** [comment]
Perhaps end the sentence before the example and have the example as a separate sentence

**Comment by AngelaFaulding** [comment]
That is what I have done.

**Comment by AngelaFaulding** [comment]
Looks OK in the January release.
