### ISSUE TITLE
Label the tickets to Project Names

### ISSUE THREAD

**Issue by luxi-liu97** [NHSDigital/DataDictionaryPublication#183]
DoD: All tickets are labelled correctly as per their delivering project names by the assigned staff.

Additional Task - move 3++ tickets to GitHub

**Comment by maxChappell** [comment]
I may have misunderstood the ask here, BUT if I haven't I don't think this is a valid ticket assignment. It is obvious on the 3+ board which team is working on a ticket (by which column it is placed in)

**Comment by luxi-liu97** [comment]
Hi Maxine - I'm currently just migrating over all the tasks from the planner and Gouri and I will refine them early next week after discussion
