### ISSUE TITLE
Run multiple (SQL) queries against FHIR database

### ISSUE THREAD

**Issue by luxi-liu97** [NHSDigital/DataDictionaryPublication#187]
05/11 - DB and AM getting familiar with the DB - assisted by LG
11/11 - Ongoing. AM has produced Physical Data Model of the database in pdf.
17/12 - Likin G has found a bug and it's being dealt with.

**Comment by maxChappell** [comment]
Concept clash queries and analysis done. Fix to be applied to reduce concept clashes when only differences are spaces and capitalisation.
Multi-level code lists are next up for analysis. Outputs of this work will inform DD documentation for users.
