### ISSUE TITLE
Related ISN History

### ISSUE THREAD

**Issue by luxi-liu97** [NHSDigital/DataDictionaryPublication#189]
- relates to 3+ and linking current change papers to Mauro published content.
More analysis and design decisions are needed.
Likin to analyse current mechanism for production via Together software and document
Likin to produce a file which could be ingested by Mauro
Meeting to be set up with James/Nicholas/Cath/Angela to explore options for ingestion
Consider requirement for merging historic and Mauro-authored change histories
Design decision on how to make output accessible via DD website

**Comment by AngelaFaulding** [comment]
10/12/21 - meeting planned for later today to discuss branch migration and Change History

**Comment by AngelaFaulding** [comment]
21/12/21 - work ongoing on how to get the old CRs into DD V3++.
James is going to produce a test to demonstrate how this can be done. Cath will also speak to Nicholas about this.

**Comment by AngelaFaulding** [comment]
Issue closed and replaced with #312 and #313.
