### ISSUE TITLE
Related DDCN/DSCN/ISN link required

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#19]

**Comment by maxChappell** [comment]
Continue local publish - to retain papers etc for DD helpdesk.

Omit for 3+

Address early in the 3+ to 3++ work

**Comment by maxChappell** [comment]
Above from workshop

**Comment by rajabr57** [comment]
23/6 - more detail required in this ticket.  Bob not aware of what the ask is from his team.

**Comment by AngelaFaulding** [comment]
10/12/21 - meeting planned for later today to discuss branch migration and Change History

**Comment by AngelaFaulding** [comment]
21/12/21 - work ongoing on how to get the old CRs into DD V3++.
James is going to produce a test to demonstrate how this can be done. Cath will also speak to Nicholas about this.

**Comment by AngelaFaulding** [comment]
Issue closed and replaced with #312 and #313.
