### ISSUE TITLE
CR DATA in Archive Data

### ISSUE THREAD

**Issue by luxi-liu97** [NHSDigital/DataDictionaryPublication#190]
https://v3.datadictionary.nhs.uk/archive/DD%20Release%20August%202020/change_packages/cr1784/cr1784.asp#ADDRESSAttribute

Correct URL is https://v3.datadictionary.nhs.uk/change_packages/cr1784/cr1784.asp#ADDRESSAttribute

11/11/20 - LG Initial investigation complete. MC assigned to help the migration effort.

26 - awaiting confirmation from LG and MC.

**Comment by rajabr57** [comment]
5/5  Get update from Likin

**Comment by rajabr57** [comment]
11/5 - same as #191

**Comment by AngelaFaulding** [comment]
10/12/21 - meeting planned for later today to discuss branch migration and Change History

**Comment by AngelaFaulding** [comment]
Maxine and Likin - this appears to just be an archive issue. Has this been fixed? If so, can the issue be closed?

**Comment by AngelaFaulding** [comment]
@maxChappell and @likin1 - is this ticket still required?

**Comment by AngelaFaulding** [comment]
Issue no longer required, superseded by #313.
