### ISSUE TITLE
CR Data from Bazar Repos.

### ISSUE THREAD

**Issue by luxi-liu97** [NHSDigital/DataDictionaryPublication#191]
on hold temporarily for october release. 13/10/20
14/10 - Review next week
27/10 - on hold until Cath speaks with James W
12/11 - see ticket 7 for agreed actions

LG to extract CR Data to AF/CC
On hold until Nov'20 release is done.
GS - Requires discussion with Maxine, Likin and Angela

**Comment by rajabr57** [comment]
11/5 - LG busy with spec for FIHR generation.  Will do this later.

**Comment by AngelaFaulding** [comment]
10/12/21 - meeting planned for later today to discuss branch migration and Change History

**Comment by AngelaFaulding** [comment]
21/12/21 - work ongoing on how to get the old CRs into DD V3++.
James is going to produce a test to demonstrate how this can be done. Cath will also speak to Nicholas about this.
