### ISSUE TITLE
Rule representation discovery (DMN)

### ISSUE THREAD

**Issue by luxi-liu97** [NHSDigital/DataDictionaryPublication#192]
DoD: 

Initial discovery re DMN
05/11 - within talend - derivations and rules work continues - derivations going well. Rules not so good - need to install Business Centre. Ali M to help with set up.
11/11 - 2nd show and tell delivered.
12/11 - Still having some issues with Business Central - liaison with Ali continuing.
26/11 - Business Central is resolved.
08/12 - NHS Number checking is now working

Tim Gentry has asked for a demo - TBA imminently - suggested NHS Number validation.
GS - Require adding the DoD in the comments. Check with YA and MC. When is the NHS number Demo.
To look at how to make it fully portable
NO - to update Tim Gentry on NHS Number

**Comment by oughnic** [comment]
Repot prepared following discovery
