### ISSUE TITLE
Mitigate Single point failures (Risk)

### ISSUE THREAD

**Issue by luxi-liu97** [NHSDigital/DataDictionaryPublication#194]
Identify the single point of failures within the projects and put a mitigation plan in place.
Identify alternate resources to assume the required roles/jobs. Granting access to required tools/environments and areas to work on.
Agree and approval of the mitigation process and resources.

1. Nicholas O is the only person who can publish the new version. (24th Sept'20 - Angela has learned about publishing process but have PC memory issue and having issues with GitHub publishing. It's being currently being looked at). (29/10 - Now Angela can do publication as well).
2. James W is due to go on Paternity Leave (likely by and of Sept)- James is providing copy of the code with NHSD (Likin) so the code will exist at two places. Any changes after this happens, James updates will be run through NHSD and if agreed and accepted will be updated to live version.
3. Steve H has shared his code. - mitigated.
4. Likin G - time and priorities. Summary level document reg. Pipeline will help reduce this a bit.
File size difference reconciled 05/11
5. LG to enable Ali, David and Kun to run the FHIR generation (populating OntoServer).

JW is intended to package his code enabling NHSD to run it - needs formal process in place
SH is already shared his code. Need to find and agree who can run it in NHSD.
LG - to write the instructions for the Kun Cheng to pick up the work 
LG - started to take Kun C through the work and progressing well.
Kun to shadow Likin for next release of DD

**Comment by maxChappell** [comment]
14/01/21 - Good progress being made, Test of end-to-end ingestion pipeline being run by NHS D for Jan 21 release
