### ISSUE TITLE
Work Instruction update for Dictionary Team (3+)

### ISSUE THREAD

**Issue by luxi-liu97** [NHSDigital/DataDictionaryPublication#195]
DoD - Updating the work instructions for whole processes for V3+

Aiming for Oxford code hosted on NHSD infrastructure for 3+ Go-Live.

Work in progress considering 3++

**Comment by AngelaFaulding** [comment]
Work on 3+ Work Instructions ongoing

**Comment by maxChappell** [comment]
Completed and handed over to DMDS as BAU for 3+
