### ISSUE TITLE
Requirements for terminology server code value properties per data set

### ISSUE THREAD

**Issue by luxi-liu97** [NHSDigital/DataDictionaryPublication#199]
It's 3++ property.
This is potentially to remove or address specific usage according the data set of a given code rather than relying on notes on the webpage.
08/12 - Meeting with James W, Nicholas O, Maxine C and GSC on 07/12 to go through this and agreed to progress this with a further discussion.

Discussions underway re - Data Migration and Editing

**Comment by oughnic** [comment]
No longer thought to be a user need
