### ISSUE TITLE
Retired Items in 'Where Used'

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#20]
Where used is showing retired items, it doesn’t in DDV3, could be confusing, e.g. ACTIVITY has ACCIDENT AND EMERGENCY ATTENDANCE CDS TYPE (Retired)

**Comment by AngelaFaulding** [comment]
I have checked a sample of items and there are no retired items in Where Used. I will move to Closed when I am able to.
