### ISSUE TITLE
Generating individual output from the template API

### ISSUE THREAD

**Issue by luxi-liu97** [NHSDigital/DataDictionaryPublication#202]
OCC have provided a capability to receive an http post with a template using Freemarker syntax for Models, classes in a model and terminologies in a model.  This task is to use that API to generate sample text documents (DITA, GraphViz DOT) for one ore more models in the Mauro repository.
There are two aspects
- write code to iterate through models and classes and apply templates
- write templates to generate a publication
13/10/20 - issue with code that James is exploring

possible duplication
Work needed for terminologies - with NO

**Comment by rajabr57** [comment]
6/5 - waiting on NO - not urgent

**Comment by AngelaFaulding** [comment]
Nicholas says this can be closed as it is duplication.
