### ISSUE TITLE
Management of non-Data Dictionary master metadata: Data Dictionary for Care (SNOMED CT refsets)

### ISSUE THREAD

**Issue by luxi-liu97** [NHSDigital/DataDictionaryPublication#203]
04/08/2020 - Moved to blocked sure resource availability.

------
Epic: https://nhsd-jira.digital.nhs.uk/browse/DPNDA-165
Discovery : 

Initial Plan:
DD4C Current situation Ticket #1

Describe what DD4C is
Describe the current technologies and platforms it uses
Describe the current costs
Describe future developments (none due to cost?)
Describe the Technical Debt issues

Remediation Ticket #2

Options

1) Do Nothing - unacceptable to EAB - may result in service closure. Assumption this isn't what the customers wants but assumption needs to be tested.
2) Uplift/refresh - Ticket #3 Describe what needs to be done, how long it will take and any risk/issues. Technical debt will continue to resurface. Run and maintenance costs will continue along the current trajectory
3) Incorporate DD4C into Mauro
Ticket #4 Describe Mauro in terms the DD4C customer will understand and how current DD4C functionality will be accommodated to achieve their buy in
Will need to understand platform and maintenance costs and how or if they will be attributed to customers
Will need to understand dependencies with DD and other systems and Workflow (Cath and Michael?)
Will need to bring in as wider group of Data Products people as possible to develop and share Mauro skillset
Will need to understand Migration issues and develop a migration plan Ticket #5
Ticket #6 Build a light demonstration?
Ticket #7 explore and describe future opportunities/benefits for DD4C

Present the above to Nicholas and DD4C owners/users for final decision/funding

Ticket 8 - Implement the decision

**Comment by rajabr57** [comment]
12/5 - still blocked, awaiting stable instance of Mauro.  Team also do not have capacity.

**Comment by rajabr57** [comment]
23/6 - Update from BC:  Meeting required between Ali and Nicholas to review the design for data migration of DD4C in NHSD Mauro design

**Comment by GSChandel** [comment]
Meeting b/w Ali, Nicholas and Paul happened. Now Ali (@BobCox-afk) needs to review and arrange review sessions with Cath and Angela #279

**Comment by AngelaFaulding** [comment]
Closed, see https://github.com/NHSDigital/DataDictionaryPublication/issues/279
