### ISSUE TITLE
Classes: No relationships and therefore no Key relationships

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#21]

**Comment by AngelaFaulding** [comment]
Maxine - we need this prioritising for 3+

**Comment by AngelaFaulding** [comment]
There are some strange entries on Class Relationships, e.g.
https://modelcatalogue.cs.ox.ac.uk/datadictionary/classes/w/ward.html#class_ward.relationships
https://modelcatalogue.cs.ox.ac.uk/datadictionary/classes/o/organisation.html#class_organisation.relationships

Are you aware of these?

**Comment by jamesrwelch** [comment]
Ha!  Some debug information coming through - this is actually the `relationSupplierExclusivity` coming through in places.  I'll remove them

**Comment by AngelaFaulding** [comment]
Now has relationships and shows Key relationships. Issue closed.
