### ISSUE TITLE
Description editing impact assessment

### ISSUE THREAD

**Issue by luxi-liu97** [NHSDigital/DataDictionaryPublication#216]
We need to have a comprehensive view of the impact of changing from editing descriptions in HTML to using Markdown
Output - 
an approach to handling this in 3++ implementation
Report of expressiveness lost (if any)
Data Migration
Editing
DITA generation (or Markdown export?)
Publication

**Comment by maxChappell** [comment]
Think embedded WYSIWYG html editor has been incorporated as part of editing epic?

**Comment by GSChandel** [comment]
Burned - as new editor is using HTML.
