### ISSUE TITLE
Not showing retired date - null overviews

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#22]
ACCIDENT AND EMERGENCY ATTENDANCE CDS TYPE (Retired), it doesn’t show the retired date as other items

**Comment by maxChappell** [comment]
Hi Angela - have a look at this page -> https://www.datadictionary.nhs.uk/retired/data_dictionary/messages/commissioning_data_set_v5/accident_and_emergency_attendance_cds_type_fr.asp?shownav=1

**Comment by AngelaFaulding** [comment]
I will fix this the link to the overview page in Together but why is the retired date not shown on the item?

**Comment by maxChappell** [comment]
It looks like only the text from the introduction is being used. Cannot see any text matching it's overview content (which contains the date).

**Comment by AngelaFaulding** [comment]
I will fix this in the August release.

**Comment by AngelaFaulding** [comment]
Still not displaying correctly in the beta version, will check the September release.

**Comment by AngelaFaulding** [comment]
See https://www.datadictionary.nhs.uk/data_sets/retired/commissioning_data_set_v5/accident_and_emergency_attendance_cds_type.html, it still isn't showing the retired date

**Comment by AngelaFaulding** [comment]
Not sure who needs to fix this

**Comment by maxChappell** [comment]
Description field is showing as null. Text is available in the expanded xml file.

**Comment by maxChappell** [comment]
See also 
https://datadictionary.nhs.uk/data_elements/retired/observation_date__hba1c_level_.html
https://datadictionary.nhs.uk/data_elements/retired/observation_date__serum_ferritin_concentration_.html

**Comment by maxChappell** [comment]
https://datadictionary.nhs.uk/data_sets/retired/cds_v6_old_layout/cds_v6_type_003.html
https://datadictionary.nhs.uk/data_sets/retired/central_returns_data_sets/nhs_funded_nursing_care_annual_central_return_data_set.html
https://datadictionary.nhs.uk/data_sets/retired/cds_v6_old_layout/cds_v6_type_005b.html
https://datadictionary.nhs.uk/data_sets/retired/commissioning_data_set_v5/elective_admission_list_cds_type_040_-_end_of_period_census__old_.html
https://datadictionary.nhs.uk/data_sets/retired/cds_v6_old_layout/cds_v6_type_021.html
https://datadictionary.nhs.uk/data_sets/retired/cds_v6_old_layout/cds_v6_type_180.html
https://datadictionary.nhs.uk/data_sets/retired/clinical_data_sets/mothers_sexual_health_and_infectious_diseases_data_set.html
https://datadictionary.nhs.uk/data_sets/retired/cds_v6_old_layout/cds_v6_type_170.html
https://datadictionary.nhs.uk/data_sets/retired/commissioning_data_set_v5/elective_admission_list_cds_type_090_-_event_during_period__available_unavailable_.html

**Comment by maxChappell** [comment]
https://datadictionary.nhs.uk/data_sets/retired/clinical_data_sets/mental_health_and_learning_disabilities_data_set.html

**Comment by AngelaFaulding** [comment]
I have fixed these for the October release.

**Comment by maxChappell** [comment]
See https://datadictionary.nhs.uk/data_sets/retired/cds_v6-2/cds_v6-2_type_010_-_accident_and_emergency_cds.html - october 20 release

**Comment by AngelaFaulding** [comment]
I am not sure what is happening with these items.
See https://v3.datadictionary.nhs.uk/retired/data_dictionary/messages/cds_v6-2/cds_v6-2_type_010_-_accident_and_emergency_cds_fr.asp?shownav=1. This has the retied text.

I removed the explanatory pages for the October release so am not sure what the issue is with these.

**Comment by maxChappell** [comment]
https://datadictionary.nhs.uk/data_sets/retired/commissioning_data_set_v5/ward_attendance_cds_type.html?hl=null

A website search for null gives a pretty long list.

**Comment by AngelaFaulding** [comment]
I have done some investigating and found that 172 items (including WARD ATTENDANCE CDS TYPE) has:

Access to this version can be obtained by emailing &lt;a href=&quot;mailto:information.standards@nhs.net&quot;&gt;information.standards@nhs.net&lt;/a&gt; with &amp;lsquo;NHS Data Model and Dictionary - Archive Request&amp;rsquo; in the email Subject line

And 4032 files has:

Access to this version can be obtained by emailing &lt;a href=&quot;mailto:information.standards@nhs.net&quot;&gt;information.standards@nhs.net&lt;/a&gt; with &quot;NHS Data Model and Dictionary - Archive Request&quot; in the email subject line

Will that make a difference to what is displayed?

**Comment by arkie-boy** [comment]
That somewhat depends on how the browser maps &lsquo; and &rsquo;.  They are intended to map to the versions of the quote symbols that are actually at angles rather than the straight versions your keyboard carries.  What you'll actually see, like I said, may somewhat depend on the browser.

Personally I would marginally prefer the regular " and ' marks that don't need to be identified with entities.

**Comment by arkie-boy** [comment]
Interestingly I typed **& lsquo ;** and both were automatically interpreted as single bottom left to top right quotes in my browser.

**Comment by jamesrwelch** [comment]
Data sets were all picking up their 'overview' from the corresponding explanatory page.  For retired datasets that did not have explanatory pages, no overview was found, hence the 'null'.  I've fixed so that where no explanatory page is found, the 'definition' text is used.  This fixes the original problem reported, but doesn't yet fix the issue with the strange quote marks.

**Comment by AngelaFaulding** [comment]
Do I need to remove the strange quote marks?

**Comment by jamesrwelch** [comment]
@AngelaFaulding You could, but if there are many occurrences, it may be quicker at this point for me to replace them at this point in the pipeline

**Comment by AngelaFaulding** [comment]
It is a two minute job so I will do it and we can check if it works in the December release

**Comment by AngelaFaulding** [comment]
All items listed on this page have the retired date in the January release.
