### ISSUE TITLE
Management of non-Data Dictionary master metadata: SNOMED CT releases

### ISSUE THREAD

**Issue by luxi-liu97** [NHSDigital/DataDictionaryPublication#221]
3++ requirements related to non-DD authored vocabulary .

**Comment by rajabr57** [comment]
11/5 - cant do anything with this until we have our own instance of Mauro

**Comment by GSChandel** [comment]
21/06/2021 - Not required for 3++

**Comment by GSChandel** [comment]
Closed as not required for 3++
