### ISSUE TITLE
Functionality for content authoring: Branching

### ISSUE THREAD

**Issue by luxi-liu97** [NHSDigital/DataDictionaryPublication#224]
SoW 901 - MS04

**Comment by maxChappell** [comment]
OCC deliverable currently in UAT

**Comment by rajabr57** [comment]
5/5 still waiting to be tested.  NHSD-test Mauro instance needs to have the Jodit plug-in before UAT can take place.

**Comment by GSChandel** [comment]
This task is already picked in [#198](https://github.com/NHSDigital/DataDictionaryPublication/issues/198).

**Comment by AngelaFaulding** [comment]
Already burned in 2021 but not closed.
