### ISSUE TITLE
Production environment of Mauro on NHS Digital Azure/AWS instance (not Oxford)

### ISSUE THREAD

**Issue by luxi-liu97** [NHSDigital/DataDictionaryPublication#225]
Check with Jas. Jas team may be delivering the 'setting up the environment'
Damian M or his team member needs to be on the assigned list
Bob and his team can/may move this forward
Solution Assurance Sign-Off
Cath comments on 2nd  July'20

**Comment by maxChappell** [comment]
Suspect this is a duplicate

**Comment by maxChappell** [comment]
Closed as duplicate
