### ISSUE TITLE
3++ Mauro Editing (stories attached)

### ISSUE THREAD

**Issue by GSChandel** [NHSDigital/DataDictionaryPublication#235]
Data Dictionary team require the capability to carry out changes (Create, Update, Delete) to the data content in Mauro.

A change management process is required that provides:
 
-Role based access to control “who can do what” 
-Merging/Branching functionality 
-Editing existing and creating new items 
-Retired and Available From functionality 
-Auditability 
-Versioning 
-Ability to show what published change looks like on Web
 
Technical: This functionality is required within Mauro. It will replace the current solution that is constructed using multiple systems. (Note the data is published to the Web via “3++ Publishing” below) 

Functional: The time taken to carry out changes must ideally be less than the existing solution. Would be great if the process is more straightforward (for e.g. new Data Dictionary team members) compared to the current (V3) process.

**Comment by GSChandel** [comment]
[Stories-Editing v1.1.docx](https://github.com/NHSDigital/DataDictionaryPublication/files/5843363/Stories-Editing.v1.1.docx)

**Comment by rajabr57** [comment]
21/05 - Gauri asked for this to be moved to For Discussion as Angela and team were working on this but need to know the current updated plan

**Comment by AngelaFaulding** [comment]
@GSChandel : do we need this ticket? You created it but it isn't assigned to anyone and doesn't have any labels? It is covered by other tickets.

**Comment by AngelaFaulding** [comment]
Issue closed as instructions are covered in https://github.com/NHSDigital/DataDictionaryPublication/issues/233
