### ISSUE TITLE
3++ Publishing (To Web and Onto server) (stories attached)

### ISSUE THREAD

**Issue by GSChandel** [NHSDigital/DataDictionaryPublication#236]
Capability to publish the Data Dictionary to the Web is required. Amendments to the current process developed for 3+ are required to make publishing ‘single click’ for 3++. 

The publishing process takes data from the Mauro Data Dictionary, blends with additional textural information and publishes to the Web.

Publishing to a Pre-Live and Live website required.

Publishing to also ‘push’ appropriate data to the Onto Server.

**Comment by GSChandel** [comment]
[Stories - Rel and Pubcn Proc v1.1.docx](https://github.com/NHSDigital/DataDictionaryPublication/files/5843359/Stories.-.Rel.and.Pubcn.Proc.v1.1.docx)

**Comment by rajabr57** [comment]
11/5 - need to discuss with wider team

**Comment by AngelaFaulding** [comment]
10/12/21 - Kun is working on the process for publishing the DD, archives and previews via a Data Dictionary build manager.
The DD and DDCNs have now been moved to the Cloud.
Also discussing with Kun the process of uploading the DDCNs and demonstration files to the Cloud.

Pushing appropriate data to the Onto Server is a different issue and will be done via the orchestration tool.

Should these be split out into separate tickets?

**Comment by AngelaFaulding** [comment]
21/12/21 - @GSChandel : can this ticket be closed as you updated https://github.com/NHSDigital/DataDictionaryPublication/issues/243 and https://github.com/NHSDigital/DataDictionaryPublication/issues/305 on 20/12/21

**Comment by AngelaFaulding** [comment]
22/12/21 - issue closed so this is covered in other tickets.
