### ISSUE TITLE
3++ Infrastructure Requirements (NHS D - hosted instances)

### ISSUE THREAD

**Issue by GSChandel** [NHSDigital/DataDictionaryPublication#238]
NHSD Infrastructure is required to run NHSD hosted Mauro instances.

Expect 4 infrastructures required as follows:
- UAT 
- Pre-Production 
- Production – Data Dictionary 
- Production – DD4C 

Infrastructure to include secure access for authorised internal and external customers.

**Comment by maxChappell** [comment]
Expect to need (MVP)

dev
uat
data migration
DD/DD4C authoring
live (NHS D (incl DD))

+ other instances for external (funded) e.g NHS X

Requirements need elaborating further

**Comment by AngelaFaulding** [comment]
NHS Digital hosted instances required for:

- UAT: March 2021 onwards
- Public (NHS D including DD and DD4C): March 2021 onwards
- DD instance: solely for DD team (required once DMDS preparing for V3++ migration)
- Dev: at the point where we are developing our own plug ins
- HDRUK dedicated instance: for them to do their work on (needs confirmation of funding)

This is as requested by Maxine and Nicholas.

**Comment by rajabr57** [comment]
21/5/ - update from BC:  basically I want the requirement expressed as services rather than servers for this and that. Ultimately that is what we will have to provide and might not require a server at all for parts of it.

**Comment by rajabr57** [comment]
23/6 - update from BC:  Environments, approach and configuration established. Staff trained in their use. Awaiting Mauro.

**Comment by AngelaFaulding** [comment]
22/12/21 - update from BC. Requirements demonstrated so issue closed.
