### ISSUE TITLE
Attribute types inconsistent

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#24]
Attribute types inconsistent.

E.g. Activity Class has:
- ACTIVITY IDENTIFIER Enumeration - ACTIVITY IDENTIFIER (Attribute)
- PDS PATIENT CARE PROVISION TYPE Enumeration - PDS PATIENT CARE PROVISION TYPE (Attribute) 
- CONTRACT MONITORING ACTUAL ACTIVITY Default String 

ACTIVITY DURATION Default StringCare Activity has:
- FEMALE GENITAL MUTILATION IDENTIFICATION METHOD CODE Enumeration - FEMALE GENITAL MUTILATION IDENTIFICATION METHOD CODE (Attribute) 
- RESTRICTIVE INTERVENTION POST-INCIDENT REVIEW HELD INDICATOR Enumeration - RESTRICTIVE INTERVENTION POST-INCIDENT REVIEW HELD INDICATOR (Attribute) 

Service has:
- SERVICE TYPE Enumeration - SERVICE TYPE (Attribute) 
- SERVICE IDENTIFIER Default String 
- Clarification would be helpful
- How does a user know what the Key is?

**Comment by maxChappell** [comment]
Need to understand what is needed and by whom...

**Comment by maxChappell** [comment]
Workshop - remove column for 3+

We will revisit between 3+ and 3++

**Comment by maxChappell** [comment]
May need priority increasing

**Comment by AngelaFaulding** [comment]
The Enumeration tags have been removed, issue closed.
