### ISSUE TITLE
3+ to 3++ Migration (ADDED TO CORE FUNCTIONALITY DOC)

### ISSUE THREAD

**Issue by GSChandel** [NHSDigital/DataDictionaryPublication#245]
Migration from 3+ to 3++ will be required. Potentially the underlying Mauro database will be slightly changed to support e.g. Branching and Merging and therefore a migration of data from 3+ could be required.

Potentially decommissioning and or archiving needs will require consideration as with any migration project.

**Comment by maxChappell** [comment]
There is a seperate board for the activities required to decommission together and migrate to mauro (Together Migration) - so closing this ticket as not needed.
