### ISSUE TITLE
EPISODE NUMBER default codes missing

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#248]
See https://v3.datadictionary.nhs.uk/data_dictionary/data_field_notes/e/ep/episode_number_de.asp?shownav=1
Episode Number has default codes:
98 - Not applicable
99 - EPISODE NUMBER not known

Version 3+ does not have any default codes, see https://datadictionary.nhs.uk/data_elements/episode_number.html

Who needs to fix this?

**Comment by maxChappell** [comment]
Default codes present in valueset expand file - so think this is one for James.
Have checked that other default codes are on website - this absence for this item appears to be an anomaly

**Comment by AngelaFaulding** [comment]
New Dita provided by James:
Default Codes on the test version are now:
EPISODE NUMBER - 98 and 99
Will publish on the 2nd and then close the issue.

**Comment by AngelaFaulding** [comment]
DD republished and the default codes are correct.
