### ISSUE TITLE
Default Codes Missing off Data Elements with no National Codes

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#249]
There is an issue with Data Elements that are linked to attributes that have no National Codes. The default codes are not displaying on the Data Element.
e.g.
https://datadictionary.nhs.uk/data_elements/age_at_activity_date__contract_monitoring_.html
and
https://v3.datadictionary.nhs.uk/data_dictionary/data_field_notes/a/ag/age_at_activity_date_(contract_monitoring)_de.asp?shownav=1

https://datadictionary.nhs.uk/data_elements/age_at_attendance_date.html
and
https://v3.datadictionary.nhs.uk/data_dictionary/data_field_notes/a/ag/age_at_attendance_date_de.asp?shownav=1

James is aware of this and is looking into it.

**Comment by oughnic** [comment]
Perhaps we should describe the default codes as default values :-)

**Comment by AngelaFaulding** [comment]
Do you mean on every item?
You or James will have to change the section headings
I would have to change the overviews again and some of the help pages I am working on.
Can we have a very quick decision on this please?
I'd rather it stayed as default codes.

**Comment by oughnic** [comment]
Where the item is a date or a number (not a code) the label is misleading. The four examples aren't codes - two ages (integer number of years) and two dates.

**Comment by AngelaFaulding** [comment]
@oughnic  are you saying we will have a Default Codes section for Data Elements with National Codes and a Default Values section for Data Elements without National Codes.
When will this be done?

**Comment by cach1** [comment]
@oughnic  - despite being numeric in their format, the default codes on the 'age' items are actually codes and don't represent a default 'age' of 999, for example.  We have fixed a lot of these in terms of the specified format/length (from n3 to max an3 for example) in our various patches upcoming for CDS 6-3. Please don't suggest a different label type for them - it will break all manner of things, not least Angelas help pages stuff.  @jamesrwelch please can you ignore @oughnic :-)

**Comment by oughnic** [comment]
@cach1 Their really neither codes nor values - they are null flavours.  We need to work out how we handle then properly.

**Comment by cach1** [comment]
*they're
yep, I agree, but we are where we are

**Comment by AngelaFaulding** [comment]
Also see https://github.com/NHSDigital/DataDictionaryPublication/issues/254, which has been reported as a help desk query.

**Comment by AngelaFaulding** [comment]
New Dita provided by James:
Default Codes on the test version are now:
AGE AT ACTIVITY DATE (CONTRACT MONITORING) - 999
AGE AT ATTENDANCE DATE - 999

Will publish on the 2nd and then close the issue.

**Comment by AngelaFaulding** [comment]
DD republished and the default codes are correct.
