### ISSUE TITLE
Classes: Meta

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#25]
Classes: m has:
- MENTAL HEALTH ACT LEGAL STATUS CLASSIFICATION 
- Classes: meta 
- MIDWIFE
- Classes: Meta still there
- The meta items should be removed: for discussion, should we retire them from Together

**Comment by oughnic** [comment]
I'd rather keep them separate so we can swap the meta model out for ContSys in V4.  In theory (ahem) the main classes should link back to the meta classes.
