### ISSUE TITLE
Issue with field in PLICS Ambulance data set

### ISSUE THREAD

**Issue by cach1** [NHSDigital/DataDictionaryPublication#252]
A field in the in the PLICS ambulance data set (last field in the CARE ACTIVITY DETAILS data group) should have a choice of 3 data elements in it - ORGANISATION IDENTIFIER (RECEIVING) or ORGANISATION SITE IDENTIFIER (RECEIVING) or GENERAL MEDICAL PRACTICE CODE (RECEIVING).  Only the first one is showing

**Comment by AngelaFaulding** [comment]
@jamesrwelch:  this looks like one for you. 
It is OK in V3, see https://v3.datadictionary.nhs.uk/data_dictionary/messages/supporting_data_sets/data_sets/plics_data_set/patient_level_information_costing_system_data_set_-_ambulance_fr.asp?shownav=1
It should have:
ORGANISATION IDENTIFIER (RECEIVING) 
or
ORGANISATION SITE IDENTIFIER (RECEIVING) 
or
GENERAL MEDICAL PRACTICE CODE (RECEIVING)
But V3+ only has:
ORGANISATION IDENTIFIER (RECEIVING

**Comment by AngelaFaulding** [comment]
Test February release run:
The Care Activity Details group now has:
R
ORGANISATION IDENTIFIER (RECEIVING)
Or
ORGANISATION SITE IDENTIFIER (RECEIVING)
Or
GENERAL MEDICAL PRACTICE CODE (RECEIVING)

**Comment by AngelaFaulding** [comment]
Release has the correct details
