### ISSUE TITLE
Missing Default Codes on Gestation Length Data Elements

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#254]
We have received a help desk query raising an issue. I presume this is because there are no National Codes on the attribute. 

The following data elements in Version 3+ have the default code 99 missing:
GESTATION LENGTH (ASSESSMENT) - https://datadictionary.nhs.uk/data_elements/gestation_length__assessment_.html
GESTATION LENGTH (AT DELIVERY) - https://datadictionary.nhs.uk/data_elements/gestation_length__at_delivery_.html
GESTATION LENGTH (LABOUR ONSET) - https://datadictionary.nhs.uk/data_elements/gestation_length__labour_onset_.html

There are in Version 3:
GESTATION LENGTH (ASSESSMENT) - https://v3.datadictionary.nhs.uk/data_dictionary/data_field_notes/g/gestation_length_(assessment)_de.asp?shownav=1
GESTATION LENGTH (AT DELIVERY) - https://v3.datadictionary.nhs.uk/data_dictionary/data_field_notes/g/gestation_length_(at_delivery)_de.asp?shownav=1
GESTATION LENGTH (LABOUR ONSET) - https://v3.datadictionary.nhs.uk/data_dictionary/data_field_notes/g/gestation_length_(labour_onset)_de.asp?shownav=1

**Comment by AngelaFaulding** [comment]
The default code wasn't in the January release, e.g. https://v3.datadictionary.nhs.uk/archive/DD%20Release%20January%202021/data_elements/gestation_length__labour_onset_.html

**Comment by AngelaFaulding** [comment]
This appears to be the same as https://github.com/NHSDigital/DataDictionaryPublication/issues/249

**Comment by maxChappell** [comment]
This issue has only been present in the Jan and Feb releases - representation in knitted files and valueset xml file is unchanged

**Comment by AngelaFaulding** [comment]
New Dita provided by James:
Default Codes on the test version are now:
GESTATION LENGTH (ASSESSMENT) - 99
GESTATION LENGTH (AT DELIVERY) - 99
GESTATION LENGTH (LABOUR ONSET) - 99

Will publish on the 2nd and then close the issue.

**Comment by AngelaFaulding** [comment]
DD republished and the default codes are correct.
