### ISSUE TITLE
OVERSEAS VISITOR CHARGING CATEGORY Default Codes

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#257]
Default codes for the two items below are not displaying correctly:
OVERSEAS VISITOR CHARGING CATEGORY 
- https://www.datadictionary.nhs.uk/data_elements/overseas_visitor_charging_category.html
- https://v3.datadictionary.nhs.uk/data_dictionary/data_field_notes/o/ov/overseas_visitor_charging_category_de.asp?shownav=1

OVERSEAS VISITOR CHARGING CATEGORY AT CDS ACTIVITY DATE 
- https://www.datadictionary.nhs.uk/data_elements/overseas_visitor_charging_category_at_cds_activity_date.html
- https://v3.datadictionary.nhs.uk/data_dictionary/data_field_notes/o/ov/overseas_visitor_charging_category_at_cds_activity_date_de.asp?shownav=1

OVERSEAS VISITOR CHARGING CATEGORY had extra html. I have tried to fix them and will check in the next release.

@maxChappell are these OK on the server?

**Comment by maxChappell** [comment]
This appears to be a double issue.

1) Currently concept 9 is a default code clash - so these should not be getting sent to ontoserver. Also concept 8 appears to be missing for one of them.

2) Oxford ingestion - does not appear to match the content as it is on ontoserver - NOte have not yet checked kniotted files to see if this content is read from txa file or term server.

**Comment by maxChappell** [comment]
The 4th link when this was raised points to wrong DE - should be pointing to https://v3.datadictionary.nhs.uk/data_dictionary/data_field_notes/o/ov/overseas_visitor_charging_category_at_cds_activity_date_de.asp?shownav=1

**Comment by maxChappell** [comment]
@jamesrwelch This is one for you please. Default code 9 for the 2 affected items is missing text.

**Comment by AngelaFaulding** [comment]
James can fix the current issue.

**Comment by jamesrwelch** [comment]
This was a result of <font> tags which have no equivalent in DITA.  I've applied a conversion - it might be worth keeping an eye out for any other text which shouldn't be appearing but now is.

**Comment by AngelaFaulding** [comment]
Both items are correct in the June release. Issue closed.
