### ISSUE TITLE
Supporting Information not displaying in Where Used

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#261]
There are a few examples where a Supporting Item is shown as just i in Where Used.

Examples include:

- https://www.datadictionary.nhs.uk/classes/patient.html#class_patient.where_used (above Data Element BASE EXCESS CONCENTRATION)
- https://www.datadictionary.nhs.uk/nhs_business_definitions/adult_improving_access_to_psychological_therapies_programme.html#business_definition_adult_improving_access_to_psychological_therapies_programme.where_used
- https://www.datadictionary.nhs.uk/classes/nhs_service_agreement.html#class_nhs_service_agreement.where_used
- https://www.datadictionary.nhs.uk/classes/operating_theatre.html#class_operating_theatre.where_used

It is not happening for all Supporting Information pages, see

- https://www.datadictionary.nhs.uk/attributes/organisation_code.html#attribute_organisation_code.where_used
- https://www.datadictionary.nhs.uk/classes/general_dental_practitioner.html#class_general_dental_practitioner.where_used
- https://www.datadictionary.nhs.uk/classes/education.html#class_education.where_used

Is this an issue for James or Maxine?

**Comment by AngelaFaulding** [comment]
James to fix

**Comment by jamesrwelch** [comment]
These were mostly pointing at pages such as dataset group overviews, which are not published.  I've hopefully fixed the issue, but might be worth checking I've not removed too many links which should be there.

**Comment by AngelaFaulding** [comment]
I have checked the items above and they are OK. Issue closed.
