### ISSUE TITLE
Use GitHub DataDictionaryPublication code/DITA to hold the generated DITA for the website publication generated by Mauro

### ISSUE THREAD

**Issue by oughnic** [NHSDigital/DataDictionaryPublication#267]

**Comment by oughnic** [comment]
The code directory is https://github.com/NHSDigital/DataDictionaryPublication/tree/master/DITA
Need to pick up the history and roll that forward first
Then change our process to automagically populate GitHub on Export.
"Cherry on the cake" - enable branches to be published into Git branches

**Comment by AngelaFaulding** [comment]
21/12/21 - Nicholas: what needs to be done for this? It isn't assigned to anyone?

**Comment by AngelaFaulding** [comment]
22/12/21 - the DD pipeline uses dita and GitHub. This isn't need for go live.

**Comment by AngelaFaulding** [comment]
This is being done so issue closed.
