### ISSUE TITLE
Run branch via pipeline

### ISSUE THREAD

**Issue by maxChappell** [NHSDigital/DataDictionaryPublication#268]
To be done following June DD release

**Comment by rajabr57** [comment]
23/6 - update from BC: Unaware of this work. Unlikely to be in a position in the short term to take this on without additional resource

**Comment by AngelaFaulding** [comment]
The Jira ticket for this is https://nhsd-jira.digital.nhs.uk/browse/DPNDA-274 which was created on 26 May 2021

**Comment by AngelaFaulding** [comment]
There are two options for this, which is the preferred option?

- Run the pipeline on the branch
- Incorporate the branch into the trunk early and run the pipeline for the dictionary.

**Comment by rajabr57** [comment]
13/7 - resourcing and timescale issues - please can you contact Bob to discuss options.  Cannot commit to 6.3.

**Comment by AngelaFaulding** [comment]
Due to the timescales for CDS 6-3, the CR can now longer be used for testing.
We will used Radiotherapy CR1736.
I have updated the Jira ticket to reflect this.

**Comment by GSChandel** [comment]
Following the discussion in 2nd Aug'21 Show & Tell, this ticket is now closed and new ticket #287 is opened to continue the activities under the EPIC (Ability to migrate the data).
