### ISSUE TITLE
Attributes: No links in National Code descriptions

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#27]

**Comment by maxChappell** [comment]
Have spoken with ontoserver folks - there is no clean fhir way of including hyperlinks in code descriptions (wouold be fine with bespoke handling in mauro - but not good for other user of the code sets via term server.

Options given are:
I guess it comes down to what you’re trying to achieve with them.  Are the links pointers to some rich definition text?  If so, then you might use a property, or a designation with a custom use code (possibly from SKOS or one of the Linked Data schemas).

1:17
The other option is CodeSystem.concept.definition, which is string valued, but I believe it would be perfectly acceptable to assert that the contents is treated as markdown.
The best way I can think of for doing this formally would be to define a DD profile to document it.

**Comment by AngelaFaulding** [comment]
Definitely needs a discussion as we create NHS Business Definitions to help users understand the National Codes.
If they are not linked there will be a lot of NHS Business Definitions that are not used anywhere.

**Comment by maxChappell** [comment]
Workshop note - add full description to a new property

**Comment by maxChappell** [comment]
[Enhancement to FHIR generation app to meet need identified in ticket 27 on github.docx](https://github.com/NHSDigital/DataDictionaryPublication/files/4995231/Enhancement.to.FHIR.generation.app.to.meet.need.identified.in.ticket.27.on.github.docx)

**Comment by maxChappell** [comment]
Spec for change attached

**Comment by maxChappell** [comment]
Note that this will need to rely on the updated html de-refencing app in order to capture the correct hyperlinks to contain in the web presentation property

**Comment by likin1** [comment]
HI,

As mentioned in the comment above. the web description property has been added

**Comment by maxChappell** [comment]
@arkie-boy and @jamesrwelch  This fix will be coming through for you today - Steve may need to do some html tinkering to the added property html

**Comment by AngelaFaulding** [comment]
National Code descriptions now have links, issue closed.
