### ISSUE TITLE
Determine what is required to do for Re-Direct of Data Dictionary Publication in future

### ISSUE THREAD

**Issue by GSChandel** [NHSDigital/DataDictionaryPublication#271]
Production Server for Publishing is installed and up & running. Now it's required to determine how this will work in future and automation requirements. Related to [#185](https://github.com/NHSDigital/DataDictionaryPublication/issues/185)

Definition of Done:
1. Data Products Team to provide advise on how this can be done (solution) and
2. Product Owner to select the final solution to be implemented.

**Comment by GSChandel** [comment]
Ask for Data Products Team is - How 301 and 302 HTTP response will be handled?

**Comment by AngelaFaulding** [comment]
Angela to meet with Robert on Friday (6th) to discuss.

**Comment by rajabr57** [comment]
10/8- Angela has set up another meeting with Robert on 16th August to discuss what was discussed/agreed with Nicholas

**Comment by AngelaFaulding** [comment]
19/08 - I have spoken to Nicholas and he says we don’t have to do anything at the moment.

**Comment by rajabr57** [comment]
12/10 - confirmation from CC that this can be closed

**Comment by AngelaFaulding** [comment]
Issue re-opened.
BC confirms that this still needs doing as a matter of urgency.
GS has contacted the DNS team but there is no delegated authority for the root DD url. This means the old box cannot be closed down.
datadictionary.nhs.uk goes to the old box. www.datadictionary.nhs.uk goes to AWS.
Data Products cannot do anything with this and do not know how to resolve this.
Delegated authority from someone is required to do this.
We need ownership and control of our url; this is not a technical solution.
For CC and NO to discuss.
Robert has discussed this with NO / CC in the past so NO may have some information to help with this.
There may be a process documented somewhere.

**Comment by AngelaFaulding** [comment]
Nicholas says Paul Chapman is managing this.
Bob is dealing with this.

**Comment by PaulChapmanPM** [comment]
For my sins.  That is true.

Paul

Senior Project Manager
Information Standards Architecture
***@***.***
07824 640551

***@***.***
NHS Digital provides information and technology for better health and care.
Find out more about us: www.digital.nhs.uk<http://www.digital.nhs.uk/>  | @nhsdigital

**Comment by PaulChapmanPM** [comment]
We have tried (and failed) to get delegated control of the root domain for Data Products so that option is now closed.
Bob Cox is now taking this up within Data Products to find an alternative solution (as per Teams conversation between Bob and I today.  Bob has confirmed he does not need a new ticket raising for this.

**Comment by AngelaFaulding** [comment]
Jira ticket: https://nhsd-jira.digital.nhs.uk/browse/DPTC-2956

**Comment by AngelaFaulding** [comment]
I have spoken to Kun about the URLs for the archives, version 2 and version 3.

**Comment by AngelaFaulding** [comment]
Kun has produced a test for V2 which looks fine: http://v2.dd.dev.dataproducts.nhs.uk.s3-website.eu-west-2.amazonaws.com/web_site_content/navigation/main_menu.asp.html

**Comment by AngelaFaulding** [comment]
This is covered under #298
