### ISSUE TITLE
Describe Target Infrastructure for Publishing Data Dictionary in Future

### ISSUE THREAD

**Issue by GSChandel** [NHSDigital/DataDictionaryPublication#272]
Definition of Done:

- Data Products Team acts as consultant on how this can or will look like in the AWS using Archimate.
- Product owner to select and finalise the Target Infrastructure.

**Comment by AngelaFaulding** [comment]
22/12/21 - DMDS working with Data Products; they are describing the current infrastructure as part of supporting the TRG approval process: https://github.com/NHSDigital/DataDictionaryPublication/issues/306

**Comment by PaulChapmanPM** [comment]
Ticket #367 created to combine #272, #278 and #306

**Comment by GSChandel** [comment]
Closing as now created as part of the new ticket.
