### ISSUE TITLE
Get Target Infrastructure Architecture submitted for review to TRG

### ISSUE THREAD

**Issue by GSChandel** [NHSDigital/DataDictionaryPublication#273]
Definition of Done:
- Data Products Team to provide a proposed technical documentation and support for submission to Technical Review Group (TRG).
- Project Team to finalise the final submission.

**Comment by rajabr57** [comment]
13/7 - BC has told GC that it is not DP job  - already discussed with Gouri. Position has not changed.

**Comment by AngelaFaulding** [comment]
Duplicate ticket https://github.com/NHSDigital/DataDictionaryPublication/issues/306. Issue closed.
