### ISSUE TITLE
Unified Register Entry for Mauro

### ISSUE THREAD

**Issue by GSChandel** [NHSDigital/DataDictionaryPublication#274]
Requirement from IG.

**Comment by AngelaFaulding** [comment]
@GSChandel - why is this ticket here?
Why is different to how we author now? No new personal data is being collected. We are only changing how we author.

**Comment by cach1** [comment]
@AngelaFaulding @GSChandel the DPIA for Mauro does need updating, as it requires a login for users (our team, basically) - when our old software did not.  Hence it does collect person identifiable information.  @AngelaFaulding if you recall, I sent you the email correspondence I had with the DPIA team and said we need to look at updating it.  Can we meet for half an hour to look at the existing DPIA content and make sure it gets updated please?  We may need assistance from Bob on this as I seem to think Ross Dixon provided some stuff for the original - but lets discuss first before we talk to him on it

**Comment by AngelaFaulding** [comment]
Cannot update the Unified Register, kept getting error messages (possibly as we didn't know what to write).
Meeting planned with Senior Information Governance Specialist to discuss for 21 January 2022.

**Comment by AngelaFaulding** [comment]
Cath and Angie to look at this 27/1/22.

**Comment by AngelaFaulding** [comment]
Entry in the Unified Register created 27/1/22.
Email sent with queries. Will chase if nothing received within a week.

**Comment by AngelaFaulding** [comment]
Meeting arranged for 15/2/22.

**Comment by AngelaFaulding** [comment]
Meeting held 15/2/22 with ,Cath, Angie and Julie Shippen. She is going to send a questionnaire to help with the entry. She is also going to speak to her manager regarding whether an email address is considered to be "Of a confidential or personal nature relating to staff".
Julie will get back to us by email and we can then continue with the entry.

**Comment by AngelaFaulding** [comment]
Cath has raised a call with the IG Helpline and Neil Lang will pick this up next week.

**Comment by GSChandel** [comment]
Cath has spoken with Neil and got advise on retention period of the log. Awaiting confirmation of the classification of login data whether or not it's personal/confidential or not.

**Comment by AngelaFaulding** [comment]
9/3/22 - chased Julie.
Response: I’m sorry I have been taken off Helpline queries. I did ask that this was re-allocated so apologies that no-one has come back to you on this. 
@HELPLINESERVICE, Ig (NHS DIGITAL) really sorry but I can’t remember the IG number for this query, however, are you able to confirm to Angela who this is with now please?

Will await contact from the helpline.

**Comment by AngelaFaulding** [comment]
Response from Helpline received - call scheduled for 14/3/22.

**Comment by AngelaFaulding** [comment]
22/3/22 - Call held 14/3/22.
Aldo to discuss our request with his colleagues to process it further.

**Comment by AngelaFaulding** [comment]
A DPIA is required; Angie and Naresh to work on it.
Neither can update the Unified Register, Angie has access but no update button. Naresh does not have an NHS Digital short code so cannot get access without raising a ticket but he can't raised a ticket via ServiceNow without a shortcode.
Last email sent to paul.hague@nhs.net and ighelplineservice@nhsdigital.nhs.uk on 19 February 2024 requesting help.

**Comment by AngelaFaulding** [comment]
Naresh has confirmation that a DPIA is not required.
Naresh to update the Unified Register.

**Comment by AngelaFaulding** [comment]
@GSChandel - can you please provide an update on this issue?

**Comment by NellySSJ** [comment]
To sum up;
- Checked whether DPIA was required form IG, it wasn't
- Unified Register was decommissioned and Mauro was added to Corestream (Asset 5624)
