### ISSUE TITLE
Document the new model structure

### ISSUE THREAD

**Issue by GSChandel** [NHSDigital/DataDictionaryPublication#275]
Document the new Data Dictionary in Mauro model structure and how to 'Edit' the content within Mauro.

Definition of Done:
1. Every Data Dictionary UML stereotype, there is a map to it's destination in Mauro model.
2. Similarly for Terminologies Data Sets and Code Sets.

**Comment by AngelaFaulding** [comment]
Is this required?

**Comment by AngelaFaulding** [comment]
Work Instructions and Wiki being created with help from James so issue closed.
