### ISSUE TITLE
Mauro documentation to DITA (DPI JIRA#519)

### ISSUE THREAD

**Issue by GSChandel** [NHSDigital/DataDictionaryPublication#277]
As a DITA Open Toolkit DITA Open Toolkit (dita-ot.org) user I need to take in content generated using MkDocs, such as the content at MauroDataMapper/docs: Documentation for the Mauro Data Mapper (github.com), and incorporate within a DITA project for onward publication, including regular DITA content authored outside MkDocs. MkDocs is in Python; DITA-OT is in Java. (JIRA # DPI-519 - https://nhsd-jira.digital.nhs.uk/browse/DPI-519)

**Comment by AngelaFaulding** [comment]
22/12/21 - update from BC. There is a Jira ticket for this: 519. This is not a priority piece of work.

**Comment by AngelaFaulding** [comment]
Jira ticket closed so issue closed.
