### ISSUE TITLE
Create a documentation of the infrastructure supporting the publication

### ISSUE THREAD

**Issue by GSChandel** [NHSDigital/DataDictionaryPublication#278]
Related to [#260](https://github.com/NHSDigital/DataDictionaryPublication/issues/260) 

Definition of Done: Data Products Team to provide documentation in Archimate format (for the work completed by Kun #260 ).

**Comment by AngelaFaulding** [comment]
22/12/12 - part of the TRG approval process: https://github.com/NHSDigital/DataDictionaryPublication/issues/272

**Comment by GSChandel** [comment]
Closing as now created as part of the new ticket.
