### ISSUE TITLE
Data Dictionary team to complete a comprehensive review of the target data model for Mauro that Yousef produced

### ISSUE THREAD

**Issue by GSChandel** [NHSDigital/DataDictionaryPublication#279]
A model for the data to be transformed into for load to Mauro which Yousef created and it needs reviewing by Ali and the Data Dictionary team.

**Comment by cach1** [comment]
@oughnic I have never heard of this model, can we access it somewhere?

**Comment by AngelaFaulding** [comment]
22/12/21 - is this DD4C?

**Comment by AngelaFaulding** [comment]
This is DD4C so can be closed.
