### ISSUE TITLE
Attributes: Default String?

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#28]
Is an attribute that doesn’t have a national code list Type: Default String?

**Comment by maxChappell** [comment]
Is this for items ONLY where there is a default code on a linked data element? or is this a more general question. I suspect the answer is no in both instances - but one for DD team to ponder.

**Comment by maxChappell** [comment]
Maxine and Steve to facilitate a discrete test to show hoe de's with default code - linked to att with no codes will be rendered in beta.

**Comment by maxChappell** [comment]
age at cds activity date - an example de

**Comment by AngelaFaulding** [comment]
Fixed
