### ISSUE TITLE
Submit Proposal for the implemented architecture to TRG

### ISSUE THREAD

**Issue by GSChandel** [NHSDigital/DataDictionaryPublication#284]
Santosh Dubey to work with Data Products to describe the proposal for the implemented architecture and to take this proposal to TRG for review, feedback and suggestions of refinements.

**Comment by AngelaFaulding** [comment]
22/12/21 - Santosh no longer working for NHS Digital. Issue closed. Replaced with https://github.com/NHSDigital/DataDictionaryPublication/issues/306.
