### ISSUE TITLE
NHS Business Definition: Physical Activity Vital SIGN

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#285]
@jamesrwelch: see https://www.datadictionary.nhs.uk/nhs_business_definitions/physical_activity_vital_sign.html and https://www.datadictionary.nhs.uk/nhs_business_definitions_overview.html#nhs_business_definitions.p

Physical Activity Vital SIGN has SIGN in capital letters it should be Sign.

Is this easy to fix?

**Comment by jamesrwelch** [comment]
This is coming through in the "Title Case Name" field in the XML file - I'm not sure what the original source of that value is.  There is a ticket for me to update to using the "Web

**Comment by AngelaFaulding** [comment]
Another example of incorrect case is Faculty of General Dental Practice (Uk): see https://www.datadictionary.nhs.uk/nhs_business_definitions/faculty_of_general_dental_practice__uk_.html

**Comment by jamesrwelch** [comment]
Duplicate of #280

**Comment by AngelaFaulding** [comment]
These look OK in the Oxford preview so will check the August release and then close the issue.

**Comment by AngelaFaulding** [comment]
OK in the August release so issue closed.
