### ISSUE TITLE
Agree an approach to do branch migration

### ISSUE THREAD

**Issue by GSChandel** [NHSDigital/DataDictionaryPublication#287]
Definition of done - Agree an approach of how to do individual branch migration and get it approved by product owner.

**Comment by GSChandel** [comment]
Replacing the ticket #268

**Comment by GSChandel** [comment]
Comments from #268:

The Jira ticket for this is https://nhsd-jira.digital.nhs.uk/browse/DPNDA-274 which was created on 26 May 2021

Due to the timescales for CDS 6-3, the CR can no longer be used for testing.
We will use Radiotherapy CR1736 Jira ticket is updated to reflect this).

Updates - Following 2nd Aug'21 Show & Tell, it was agreed to close #268 and create new tickets for the EPIC (Ability to migrate the data). New tickets #287, #293, #288, #289, #290, #291, and #292 are raised in relation to this EPIC.

**Comment by AngelaFaulding** [comment]
22/12/21 - CR1736 tested by James with support from Likin.

**Comment by AngelaFaulding** [comment]
This has been done as James and Likin are working on CR1736.
