### ISSUE TITLE
Demonstrate that we can do individual branch migration

### ISSUE THREAD

**Issue by GSChandel** [NHSDigital/DataDictionaryPublication#288]
Definition of Done - Demonstrating that the approach agreed can work to do the individual branch migration and get approval from product owner (Nicholas O.) and the customer (Catch C.)

**Comment by AngelaFaulding** [comment]
James tested branch ingest 10/12/21.
Encountered one issue which has been referred to Likin to investigate the reason the for error.
The item had not been edited in the branch.

**Comment by AngelaFaulding** [comment]
Need to check with Likin when he returns from leave,

**Comment by AngelaFaulding** [comment]
The approach has been demonstrated and testing is now taking place. Issue closed.
