### ISSUE TITLE
MVP that the approach of individual branch migration works.

### ISSUE THREAD

**Issue by GSChandel** [NHSDigital/DataDictionaryPublication#289]
Definition of Done - Deliver an MVP showcasing that the approach can do individual branch migration and get MVP approved by Product Owner (Nicholas O.) and the customer (Cath C.)

**Comment by AngelaFaulding** [comment]
James tested branch ingest 10/12/21.
Encountered one issue which has been referred to Likin to investigate the reason the for error.
The item had not been edited in the branch.

**Comment by AngelaFaulding** [comment]
This issue is covered in the other tickets so closed as agreed with CC.
