### ISSUE TITLE
Individual data item migration of history is to be explored and approach to be agreed

### ISSUE THREAD

**Issue by GSChandel** [NHSDigital/DataDictionaryPublication#290]
Definition of Done - an agreed approach of how the Change Requests History can be migrated to Data Dictionary Instances in Mauro and get an approval of the approach from Product Owner (Nicholas O.) and the customer (Cath C.)

**Comment by rajabr57** [comment]
21/9 - meeting held with James and Likin.  Nicholas was unable to attend.  Next meeting is arranged for 28/9.

**Comment by AngelaFaulding** [comment]
21/12/21 - meeting held 10 December 2021. James to produce demo in the new year.

**Comment by AngelaFaulding** [comment]
Duplicate ticket - closed.
