### ISSUE TITLE
Business Definitions with missing or incorrect websitePageHeading or TitleCaseName

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#297]
In trying to fix #280 and #285, I've noticed there are a number of inconsistencies with the generated `websitePageHeading` and `TitleCaseName` fields for Business Definitions in the XML.

There are 34 Business Definitions which don't have the `websitePageHeading` field set at all.  There are others, such as in 'Clinical Situation' where the websitePageHeading field is set as 'Clinical Finding', which clashes with another business definition of the same name

**Comment by AngelaFaulding** [comment]
@jamesrwelch When you get back from leave can you please give me a list of the 34 items and I will have a look at them in Together.

**Comment by jamesrwelch** [comment]
The following business definitions have incorrect 'WebsitePageHeading' or 'TitleCaseName's:
- (Clinical Situation) Clinical Finding,
- (Clinical_Intervention_Date_and_Time) Clinical Intervention Date,
- (Digital Health and Care Wales) NHS Wales Informatics Service,
- (Optical_Headquarters), (Optical_Site) Orthotist,
- (Personalised_Out-Patient_Follow_Up_Pathway_Expiry_Date) Personalised Out-Patient Follow Up Pathway Review Date,
- (eMED3_Fit_Note_Recorded_Date) eMED3 Fit Note Assessment Date

The following Business Definitions have no WebsitePageHeading:

- ABO_System
- Ambulance_Incident_Date_And_Time
- Antenatal
- Antenatal_Care_Plan
- Antiretroviral_Therapy
- Birth_Care_Plan
- Clinical_Investigation
- Cystic_Fibrosis_Trust
- Dating_Ultrasound_Scan
- Fetus_Episode
- Forced_Expiratory_Volume_in_1_second_(Absolute_Amount)
- Healthy_Person_Stay
- Local_Resolution_Eligibility_Decision_Outcome_Communicated_To_Patient_Date_(NHS_Continuing_Healthcare)
- Maternity_Episode
- Mid_Arm_Circumference
- Neonate
- NHS_Continuing_Healthcare_Checklist
- NHS_Continuing_Healthcare_Standard_Checklist_Completed_Date
- Nutritional_Assessment
- Percentage_Weight_Loss
- Personal_Health_Budget
- Postnatal
- Postpartum
- Postpartum_Care_Plan
- Registered_Medical_Practitioner
- Schedule_of_Growing_Skills
- Ultrasound_Scan_In_Pregnancy
- Critical_Care_Period
- Discharge_Letter_Issued_Date_(Community_Care)
- Fetus
- Health_of_the_Nation_Outcome_Scale_65+_(Older_Adults)
- Mantoux_Test
- NHS_Standard_Contract_for_Community_Services
- Peritoneal_Equilibration_Test
- Referral_Closure_Date_(Community_Care)

**Comment by AngelaFaulding** [comment]
Thanks @jamesrwelch .
I will look at these and fix for the September release.

**Comment by AngelaFaulding** [comment]
Fixed in the September release.
