### ISSUE TITLE
Understand options for decommissioning the IIS

### ISSUE THREAD

**Issue by GSChandel** [NHSDigital/DataDictionaryPublication#298]
Definition of Done - Understanding/appraising the options of not using Internet Information Services.

**Comment by AngelaFaulding** [comment]
22/12/12 - this can only be done when all content has moved from the old server. This isn't a showstopper as the old server works.
Old versions of the DD with asp files need to work.
DD4C also has to be migrated before IIS can be stopped. 
Redirect from datadictionary.nhs.uk also needs to be done: https://github.com/NHSDigital/DataDictionaryPublication/issues/271

**Comment by AngelaFaulding** [comment]
These are the pages that we think need to move:
- https://v3.datadictionary.nhs.uk/index.asp
- https://v3.datadictionary.nhs.uk/archive/index.asp
- https://v2.datadictionary.nhs.uk/

**Comment by AngelaFaulding** [comment]
17/3/22 - update from Rachel.
•	DD4C – you need to speak with Michael Chapman to understand his requirements for this migration to Delen – does he want extracts (ie ref sets/data sets) or the full database (not recommended).  Once requirements confirmed, ticket to be raised on DP
•	DD – all pages now moved apart from V3 (something to do with a V3 test page which is linked to it?? You may need to discuss this further with Bob)
•	Redirect from datadictionary.nhs.uk complete

**Comment by AngelaFaulding** [comment]
22/3/22 - https://v3.datadictionary.nhs.uk/ and https://v3.datadictionary.nhs.uk/version3test/cp1738/index.asp cannot be migrated yet.
Certificate renewed:
![image](https://user-images.githubusercontent.com/62995711/159433748-17c6efa4-f68c-4865-8f4b-28e8f68480c9.png)

**Comment by PaulChapmanPM** [comment]
Regarding update on 22 March "_DD4C – you need to speak with Michael Chapman to understand his requirements for this migration to Delen – does he want extracts (ie ref sets/data sets) or the full database (not recommended). Once requirements confirmed, ticket to be raised on DP_": For clarity, Michael Chapman is not managing the migration to Delen so please contact Paul Chapman for any information about requirements. (Michael is in the loop though).

**Comment by rajabr58** [comment]
Please remove DP team label from this ticket as this is not for them.  As per previous comment, once requirements have been confirmed, a ticket should be raised on DP.

**Comment by AngelaFaulding** [comment]
DMDS working with Data Solutions to find an alternative may of publishing for when the server is End of Life.

**Comment by AngelaFaulding** [comment]
All content has now been moved from the old server either to the cloud or the new Windows server.
Ticket closed.
