### ISSUE TITLE
Attributes: Some codes missing

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#30]
Some codes missing, e.g. CATEGORY VALUED PERSON OBSERVATION TYPE, which doesn’t have a Data Element. Where will the codes be displayed?

**Comment by jamesrwelch** [comment]
I believe this is fixed now

**Comment by AngelaFaulding** [comment]
Selection checked and there are now National Code lists for:
ACTIVITY DATE TYPE
ACTIVITY GROUP TYPE
CLINICAL INTERVENTION TYPE
SERVICE TYPE
