### ISSUE TITLE
Content license management

### ISSUE THREAD

**Issue by GSChandel** [NHSDigital/DataDictionaryPublication#307]
Mauro content licenses:

May be a two-phase approach:

1.	Bodge – a link at the bottom of each page pointing to a set of licences like the Terminology Server.
2.	Doing it right – either learning from TRUD or incorporating TRUD licence management into Mauro.  TRUD is rather good!  It should be able to provide licence assignment as a service with the flexibility for auto-approval or manual based on complex rules.

**Comment by BobCox-afk** [comment]
Gouri

Do not assign tickets to me without my consent.  The owner is you.

Bob

**Comment by AngelaFaulding** [comment]
@GSChandel - is this ticket still required?
You created this but it is not assigned to anyone.

**Comment by AngelaFaulding** [comment]
Thanks @PaulChapmanPM .
It needs discussing at the next planning meeting.

**Comment by AngelaFaulding** [comment]
Doesn't need doing until Post Migration.

**Comment by AngelaFaulding** [comment]
This isn't a dictionary issue, it is for Mauro.
Oxford have their own tickets about this.
