### ISSUE TITLE
CR production via Oxygen

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#309]
When CRs are generated via Mauro the pdf will be generated via Oxygen.
From discussion at the SoW meeting on 7/1/22 the preferred method was for a local version of Oxygen to be used rather than the server version.
This needs confirming as a copy of Oxygen would be required for each member of the NHS Data Model and Dictionary Service.
And potential continued use of the Developer Solution for all members, not just Configuration Management.

**Comment by BobCox-afk** [comment]
Just for the record, this has all the hallmarks of another terrible idea
that hasn't been thought through. Developer solutions should only be used
for non persistent development purposes. ICT only supply them in that basis
and they are largely unsupportable. They should never be relied upon as
part of a permanent production solution. The clue is in the name.

**Comment by AngelaFaulding** [comment]
Once CR Dita is produced by James, we will test in Oxygen and then discuss with Bob them possibility of generating the pdf through the DD pipeline.

**Comment by AngelaFaulding** [comment]
CR Dita has been provided by James. I have tested it in Oxygen.
Note that work is required on the stylesheet.
I have created a Jira ticket to discuss with Bob the possibility of generating the pdf through the DD pipeline: https://nhsd-jira.digital.nhs.uk/browse/DPNDA-322

**Comment by AngelaFaulding** [comment]
Call with Kun 28/1/22.
Need to discuss a couple of things with James and Cath and will then get back to Kun.

**Comment by AngelaFaulding** [comment]
Kun is working to add this to the DD Release Manager.

**Comment by AngelaFaulding** [comment]
Issue closed as it is covered in #406
