### ISSUE TITLE
Female Genital Mutilation Identification Method Code - where used - Datasets

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#31]
FEMALE GENITAL MUTILATION IDENTIFICATION METHOD CODE:
- Codes are on both the Attribute and Data Element
- The Data Element is not using as being used in the data set

**Comment by maxChappell** [comment]
I think this ticket can be closed now - unless I'm missing something, so assigned to Angela for review/closure.

**Comment by AngelaFaulding** [comment]
The item is used in the Female Genital Mutilation Data Set but that is not showing on the Data Element "Where Used".

I have checked one other item from another data set: "DATE FIRST SEEN" and it shows it is used in the National Cancer Waiting Times Monitoring Data Set.

I have checked another FGM item: Female Genital Mutilation Identification Method Code and it is not showing as being used in FGM.
Is there an issue with the FGM data set Where Used?

**Comment by maxChappell** [comment]
Await next release from James

**Comment by maxChappell** [comment]
This is the same as #32 and #34

**Comment by AngelaFaulding** [comment]
Data Elements now showing as used in the data sets, issue closed.
