### ISSUE TITLE
Oxford Documentation

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#326]
James has to provide guidance on how to use Mauro and the dictionary plugins.
James has been given access to Confluence. He is going to add his guidance to that.

**Comment by GSChandel** [comment]
James - Have put some content on Confluence and will continue to do so.

**Comment by AngelaFaulding** [comment]
Angie and Kate are working with James to get the documentation on the Wiki. This will continue through testing.

**Comment by AngelaFaulding** [comment]
15/2/22 - Wiki pages continue to be produced as we go through things with James.

**Comment by AngelaFaulding** [comment]
Ticket to be closed as it is covered by #233.
