### ISSUE TITLE
Procurement for Pen Testing

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#328]
Prepare and run pen testing procurement to penetration test of metadata.nhs.uk.

**Comment by AngelaFaulding** [comment]
Still needs doing unless it will be done by the supplier.

**Comment by NellySSJ** [comment]
This has been completed by the Security Assurance.
Related issue - https://github.com/NHSDigital/DataDictionaryPublication/issues/330
