### ISSUE TITLE
Ordering of National Codes

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#33]
o	The order of National Codes doesn’t match the DD. It appears that they are listed in number or alphabetical order, e.g.

These now relate to Data Elements:
- ATTENDED_OR_DID_NOT_ATTEND CANCER_OR_SYMPTOMATIC_BREAST_REFERRAL_PATIENT_STATUS
- INTENDED_DELIVERY_PLACE
- JOINT_REPLACEMENT_REVISION_REASON_CODE_FOR_SHOULDER
- PATIENT_PROCEDURE_PERFORMED_INDICATOR
- RENAL_VEIN_TUMOUR_INDICATOR

**Comment by jamesrwelch** [comment]
These should now be reflecting the defined "Web Order" added to the definitions in the ontoserver

**Comment by AngelaFaulding** [comment]
Order is OK on the selection above.
