### ISSUE TITLE
Prepare and run the Pen Testing on metadata.nhs.uk.

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#330]
Prepare and run the Pen testing on metadata.nhs.uk.
This includes re-platforming metadata.nhs.uk onto corporate standard infrastructure.

**Comment by PaulChapmanPM** [comment]
Checked in with Bob.  No further progress made on this and not possible to forecast when the work will be done.  I'll check in with him again in about another week.

**Comment by AngelaFaulding** [comment]
Comment from Nicholas:

I’m checking with Aled – assuming 
1.	he has done the tests
2.	You are hosting on the Answer Digital infrastructure
Then no, the tests probably aren’t required.

Can you leave the ticket open for now?

**Comment by AngelaFaulding** [comment]
Update from Nicholas:

Our test partner Precursor are running pen testing on: 

Environment: 25th - 26th August
Application: 29th August - 1st Sept

I'll issue a note to the mailing list with any impact on availability but have scheduled on Saturday / BH week to avoid potential impact on users.

Let's review risks and mitigations in the week after that 

Aled Greenhalgh
Answerdigital

**Comment by AngelaFaulding** [comment]
1/7/24 - Transformation Directorate colleague newsletter - 28 June states:

Spotlight on the Penetration Testing and Assurance Team (PTAT)
PTAT helps to proactively identify any weaknesses a cyber criminal could use to compromise NHS systems or steal patient data. The service is available to all NHS England teams. Tests must be carried out before a service goes live when there are major changes to a service or on an annual basis to ensure the service continues to be secure. [Learn more about the service](https://gbr01.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftransformation.cmail20.com%2Ft%2Fd-l-eihmjt-dyvliujjk-v%2F&data=05%7C02%7Cangela.faulding%40nhs.net%7Cf61d6972ea9141db63dc08dc9768d261%7C37c354b285b047f5b22207b48d774ee3%7C0%7C0%7C638551723679391735%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=x7nTzgzORbAmqaE4XECPdJJOU0OxJ9d3JQpVlhRKXW8%3D&reserved=0).

**Comment by NellySSJ** [comment]
Web PEN testing completed on Mauro UAT environment. Recommendations for remedial actions shared with System C, Mauro team and Data Solutions.

**Comment by AngelaFaulding** [comment]
@NellySSJ - is this still outstanding?

**Comment by NellySSJ** [comment]
@AngelaFaulding - testing has been completed on our environment.

I believe metadata.nhs.uk mentioned in this ticket is the instance under AnswerDigital and I understand PEN test was completed on that side too. If this is something that they need to pursue further, then this should ticket should be part of that project. Otherwise, this should be closed if this ticket needs to remain on our project.

**Comment by AngelaFaulding** [comment]
Issue closed as per the comment from @NellySSJ above.
