### ISSUE TITLE
Data Sets missing from "where used"

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#34]
Data sets have underscores:
- HARS_TEST_INDICATOR: HIV_and_AIDS_Reporting_Data_Set
- APPOINTMENT_SLOT_SHORT_NOTICE_CANCELLATION_INDICATOR: Improving_Access_to_Psychological_Therapies_Data_Set,

**Comment by maxChappell** [comment]
See e.g. https://beta.datadictionary.nhs.uk/data_elements/h/h/hars_submission_identifier.html - data set link no longer appears at all for this item (same with the second example) - so are all data set links for **where used** missing?

**Comment by AngelaFaulding** [comment]
It appears so, another example is: https://beta.datadictionary.nhs.uk/data_elements/o/ou/out-patient_attendance_indicator__radiotherapy_data_set_.html

**Comment by AngelaFaulding** [comment]
Data Elements showing as used in data sets, issue closed.
