### ISSUE TITLE
PLICS Constraints Pages

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#356]
Details taken from #320 as this is a separate issue.

The All Items Index in V3+ for the PLICS Constraints pages looks odd:

![image](https://user-images.githubusercontent.com/62995711/150323101-a53b50b5-81e0-429b-a64b-068f97449de9.png)

They also look odd on the Supporting Information menu:

![image](https://user-images.githubusercontent.com/62995711/150323172-2989e713-f33a-4cb4-be69-a08d4da560cd.png)

**Comment by AngelaFaulding** [comment]
7/2/22 - Discussion with James. Moved to To Do.

**Comment by AngelaFaulding** [comment]
15/2/22 - James still needs to do this and we will then need to be check it via the published output.

**Comment by AngelaFaulding** [comment]
Fixed in the March 2022 release.

**Comment by AngelaFaulding** [comment]
@PaulChapmanPM - T shirt label removed as now fixed.

**Comment by PaulChapmanPM** [comment]
T-Shirt label re-added
