### ISSUE TITLE
Open ID Connect

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#358]
Get OIDC set up for NHS Digital active directory.
Not required for go live.

**Comment by AngelaFaulding** [comment]
Still required.
This is dependent on whether we own this (Data Solutions) or the supplier.

**Comment by NellySSJ** [comment]
Hi @AngelaFaulding is this the same as https://github.com/NHSDigital/DataDictionaryPublication/issues/568

If so, I suggest this one can be closed.

**Comment by AngelaFaulding** [comment]
Closed as per the comment above from Naresh.
