### ISSUE TITLE
Issues with Admission Method - default code clash

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#36]
ADMISSION_METHOD:

Not sure what has happened with the last row: 
- Admission via Mental Health Crisis Resolution Team is code 25
- There is no Gate-Kept Mental Health Admission 41 in the DD
- The codes are now on the Data Element, but the note is still on the Attribute
- This is the same for others, e.g. ADMISSION METHOD
- This needs addressing as the notes may be missed.

**Comment by maxChappell** [comment]
21/07/20 - Checked on ontoserver and beta site (June 2020 release)
code 25 is correct
No code 41 found in code system
Notes are being adapted/added by DD team

However - default code clash noted for 99

**Comment by maxChappell** [comment]
Default code 99 is wrong on ontoserver. There is a default code clash between the two elements for this attribute...so should NOT be getting sent to term server.

ADMISSION METHOD CODE (MOTHER LABOUR AND DELIVERY HOSPITAL PROVIDER SPELL) 
99 - Not Known (Not Recorded)

ADMISSION METHOD CODE (HOSPITAL PROVIDER SPELL)
99 - Not known: a validation error

**Comment by AngelaFaulding** [comment]
We can't fix this now as both items are used in different data sets.

**Comment by maxChappell** [comment]
Likin - Please investigate why default codes are not getting sent in knitted txa for items where there is no ontoserver content.

**Comment by AngelaFaulding** [comment]
Text on the default codes will be fixed in the October release

**Comment by maxChappell** [comment]
Can see that default codes now match on v3. site. However, not picked up by FHIR generation - old default codes on new site for Oct release. Also, content not on ontoserver.

**Comment by maxChappell** [comment]
These items are now getting sent to Ontoserver correctly - From Jan 21 release onwards. Current day looks correct.

Business decision needed on if the gap in the series of items (March 2019 to Jan 2021) due to the default code clash needs a fix to correct history. If we don't - helpdesk will have a record of these dates if any queries come in.

**Comment by AngelaFaulding** [comment]
This is only an issue for the Terminology Server. Cath will talk to Maxine about this.

**Comment by AngelaFaulding** [comment]
Maxine said "am waiting for final run and error file in a digestible format so that we can agree whether or not we need to something clever (manually) to plug the historic gap."

**Comment by likin1** [comment]
![image](https://user-images.githubusercontent.com/59052650/159016207-72361a7f-fc39-49ca-999e-731291e12e47.png)

**Comment by likin1** [comment]
![image](https://user-images.githubusercontent.com/59052650/159016404-65aa3f51-462f-49b4-8ab4-ef70c379b9eb.png)

**Comment by likin1** [comment]
the default code clash is no longer present. Hence the marking as fixed
