### ISSUE TITLE
Test Mauro output Vs Together output

### ISSUE THREAD

**Issue by PaulChapmanPM** [NHSDigital/DataDictionaryPublication#362]
Run output from Mauro and equivalent output from Together to prove that the respective systems produce identical content.
This will be done for release, previews and CRs. 

Definition of Done:
Angela Faulding to design tests and confirm they have been successfully passed.

**Comment by AngelaFaulding** [comment]
21/05/24 - we need the Orchestrator working as expected and a new version of the DDPM to be able to do this.

**Comment by AngelaFaulding** [comment]
@stevebowring - is Solution Assurance doing this?

**Comment by stevebowring** [comment]
Short answer is - yes, we now need to work out which documents to send and how we get them over

**Comment by AngelaFaulding** [comment]
Ticket closed and replaced with #573
