### ISSUE TITLE
Set up arrangement with Procurement to ensure that Oxygen license procurement is automatically triggered through Commercial BAU processes

### ISSUE THREAD

**Issue by PaulChapmanPM** [NHSDigital/DataDictionaryPublication#365]

**Comment by AngelaFaulding** [comment]
@GSChandel - this should have been sorted ages ago. Why is it still live?

**Comment by GSChandel** [comment]
All the required steps are taken. New licenses are procured and due ones are in pipeline for approval. The BAU teams are assigned for future triggers and approvals. Project now handed it over to BAU for business continuation. Ticket is now closed.
