### ISSUE TITLE
National Code headings missing

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#37]
- ADMISSION_METHOD
- CLINICAL_CARE_INTENSITY
- SOURCE_OF_REFERRAL_FOR_OUT-PATIENTS

**Comment by jamesrwelch** [comment]
This is being fixed in the April 2020 release

**Comment by maxChappell** [comment]
Think this looks complete.

**Comment by AngelaFaulding** [comment]
I fixed the National Codes in Together.
