### ISSUE TITLE
Fix Data Sets in preview of CR

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#371]
Previews are generated through the Orchestrator.
The data sets are not displaying in the preview, e.g. https://modelcatalogue.cs.ox.ac.uk/orchestration/#/preview/d2fe90f6-32bb-4215-bd93-e11bfc1f1f02/dataSet/e3749b2c-2643-460c-8156-fe2e4480afae
This need fixing so we can test the output.

**Comment by AngelaFaulding** [comment]
15/2/22 - this has been partially fixed but James has further work to do.

**Comment by jamesrwelch** [comment]
This code needs further testing before deployment.  It is subject to the issues raised in #398 and #372

**Comment by AngelaFaulding** [comment]
19/08/24 - data sets are not displaying in the CR in the Orchestrator.

**Comment by pjmonks** [comment]
See my comment in #525 - specifically https://github.com/NHSDigital/DataDictionaryPublication/issues/525#issuecomment-2317289761

My screenshots show that data sets do appear in the Orchestrator preview of change papers. If there is some other issue you are referring to, we will need more information.

**Comment by AngelaFaulding** [comment]
Closed as superseded by #525
