### ISSUE TITLE
Add integrity check to search for invalid html

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#376]
If possible, we would like an integrity check added to search for HTML in Mauro that won't convert to Dita very well.

**Comment by AngelaFaulding** [comment]
15/2/22 - still outstanding.

**Comment by jamesrwelch** [comment]
@PaulChapmanPM Changed T-shirt size on this as a result of the work I've done on HTML -> DIta conversion in the last two weeks

**Comment by AngelaFaulding** [comment]
Doesn't appear to be an issue now. Will open a new ticket if required.
