### ISSUE TITLE
Ethnic Category Code - missing de default code

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#38]
ETHNIC_CATEGORY_CODE:
- Has extra codes
- The codes are now on the Data Element, but the extra codes are still incorrectly in the list

**Comment by maxChappell** [comment]
Data item updated - all attribute codes now showing correctly....However - loss of meaning with headings omitted. One for a patch update and do we worry about history?

**Comment by maxChappell** [comment]
Also note - default code on ETHNIC_CATEGORY de is missing from beta

**Comment by maxChappell** [comment]
Headings for this item can be omitted from beta

**Comment by maxChappell** [comment]
Next step is to check why default code is missing.

**Comment by maxChappell** [comment]
Hi Likin - please check why default codes have not been passed along in the knitted txa file for Ethnic_Category

**Comment by maxChappell** [comment]
Newly split items (to avoid the historic default code clashes) are still not being sent to ontoserver (Oct 2020). Bespoke handling will be needed.

**Comment by GSChandel** [comment]
21/06/2021 - in progress.

**Comment by AngelaFaulding** [comment]
Still outstanding.

**Comment by likin1** [comment]
Hi Angela,

Can you please let me know what is missing and where. I have checked it on my end and it seems fine to me

**Comment by GSChandel** [comment]
Awaiting Maxine response from Angela's email.

**Comment by maxChappell** [comment]
Discussed with Likin - de-prioritised until branch migration work is completed.

**Comment by AngelaFaulding** [comment]
From Maxine 28/1/22:
Put these in the backlog for now. Likin has been prioritised towards enabling branch migration and CR migration ahead of any tickets re FHIR gen history. Ideally – these will be addressed pre migration – Only post migration if we really have to.

**Comment by likin1** [comment]
![image](https://user-images.githubusercontent.com/59052650/159266668-935265c0-7e84-4c43-b3e0-d104cdc5ee2e.png)
![image](https://user-images.githubusercontent.com/59052650/159266793-9c8b4072-a99d-44fa-9a3e-7f6b76012a81.png)
![image](https://user-images.githubusercontent.com/59052650/159266912-de878a32-b61c-402f-81b0-3f98b19a7764.png)
![image](https://user-images.githubusercontent.com/59052650/159267022-a9b95cac-1264-4cad-b08e-cd1971e8e374.png)

**Comment by likin1** [comment]
Hi ,as per my last comment above. No default code is missing. There is no default code 'de' is present. Hence closing the issue

**Comment by AngelaFaulding** [comment]
16/05/22 - confirmed with Maxine that this is OK to be closed.
