### ISSUE TITLE
Has extra code: Z Not Stated

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#39]
Has extra code: Z Not Stated (PERSON asked but declined to provide a response):
- EMPLOYMENT_STATUS
- SPECIAL_EDUCATIONAL_NEED_TYPE

The codes are now on the Data Element, but the comment is still valid

**Comment by maxChappell** [comment]
Appears correct now.

**Comment by AngelaFaulding** [comment]
Extra Z removed, can close.
