### ISSUE TITLE
Names have %20 in them

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#4]
https://modelcatalogue.cs.ox.ac.uk/datadictionary/businessdefinitions/a.html:
In the list names have %20
- Accessible%20Information
- Adult Mental Health, Learning Disability or %20Autism Spectrum Disorder Care Spell
- Arrival Date and Time at%20Accident and Emergency Department
- Comment still valid
Other examples:
- Emergency Care Initial Assessment%20 Date
- Goal%20Based%20Outcomes
- Multidisciplinary Team Discussion Date%20(Cancer)
- Ultrasound%20Scan
- Comment still valid, however, I have discovered the cause of this and have fixed the ones I have found in Together.
- Can a scan be done please to see if there are any left in the new release?

**Comment by AngelaFaulding** [comment]
I have gone through the list provided by Steve. Some are Attribute Class links which are not easy to spot. I have already fixed some of these so have asked Steve to run this again after the April release to check they have all been fixed.

**Comment by AngelaFaulding** [comment]
Issue closed as the items highlighted in the original review have been fixed.
6 July 2020: Steve has been asked to run another scan to see if there are any more items with %20 in the name.
