### ISSUE TITLE
Error in Attributes: M category

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#40]
Attributes m, https://modelcatalogue.cs.ox.ac.uk/datadictionary/attributes/m/m.html:
has in the list: LEGAL_STATUS_RESTRICTIVENESS

**Comment by jamesrwelch** [comment]
This is because of the url / file path where it's stored: I guess it was previously named "Mental Health ... " and its location wasn't changed.  However, in this case, the item is retired and so shouldn't be appearing in that list anyway.

**Comment by AngelaFaulding** [comment]
No longer appearing, issue closed.
