### ISSUE TITLE
Multiplicity in Data Groups and Sub Groups

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#404]
When we created data groups and sub groups in a data set with James, he said we didn't need to add multiplicity.
However, we had a further discussion with James when we were creating data groups and sub groups.
This is because, currently words are used for the multiplicity but moving forward when we author in Mauro should we be using multiplicity?
![image](https://user-images.githubusercontent.com/62995711/155509734-f5dc7de8-ec6d-443f-aed5-da3838205be2.png)

**Comment by AngelaFaulding** [comment]
28/2/22 - agreed to add the multiplicity and the words for each data group and sub group.

**Comment by AngelaFaulding** [comment]
Is this fixed or is it dependant on #372.

**Comment by jamesrwelch** [comment]
Dependent on #372

**Comment by AngelaFaulding** [comment]
Issue closed as it is covered in #372 and doesn't have a t shirt label.
