### ISSUE TITLE
Classifications not working?

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#41]
Are Classifications not working, e.g.
- COMMUNICATION_CONTACT_METHOD
- PERIOD_ADMINISTERED
- ADDRESS_FORMAT_TYPE

Comment still valid. Do we need to change these to National Codes? However, they are not designed to flow so will be confusing as they would be downloadable codes and on Wayne’s tool. We only would want them on Attributes, as with Clinical Intervention Type etc.

**Comment by maxChappell** [comment]
DD team have changed heading to national codes on these three items - all codes now passing through correctly.

HOWEVER, COMMUNICATION_CONTACT_METHOD - still showing as linked to a data element in mauro - but not on dd website.

**Comment by maxChappell** [comment]
The data element linked to is PDS COMMUNICATION CONTACT METHOD (MOTHER OF BABY) - which is now a retired item

**Comment by maxChappell** [comment]
To confirm - it's the mauro output that still carries the link

**Comment by AngelaFaulding** [comment]
Items now displaying correctly, issued closed.
