### ISSUE TITLE
Retired text doesn’t show any different to other text - same as issue 92

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#42]
Retired text doesn’t show any different to other text, is that intended, e.g.
- CANCER CARE PLAN INTENT 
- CLINICAL_INTERVENTION_TYPE
Where are the codes for this item as there is no Data Element

**Comment by oughnic** [comment]
We have a valueset with some codes as live (C,Z,X) and some retired (P,S,N)
There are no outputclass attributes on any of the rows in the table of codes.

Looks like we need to pull the current status from the Ontoserver and add outputclass property "retired"

@AngelaFaulding Do you want the date of retirement to come from the Ontoserver date or keep as text

**Comment by oughnic** [comment]
(or just leave it as it shows the current classes)
If keeping, we would want the otherprops retired(true) adding to the strow as well

**Comment by maxChappell** [comment]
This is linked to ticket 92 - the metadata is already there on the code systems

**Comment by AngelaFaulding** [comment]
Needs discussion on whether we want the date of retirement to come from the Ontoserver date or keep as text.
I'm not sure whether Ontoserver would give the correct date.
Maxine - can you confirm whether it would?

**Comment by maxChappell** [comment]
#92 

Text on ontoserver description is as per text on current website.
Date set in fhir property against a concept for retirement is derived date of publish.
Suggest use the status property for the concept level status and leave the description for the code as per current web site and thus the concept description within the fhir codesystem.

All values - active and retired are in ontoserver.

**Comment by maxChappell** [comment]
Looks like none of the retired codes are currently being displayed on beta
