### ISSUE TITLE
Data Set Multiplicity

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#433]
In the current dictionary data sets we have mandation of:
- M
- R
- O
- P
- X

In Mauro, we add this as "Multiplicity", where it says "Use numbers only".
What do we put for P and X?
How do we differentiate between R and O?

![image](https://user-images.githubusercontent.com/62995711/165248281-73fe0a77-5c8e-4232-8e44-c88f5d08fefd.png)

**Comment by jamesrwelch** [comment]
We're treating multiplicity and mandation as separate concepts here, and so the mandation will need to be stored as part of  a profile.  However, due to #372 we can't currently store them against data elements that are brought in from another model.

**Comment by AngelaFaulding** [comment]
Ticket to be closed as this will be addressed by #372.
