### ISSUE TITLE
Default Codes

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#437]
I'm raising an issue for this so we understand what is required.
Default Codes are currently on Data Elements so when the Dita is published it as shown as Default Codes on the Data Elements.
When Default Codes are added to Mauro they added as a Terminology, the same as National Codes.
How will the Dita output process know what is a Default Code.
There is an option in the Term Profile to tick "Is Default Code".
Do we have to do this for all Default Codes?

![image](https://user-images.githubusercontent.com/62995711/165775292-f0e8d34a-acb1-405a-af87-545310d61680.png)

**Comment by AngelaFaulding** [comment]
James to think about this.

**Comment by AngelaFaulding** [comment]
The "Is Default Code" option needs to be ticked for every default code.

**Comment by AngelaFaulding** [comment]
Can't test this yet as am unable to create a term:
![image](https://user-images.githubusercontent.com/62995711/186370030-d5606822-d928-413c-89a9-85049b60c0c4.png)

This has been referred to James.

**Comment by jamesrwelch** [comment]
This needs a minor fix in Mauro - definition and description should both be optional, with definition defaulting to the code.

**Comment by jamesrwelch** [comment]
The original issue - that default codes need to be signalled, does not require further development and the new 'bulk editor' functionality will make this easier for editors.

**Comment by AngelaFaulding** [comment]
Still needs a fix.

**Comment by AngelaFaulding** [comment]
All default codes should be marked in the profile. This is part of the process.
Issue to be closed.
