### ISSUE TITLE
Develop draft MoU with Oxford University Hospitals NHS Trust for Mauro Development resource

### ISSUE THREAD

**Issue by PaulChapmanPM** [NHSDigital/DataDictionaryPublication#448]
NHS England are aiming to put in place an MoU between NHS E and Oxford University Hospitals NHS Trust in order to take advantage of their software development capabilities and unique relationship with Oxford University. This will facilitate an increase in software development resource on the Data Dictionary Mauro development work. As this work significantly benefits the Mauro Implementation project, and in order to expedite the addition of resource to the project, we will support them in the development of the MoU.

D.O.D. 
- First draft MoU written and circulated for review.

**Comment by AngelaFaulding** [comment]
No longer relevant.
