### ISSUE TITLE
Organisation Code / Organisation Site Code

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#45]
ORGANISATION CODE and ORGANISATION SITE CODE:

https://modelcatalogue.cs.ox.ac.uk/datadictionary/attributes/o/o.html doesn’t have them in the list

Comment still valid. Need to understand how the lists are working. It could be confusing that the retired items are in the first list but not all are showing as retired, e.g. OVERSEAS VISITOR QUOTA NUMBER
OVERSEAS VISITOR REFERRAL PRODUCED
OVERSEAS VISITOR TREATMENT PREARRANGED
But https://modelcatalogue.cs.ox.ac.uk/datadictionary/attributes/o/org.html has

**Comment by AngelaFaulding** [comment]
Attributes are now in the correct list.
