### ISSUE TITLE
Check website for issues that have been fixed

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#452]
James has spoken to Likin and identified an issue with Attributes and Data Elements where the National Codes heading is missing and html around the Permitted National Codes is not correct.
The following items have been checked and html made consistent with other items that work:
- PROSTATE CANCER CLINICAL RISK CATEGORY
- REFERRING CARE PROFESSIONAL TYPE FOR NHS CONTINUING HEALTHCARE STANDARD
- GS1 APPLICATION IDENTIFIER (INTERNAL)
- SMOKING STATUS (CANCER).

We will not be able to check this until the November 2022 release.

**Comment by AngelaFaulding** [comment]
17/11/22 - looks OK at:
- https://dduat.dev.dataproducts.nhs.uk/attributes/prostate_cancer_clinical_risk_category.html
https://dduat.dev.dataproducts.nhs.uk/attributes/referring_care_professional_type_for_nhs_continuing_healthcare_standard.html
- https://dduat.dev.dataproducts.nhs.uk/data_elements/smoking_status__cancer_.html

@jamesrwelch and @likin1 
https://dduat.dev.dataproducts.nhs.uk/attributes/gs1_application_identifier__internal_.html - the National Codes heading looks different. Who needs to fix this?

**Comment by AngelaFaulding** [comment]
To be checked in the December 2022 release.

**Comment by likin1** [comment]
Hi, I have rechecked this issue and it is occurring due to concept clash. 

check the data element:-
![image](https://user-images.githubusercontent.com/59052650/206198764-97c18169-cf6d-4055-994e-f3cd4f56f8b3.png)

attribute 

![image](https://user-images.githubusercontent.com/59052650/206199246-1ead054e-3176-48ab-ad52-6676435308d7.png)

**Comment by AngelaFaulding** [comment]
This has been fixed so will check the January release to see if it looks OK.

**Comment by AngelaFaulding** [comment]
Fixed in the January 2023 release: https://www.datadictionary.nhs.uk/data_elements/gs1_application_identifier__internal_.html
Issued closed.
