### ISSUE TITLE
EPMA data set landing page - incorrect text displayed

### ISSUE THREAD

**Issue by cach1** [NHSDigital/DataDictionaryPublication#457]
EPMA was introduced in the July DD release, there are 2 different data sets (Prescribing and Medicines Admin), hence it has a second 'landing' menu, in the same way as COSDS does.  Document attached highlighting what it looks like in V3 (with the correct text description appearing under the 2 different data sets), vs what it looks like in V3+ (with the same text appearing under both).

[EPMA landing menu.docx](https://github.com/NHSDigital/DataDictionaryPublication/files/9490196/EPMA.landing.menu.docx)

**Comment by AngelaFaulding** [comment]
@jamesrwelch  - can this be looked at for the next release please?

**Comment by AngelaFaulding** [comment]
@jamesrwelch - there was a problem in Together which meant the landing page was also not correct in V3. I have fixed that so hopefully this can be fixed for the next release.

**Comment by AngelaFaulding** [comment]
@jamesrwelch - this still isn't correct. See https://v3.datadictionary.nhs.uk/data_dictionary/messages/clinical_data_sets/overviews/epma_data_set_overviews/electronic_prescribing_and_medicines_administration_data_sets_introduction.asp?shownav=1

The landing page should say:
The Electronic Prescribing and Medicine Administration Data Set is made up of the following data sets:

Prescribing 
The EPMA - Prescribing Data Set relates to PRESCRIBED ITEMS for a PATIENT, including information on the active ingredient SUBSTANCES, dosage instructions and therapeutic indications for prescribing.

Medicines Administration 
The EPMA - Medicines Administration Data Set relates to the administration of PRESCRIBED ITEMS to a PATIENT.

Can this be looked at for the next release please?

**Comment by AngelaFaulding** [comment]
James to see if this can be fixed.

**Comment by AngelaFaulding** [comment]
@jamesrwelch - this still isn't fixed but isn't urgent.
Can you investigate for the next release please?

**Comment by AngelaFaulding** [comment]
@jamesrwelch - thus still isn't fixed: https://www.datadictionary.nhs.uk/data_sets/clinical_data_sets/epma.html

Electronic Prescribing And Medicines Administration Data Set - Medicines Administration and Electronic Prescribing And Medicines Administration Data Set - Prescribing both have the same description.
They don't on V3: https://v3.datadictionary.nhs.uk/data_dictionary/messages/clinical_data_sets/overviews/epma_data_set_overviews/electronic_prescribing_and_medicines_administration_data_sets_introduction.asp@shownav=1.html

Can you have a look at this please?

**Comment by AngelaFaulding** [comment]
@jamesrwelch - this still isn't correct.

This is how the page looks in V3:
![image](https://github.com/NHSDigital/DataDictionaryPublication/assets/62995711/69d2c1a0-696a-460c-8665-8a6b91edeea3)

This is how it looks in the May 2024 release:
![image](https://github.com/NHSDigital/DataDictionaryPublication/assets/62995711/1837a5d0-b868-4ee6-943f-1c927c05f2ad)

Can this be fixed in the June 2024 release as the ISN will be published and more people will look at the release?
