### ISSUE TITLE
cm^2 not copied correctly - special characters

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#46]
cm<sup>2</sup> not copied correctly
RESECTION_STATUS
It says cm2, can it be changed?

**Comment by jamesrwelch** [comment]
This appears to be an issue with the data coming from the onto server

**Comment by oughnic** [comment]
This is an issue between text and format.  Unicode symbol's hex code for square symbol, that is 00B2.  Could be addressed either in the dictionary or on translation.  To type it into Together hold down the Alt key and type 0178 on the numeric keypad.  We may have a larger "units of measure" issue to address where descriptions include units.

**Comment by maxChappell** [comment]
Need to be able to assign Likin to this one. We will both need to do some testing. Suggest we mop this up with other "special characters"

**Comment by maxChappell** [comment]
Have checked our corresponding DITA outputs...we do use <sup> around the 2

**Comment by maxChappell** [comment]
Also noted - the information is held within the transformed txaclass files too -> e,g, Less than 1.5 cm&lt;sup&gt;2&lt;/sup&gt

Needs discussion.

**Comment by maxChappell** [comment]
Looks probable that we can fix this for ontoserver entries too ->


U+00B2 | ² | 0178 | &sup2; | Superscript two | 0114
-- | -- | -- | -- | -- | --
U+00B3 | ³ | 0179 | &sup3; | Superscript three

**Comment by jamesrwelch** [comment]
Happy with either the Unicode characters above, or the `<sup></sup>` tags.  Resection Status has `cm2` a couple of times in the value set.

**Comment by maxChappell** [comment]
Let's go with unicode fix. Assigning Likin.

**Comment by likin1** [comment]
Hi ,
A fix has been amde for this iisue and the item has been regenearted on ontoserver.RESECTION_STATUS

**Comment by maxChappell** [comment]
fixed
