### ISSUE TITLE
Degree Symbols

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#461]
We recently updated a number Attributes  as the website was displaying a masculine ordinal indicator instead of a degree symbol.
I  checked with you both and agreed that it was Ok to make the change.
However, we have had a helpdek query in today regarding https://www.datadictionary.nhs.uk/data_elements/degrees_of_flexion_range__primary_knee_replacement_.html?hl=degrees%2Cflexion%2Crange%2Cprimary%2Cknee%2Creplacement where the degree symbol looks odd:
![image](https://user-images.githubusercontent.com/62995711/205286812-d74371c3-3a31-4637-96ff-6d5f214bdd5e.png)
Note that this looks OK in V3: https://v3.datadictionary.nhs.uk/data_dictionary/attributes/d/dec/degrees_of_flexion_range_for_primary_knee_replacement_de.asp?shownav=1

On checking other items, there is a difference in what is displayed:
https://www.datadictionary.nhs.uk/attributes/tibia-hindfoot_alignment_code_for_primary_ankle_replacement.html
https://www.datadictionary.nhs.uk/attributes/ankle_dorsiflexion_code_for_primary_ankle_replacement.html
https://www.datadictionary.nhs.uk/attributes/ankle_plantarflexion_code_for_primary_ankle_replacement.html
https://www.datadictionary.nhs.uk/attributes/degrees_of_fixed_flexion_deformity_for_primary_knee_replacement.html

Is this something for @jamesrwelch or @likin1 to fix?
Can we fix it for the December 2022 release?

**Comment by jamesrwelch** [comment]
How are you entering those symbols?  The codes are not coming through cleanly in the XML - they'd be better if they were coming through as `&deg;`.  
![Screenshot 2022-12-05 at 23 04 39](https://user-images.githubusercontent.com/1869668/205762498-3433bf32-6961-424b-8c99-fe9202915003.png)

As an aside, the copyright symbol is having the same issues in the onto server bit of the XML, not that it's used.
![Screenshot 2022-12-05 at 23 04 58](https://user-images.githubusercontent.com/1869668/205762518-ea019b67-6923-43dc-9a04-00edb8b58283.png)

**Comment by AngelaFaulding** [comment]
@likin1 - you haven't mentioned this. Is it something you can fix?

**Comment by likin1** [comment]
@AngelaFaulding yes this should be fixed in december release.

**Comment by AngelaFaulding** [comment]
Thanks @likin1 - I will check when I have the dita output.

**Comment by AngelaFaulding** [comment]
These are now OK in the December release.
