### ISSUE TITLE
National Codes are not correct

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#47]
National Codes are not correct:

REVISION PROCEDURE TYPE:
- REVISION_PROCEDURE_TYPE_FOR_HIP_REPLACEMENT has 11, 5, 52, 7, 8, A, B, C, D
- DD REVISION PROCEDURE TYPE FOR HIP REPLACEMENT  has 5, 7, 8, 11, 52

SETTLED ACCOMMODATION
- SETTLED_ACCOMMODATION_INDICATOR has 0, 1, N, Y, Z
- SETTLED ACCOMMODATION INDICATOR has Y, N, Z

**Comment by jamesrwelch** [comment]
Generally fixed now, with the exception of those awaiting correction in the Ontoserver

**Comment by AngelaFaulding** [comment]
These items are now correct.
