### ISSUE TITLE
Orchestrator: Integrity Checks: Elements linked to an attribute

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#481]
In the Orchestrator: Integrity Checks it is showing "Elements linked to an attribute" as 2694.
It looks like all links on the Data Elements have been removed:

![image](https://github.com/NHSDigital/DataDictionaryPublication/assets/62995711/1622253d-358c-409e-b338-16b7c5242b91)

![image](https://github.com/NHSDigital/DataDictionaryPublication/assets/62995711/ab5f88b4-49c6-4469-a266-6939e64f050d)

Also, when you click on the items it goes to: https://modelcatalogue.cs.ox.ac.uk/nhsd-datadictionary//#/catalogue/notFound
I assume it will be fixed for live?

**Comment by pjmonks** [comment]
Thanks @AngelaFaulding. I had already spotted this last week after I deployed to test, I've now linked our own work item to this for tracking.

**Comment by pjmonks** [comment]
@AngelaFaulding These hyperlinks have been fixed now, please re-test and update this issue accordingly.

**Comment by AngelaFaulding** [comment]
This is linked to #523 so can be closed
