### ISSUE TITLE
Missing tables

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#5]
HTML Table temporarily redacted is no longer displayed but the tables are missing

**Comment by cach1** [comment]
Does this relate to AREA OF WORK NAME table?

**Comment by AngelaFaulding** [comment]
I will remove the National Codes heading and the links on the Data Elements as these are not National Codes.
This will be done in the October release

Maxine - will this resolve your issue?

**Comment by maxChappell** [comment]
Issue already resolved from our end (likin pipe) - mauro processes whether on ontoserver or not appropriately.

**Comment by maxChappell** [comment]
Question for @oughnic and @cach1 - do we care that historic fhir items for this are not available on ontoserver? Or should we create this items' history by creating some bespoke code?

**Comment by oughnic** [comment]
Assuming its area of work, I'm not inclines to invest extra effort here.

**Comment by AngelaFaulding** [comment]
This has been fixed by removing the National Codes header on the Attribute as the table doesn't contain National Codes.
The table is appearing on the Data Element, I wasn't expecting that. Is that what was intended?

**Comment by maxChappell** [comment]
Gaps in historic fhir content will by identified via db queries and business will make decisions on where/whether to invest effort to fill the historic gaps. So happy to now close this.
