### ISSUE TITLE
No format on items with National Codes

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#50]
No Format on items with National Codes, e.g.
- ADMISSION_METHOD_CODE_(HOSPITAL_PROVIDER_SPELL)

There is a format on items with no National Codes, e.g. 
- ADMITTED_PATIENTS_IN_MONTH_TOTAL
Is that how it works?
There is no format now on both items

**Comment by jamesrwelch** [comment]
Several items have Type: is this ever populated? Is this just on Data Elements that don’t have National Codes?
- E.g. ADMITTED_PATIENTS_IN_MONTH_TOTAL
- APGAR_SCORE_(5_MINUTES) doesn’t have type
- Question still valid
- Will the types be populated so users can click on to see the format/length?

**Comment by maxChappell** [comment]
Format/length id within the html e.g. for ADMISSION_METHOD_CODE_(HOSPITAL_PROVIDER_SPELL) format length is 
an2

ADMITTED_PATIENTS_IN_MONTH_TOTAL its format length is 
max n7

I cannot see a "type" on current website for ADMITTED_PATIENTS_IN_MONTH_TOTAL

May have misunderstood this ticket, I presume when you say "Several items have Type" you are meaning a mauro type?

Ticket does however raise the question of how consistently the format/lengths are described. I will do some digging.

**Comment by jamesrwelch** [comment]
I've now added the format/length fixed for all elements

**Comment by AngelaFaulding** [comment]
Data Elements now have format/length.
