### ISSUE TITLE
Class Relationships appearing incorrectly on the Orchestrator

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#509]
Peter showed us how to add Class relationships on Monday.
I added the relationships as instructed and they don't appear correctly on the Orchestrator.
I will add this to go through next Monday.

Relationships in  CR8000 - National Eye Colour Data Set Version 1 for Person Stated Eye Colour and Category Valued Person Observation.

![image](https://github.com/user-attachments/assets/5d61b625-d406-4e39-be45-80cc03bb4e5e)

![image](https://github.com/user-attachments/assets/d9e631ac-e856-43ae-ae61-b9e127802148)

**Comment by pjmonks** [comment]
Me and @jamesrwelch were aware of this issue and were planning to resolve it once the publishing was ready to test. It is on our backlog.

**Comment by pjmonks** [comment]
We have a fix pending for class relationship description text, currently in review/testing internally:

- MauroDataMapper-NHSD/mdm-plugin-nhs-data-dictionary#64

Also, this is a duplicate of one of your other issues:

- #531

**Comment by AngelaFaulding** [comment]
19/08/24 - System are working on this.

**Comment by AngelaFaulding** [comment]
Please also see the comments and examples on #509 which I will close as it is a duplicate.
