### ISSUE TITLE
Admission Method Code (Hospital Provider Code)

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#51]
ADMISSION_METHOD_CODE_(HOSPITAL_PROVIDER_SPELL):

Not sure what has happened with the last row: 
- Admission via Mental Health Crisis Resolution Team is code 25
- There is no Gate-Kept Mental Health Admission 41 in the DD

**Comment by jamesrwelch** [comment]
I believe this is now correct

**Comment by AngelaFaulding** [comment]
This now looks OK.
