### ISSUE TITLE
National Codes not correct

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#52]
National Codes are not correct, e.g.

REVISION PROCEDURE TYPE:
- ANAESTHETIC_TYPE_(JOINT_REPLACEMENT) has 01, 02, 03, 04, 10, 11, 5, 9
- DD ANAESTHETIC TYPE FOR JOINT REPLACEMENT has 5, 9, 10, 11
Comment still valid, codes still incorrect

ASA PHYSICAL STATUS CLASSIFICATION SYSTEM CODE
- ASA_PHYSICAL_STATUS_CLASSIFICATION_SYSTEM_CODE_(NATIONAL_JOINT_REGISTRY) has 1, 2, 3, 4, 5, 8
- ASA PHYSICAL STATUS CLASSIFICATION SYSTEM CODE FOR NATIONAL JOINT REGISTRY has 1, 2, 3, 4, 8
Codes still not consistent

ASSOCIATED PROCEDURE TYPE
- ASSOCIATED_PROCEDURE_TYPE_(ANKLE_REPLACEMENT) has 01, 02, 03, 04, 05, 06, 07, 08, 09, 1, 10, 11, 12, 2, 3, 4, 5, 6, 7, 8, 9
- DD ASSOCIATED PROCEDURE TYPE FOR ANKLE REPLACEMENT has 1, 2, 3, 4, 5, 6, 7, 8, 9, 12, 10, 11,
Comment still valid, codes still incorrect

Other examples include BIRTH_LENGTH
- This is now correct but how would the user know what the format/length is?

**Comment by maxChappell** [comment]
Steve has processed it for you - see example below (**):
<DDDataElement>
      <base-uri>file:/Users/steveharris/bitbucket/nhsdd-preprocessing/April_2020_release/transformedoutput/Data_Dictionary/Data_Field_Notes/A/As/ASA_PHYSICAL_STATUS_CLASSIFICATION_SYSTEM_CODE_(NATIONAL_JOINT_REGISTRY).txaClass20</base-uri>
      <ultimate-path>http://www.datadictionary.nhs.uk/data_dictionary/data_field_notes/a/as/asa_physical_status_classification_system_code_(national_joint_registry)_de.asp</ultimate-path>
      <uin>fjgl1hl4snp9n-fjh87</uin>
      <baseVersion>Version 3.0&lt;;&gt;3.0.1</baseVersion>
      <name>ASA_PHYSICAL_STATUS_CLASSIFICATION_SYSTEM_CODE_(NATIONAL_JOINT_REGISTRY)</name>
      <aliasPlural>ASA PHYSICAL STATUS CLASSIFICATION SYSTEM CODES (NATIONAL JOINT REGISTRY)</aliasPlural>
      <link uin="ieje0rjrt9kedg-4311yl">
         <metaclass>KernelAssociation20</metaclass>
         <participant referencedUin="fjgl1hl4snp9n-fjh87" role="Client"/>
         <participant referencedUin="-tdsqjujrt8ndc4jhswzy" role="Supplier"/>
      </link>
      <link-target>
         <kind>DDAttribute</kind>
         <name>ASA_PHYSICAL_STATUS_CLASSIFICATION_SYSTEM_CODE_FOR_NATIONAL_JOINT_REGISTRY</name>
      </link-target>
      **<format-length>an1</format-length>**

**Comment by AngelaFaulding** [comment]
These items are now correct.
