### ISSUE TITLE
Displaying hyperlinks in format/length fields

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#53]
Strange entry on: https://modelcatalogue.cs.ox.ac.uk/datadictionary/elements/a/as.html
Index Page
ASA_PHYSICAL_STATUS_CLASSIFICATION_SYSTEM_CODEASA_PHYSICAL_STATUS_CLASSIFICATION_SYSTEM_CODE 

Strange entry on: https://modelcatalogue.cs.ox.ac.uk/datadictionary/elements/h/h.html
- HEALTH_PROGRAMME_STAGE_NUMBER (HUMAN_PAPILLOMAVIRUS_VACCINE)HEALTH_PROGRAMME_STAGE_NUMBER_(HUMAN_PAPILLOMAVIRUS_VACCINE)

Strange entry on: https://modelcatalogue.cs.ox.ac.uk/datadictionary/elements/f/f.html
FURTHER_ASSESSMENT_REQUIRED_INDICATOR_(IMPAIRED_FASTING_GLYCAEMIA_IMPAIRED_GLUCOSE_TOLERANCE_LIFESTYLE_MANAGEMENT)
Strange text, e.g.
ANTIRETROVIRAL THERAPY DRUG (SNOMED CT DM+D): See DM+D_CODE: there is no link to this item
This is the same on CANCER_PROGRESSION_(ICD) with no link to ICD-10_CODE
- Trademark symbol now ok.
- How would the user know what the format/length is?

**Comment by maxChappell** [comment]
ASA PHYSICAL STATUS CLASSIFICATION SYSTEM CODE - getting passed through correctly by steve's processing.

Re ANTIRETROVIRAL THERAPY DRUG (SNOMED CT DM+D): See DM+D_CODE: there is no link to this item - the link is de-referenced in the usual way in the transformed txaclass files.

**Comment by AngelaFaulding** [comment]
ANTIRETROVIRAL THERAPY DRUG (SNOMED CT DM+D): See DM+D_CODE: there is no link to this item
This is the same on CANCER_PROGRESSION_(ICD) with no link to ICD-10_CODE.
For discussion on Thursday.
