### ISSUE TITLE
Merging

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#533]
Peter tried to demonstrate merging and it didn't work.

He said he would fix it and produce documentation as we haven't had any training.

Ticket raised to ensure this is fixed and the documentation is produced.

**Comment by pjmonks** [comment]
I have created our own issue for tracking this:

- MauroDataMapper-NHSD/mdm-plugin-nhs-data-dictionary#102

**Comment by pjmonks** [comment]
I have just emailed you a Word document containing instructions for merging and finalising dictionary branches in Mauro.

**Comment by AngelaFaulding** [comment]
19/08/24 - System C are working on this.

**Comment by AngelaFaulding** [comment]
Merging still doesn't work so has been passed to James.

**Comment by AngelaFaulding** [comment]
Ticket not needed as there other merge tickets which haven't been fixed yet.
