### ISSUE TITLE
Unique items

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#538]
As a test of copying an item, in the Test Branch, I copied PERSON STATED GENDER and called it PERSON STATED EYE COLOUR, which I have in CR8000.

I received the message below.

Does this mean the name has to be unique in Mauro, not just in a branch?

![image](https://github.com/user-attachments/assets/2685565d-b9a5-4858-be3b-82d585f1c766)

**Comment by pjmonks** [comment]
A label must be unique within a branch. When you copy you must select the right branch to target. I have copied PERSON STATED GENDER (under "Test branch") successfully, calling it PERSON STATED EYE COLOUR, see here:

![Image](https://github.com/user-attachments/assets/ac86b90a-1dda-4a31-bc12-ec92135506fe)

In this case, you probably picked the wrong place to copy to, this is where it should have gone:

![Image](https://github.com/user-attachments/assets/accac2ad-c332-4448-b21f-b0a1597cecdc)

**Comment by AngelaFaulding** [comment]
I will retest this.

**Comment by AngelaFaulding** [comment]
This is now working.
