### ISSUE TITLE
Extra space

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#54]
Not a major issue but there is space between the ‘ and the definition, e.g. EMERGENCY CARE ARRIVAL DATE

**Comment by jamesrwelch** [comment]
This doesn't look too bad now... but in the description coming out of the .txa classes, there's an unnecessary bit of spacing and styling:

**Comment by maxChappell** [comment]
Are we content with this? Or do we need to actively remove extra spaces?

**Comment by AngelaFaulding** [comment]
In Together there were extra em tags but no space. I have removed the extra tags.
It still shows an extra space before and after the apostrophe.
' Emergency Care Arrival Date ' .
Cath - it is the same with all similar items, can we live with this?

**Comment by AngelaFaulding** [comment]
This is not a big deal but does need fixing, who needs to do this?
