### ISSUE TITLE
CATEGORY VALUED PERSON OBSERVATION: PERSON PHYSICAL ACTIVITY LEVEL Class Relationship

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#546]
@jamesrwelch - could you please have look at the CATEGORY VALUED PERSON OBSERVATION: PERSON PHYSICAL ACTIVITY LEVEL Class Relationship.

Why doesn't PERSON PHYSICAL ACTIVITY LEVEL in V3+ have "or" as it does in V3.

V3 has:
<img width="353" alt="image" src="https://github.com/user-attachments/assets/b5e46500-7e62-4e04-a9a1-11ac26cb6d19">

V3+ has:
<img width="509" alt="image" src="https://github.com/user-attachments/assets/0bf5ae1c-7fbd-4e85-b0f9-6c62fb881347">

**Comment by AngelaFaulding** [comment]
James to investigate.
ACTIVITY also has or but I'm not sure if it is the same: https://www.datadictionary.nhs.uk/classes/activity.html
Does this helps?

**Comment by jamesrwelch** [comment]
The relationship to `PERSON PHYSICAL ACTIVITY LEVEL` is modelled slightly differently from all the others.  In the XML, I'm seeing that relationship owned by that class, with `relationClientExclusivity` set to `A`.  Whereas the other 24 relationships are owned by their respective target classes, with `relationSupplierExclusivity` set to `A`.

**Comment by AngelaFaulding** [comment]
Thanks @jamesrwelch - I will try to make this relationship the same as the others.

**Comment by AngelaFaulding** [comment]
Relationships updated and will check in the next release.

**Comment by AngelaFaulding** [comment]
Looks OK in the test publication.

**Comment by AngelaFaulding** [comment]
OK in the new release so the issue can be closed.

![image](https://github.com/user-attachments/assets/dd61efea-bca3-49b7-8d34-42824af45746)
