### ISSUE TITLE
Permitted National Codes

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#55]
Are Permitted National Codes working ok?, e.g.

- DD MATERNITY CARE PLAN TYPE has 3 codes
- MATERNITY_CARE_PLAN_TYPE has a lot more codes, looks like the full list

- There are other e.g. s of this: MAIN_SPECIALTY_CODE_(MENTAL_HEALTH) etc.

**Comment by maxChappell** [comment]
No. permitted codes are not showing correctly. see https://beta.datadictionary.nhs.uk/data_elements/p/pers/person_stated_gender_code__stop_smoking_.html

This item should only have 1 and 2 as permitted codes (identifiable by Data Element Property - with value matching the name of element)

The inverse is also true - we are seeing default codes (defined on data elements) listed against an attribute. see https://beta.datadictionary.nhs.uk/attributes/p/person/person_stated_gender_code.html
The item should not have X code. Use the Data Attribute property to identify which codes from a union are defined within the attribute itself.

**Comment by AngelaFaulding** [comment]
Both items checked and they are now OK.
