### ISSUE TITLE
STOP SMOKING AID TREATMENT TYPE

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#555]
Hi @jamesrwelch - can you have a look at STOP SMOKING AID TREATMENT TYPE please.
The National Codes are not displaying on the Attribute

https://www.datadictionary.nhs.uk/attributes/stop_smoking_aid_treatment_type.html
![image](https://github.com/user-attachments/assets/ca1d537b-b41b-476b-9aaf-db78e394c69b)

https://v3.datadictionary.nhs.uk/data_dictionary/attributes/s/stan/stop_smoking_aid_treatment_type_de.asp@shownav=1.html
![image](https://github.com/user-attachments/assets/8c5c517e-4f2d-4c14-84e1-84c2f07c6b87)

**Comment by AngelaFaulding** [comment]
James will investigate as it appears there is an issue with the ingest.

**Comment by jamesrwelch** [comment]
Sadly this may be an issue for Likin to investigate - that attribute is coming through with only the default code and no national codes included.  I can provide more information to Likin if needed.

<img width="1254" alt="Screenshot 2024-09-03 at 14 10 21" src="https://github.com/user-attachments/assets/2edb4623-b818-417a-aaa7-5df5485ffa94">

**Comment by jamesrwelch** [comment]
I've run an Path query over the ingest XML file and this is the only instance where there are codes, but no national codes defined

**Comment by AngelaFaulding** [comment]
Hi @likin1  - please see the issue above and comment from James.
Can you investigate please?

**Comment by likin1** [comment]
hi @AngelaFaulding , I can see that it was not present in the august release but I ran another branch 1915 after that and I can see that the codes are present

![image](https://github.com/user-attachments/assets/552cbae9-3cb7-4791-85a7-74ac099e5f8f)

**Comment by AngelaFaulding** [comment]
Thanks @likin1 - I will test in the next release.

**Comment by AngelaFaulding** [comment]
Looks OK in the test publication.
