### ISSUE TITLE
Extra Space

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#56]
Not a big issue but where a Data Element “is the same as attribute” there is a space after the attribute name and the full stop, e.g.
- CANCER PROGRESSION (ICD)
- ACCOMMODATION STATUS CODE

**Comment by maxChappell** [comment]
Not urgent

**Comment by arkie-boy** [comment]
I think this is a James one.  I've just looked at the HTML I send to James and there doesn't appear to be any spaces, so I'm guessing its an artefact of replacing the 'a' tag with an internal link.

CANCER_PROGRESSION_(ICD_ORIGINAL)</a> is the same as attribute <a href="http://www.datadictionary.nhs.uk/data_dictionary/attributes/c/cla/clinical_classification_code_de.asp">CLINICAL_CLASSIFICATION_CODE</a>.<p>

ACCOMMODATION_STATUS_CODE</a> is the same as attribute <a href="http://www.datadictionary.nhs.uk/data_dictionary/attributes/a/acc/accommodation_status_code_de.asp">ACCOMMODATION_STATUS_CODE</a>.

**Comment by arkie-boy** [comment]
(of course it rendered the html.  fml.  apologies)

**Comment by maxChappell** [comment]
In the DITA file the full stop appears on next line

<xref outputclass="element"
            keyref="element_cancer_progression__icd_original_">CANCER PROGRESSION (ICD ORIGINAL)</xref>
 is the same as attribute 
    <xref outputclass="attribute" keyref="attribute_clinical_classification_code">CLINICAL CLASSIFICATION CODE</xref>
.  </p>

Have assigned to both Nicholas and James - as css might be able to handle?

**Comment by maxChappell** [comment]
This may also be same issue as #8

**Comment by AngelaFaulding** [comment]
This appears to have been fixed, can it be closed?
