### ISSUE TITLE
Formula Milk or Milk Fortifier Type

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#57]
FORMULA MILK OR MILK FORTIFIER TYPE (SNOMED CT DM+D):
- The link goes to DDV3 and is not green
- The majority of links on this page go to DDV3

**Comment by jamesrwelch** [comment]
This is because the link in the description has a space character between CT and DM; the 'ultimate path' field has a %20.  If spaces are being replaced by underscores, then this shouldn't be an issue in the next release

**Comment by maxChappell** [comment]
Completed by James
