### ISSUE TITLE
'Where Used' looks strange - missing dataset names

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#6]
Datasets are listed, but their names not given

**Comment by jamesrwelch** [comment]
This is because they're pointing at CDS definitions, which are not generated yet.  Hopefully will be fixed when the CDS datasets go in

**Comment by maxChappell** [comment]
see https://beta.datadictionary.nhs.uk/data_elements/h/h/hars_submission_identifier.html seems to be common across all DD object types. - MIssing Data sets in where used.

**Comment by AngelaFaulding** [comment]
Data sets now shoeing in Where Used, issue closed.
