### ISSUE TITLE
Ordering of Data Sets

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#60]
What is the order of the data sets? It doesn’t match the DD order and isn’t in alphabetical order

- Datasets: Retired 
- Datasets: Clinical Content 
- Datasets: Supporting Data Sets 
- Datasets: Clinical Data Sets 
- Datasets: Central Return Data Sets 
- Datasets: Administrative Data Sets

**Comment by jamesrwelch** [comment]
Data Set groups not in the correct order, they appear to be in alphabetical order, e.g. 
https://modelcatalogue.cs.ox.ac.uk/datadictionary/datasets/clinical_data_sets/cancer_outcomes_and_services_data_set/cancer_outcomes_and_services_data_set___core.html
- Top is: PERSON OBSERVATION – CORE
- Should be: SUBMISSION HEADER
- Order still not correct, RECORD IDENTIFIER should be followed by LINKAGE – CORE, not DIAGNOSIS: ADDITIONAL ITEMS - CORE

**Comment by maxChappell** [comment]
Assigned to Angela, Cath and Nicholas in order to answer the original question re menus and ordering.

**Comment by maxChappell** [comment]
Re first question - use of navigation txaclass files should resolve in most instances.

**Comment by maxChappell** [comment]
James is capturing data group order for data set tables

**Comment by maxChappell** [comment]
OK at this level of navigation/structure.
