### ISSUE TITLE
CR Paper not showing updated format

### ISSUE THREAD

**Issue by stevebowring** [NHSDigital/DataDictionaryPublication#606]
When we produce a CR paper using NHSE tools we are unable to replicate the format changes implemented by System C.

Initial investigation suggest our version of Oxygen (24.1) may be a factor.

Data Solutions to investigate.

**Comment by stevebowring** [comment]
Peter has confirmed we are using the same stylesheets - Likin to look at updating Oxygen to version 26

**Comment by stevebowring** [comment]
DITAS avaiable in this ticket comment

 https://github.com/NHSDigital/DataDictionaryPublication/issues/540#issuecomment-2385317567

**Comment by stevebowring** [comment]
Data Solutions to obtain Oxygen 26.

**Comment by stevebowring** [comment]
Data Solutions to update our CSS and LESS Stylesheets with code supplied by Peter.

**Comment by AngelaFaulding** [comment]
@stevebowring - is this linked to #308? Do we need both tickets?

**Comment by AngelaFaulding** [comment]
Ticket closed as this has been done.
