### ISSUE TITLE
Clinical Content - has an extra content index page

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#61]
Clinical content: has an extra content index page. Can this be removed?

**Comment by maxChappell** [comment]
Not sure who can action/answer this

**Comment by AngelaFaulding** [comment]
https://beta.datadictionary.nhs.uk/data_sets/clinical_content.html is not require.

Why can't https://beta.datadictionary.nhs.uk/data_sets.html go straight to https://beta.datadictionary.nhs.uk/data_sets/clinical_content/content.html ?

**Comment by AngelaFaulding** [comment]
Extra page removed, issue closed.
