### ISSUE TITLE
Ordering of COSD Data Sets

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#63]
DataSets: cancer outcomes and services data set:
- Core should be at the top of the list, rather than being in alphabetical order

**Comment by AngelaFaulding** [comment]
This is OK on the introduction page but not on the menu

**Comment by AngelaFaulding** [comment]
Menu still not in the correct order, see https://www.datadictionary.nhs.uk/data_sets/clinical_data_sets/cosds/cancer_outcomes_and_services_data_set_-_core.html

**Comment by AngelaFaulding** [comment]
James will investigate when we migrate for:
https://www.datadictionary.nhs.uk/data_sets/clinical_data_sets/cosds.html
https://www.datadictionary.nhs.uk/data_sets/clinical_content/national_joint_registry_data_set.html
https://www.datadictionary.nhs.uk/data_sets/supporting_data_sets.html
https://www.datadictionary.nhs.uk/data_sets/cds_v6-2.html

**Comment by AngelaFaulding** [comment]
10/12/21 - should be able to do this in the data set folder when we have migrated to Mauro

**Comment by AngelaFaulding** [comment]
Issue closed as it is a duplicate of #392
