### ISSUE TITLE
Data Set aliases not working - null hrefs

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#65]
Data Set aliases not working, e.g.
- “Using the Community_Services_Data_Set  ( null ) XML Schema.”
- “The Mental_Health_Services_Data_Set  ( null ) is a”

**Comment by AngelaFaulding** [comment]
The aliases are still not working, e.g.
The Mental Health Services Data Set  ( null ) 
The Maternity Services Data Set ( null )
The Community Services Data Set  ( null )

**Comment by AngelaFaulding** [comment]
The aliases are still not working, e.g.
The Mental Health Services Data Set ( null )
The Maternity Services Data Set ( null )
The Community Services Data Set ( null )

**Comment by maxChappell** [comment]
To fix this one - processing needs to get the property property name="Data_Dictionary_Profile_x__y_DD_Alias_x__y_aliasSchema"  whenever the following occurs for an anchor label - alias=&quot;**schema**&quot; in the txaclass file

**Comment by maxChappell** [comment]
`alias=&quot;schema&quot;` = Data_Dictionary_Profile_x__y_DD_Alias_x__y_aliasSchema property

**Comment by likin1** [comment]
Hi,

this has been fixed

**Comment by maxChappell** [comment]
agreed.
