### ISSUE TITLE
Could be confusing for users to have Attribute Name and Attribute Type on data sets

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#66]

**Comment by maxChappell** [comment]
In DD world I believe the heading should be Data Element and Data Element Type - can you confirm please Angela?

**Comment by AngelaFaulding** [comment]
The items in data sets are Data Elements, not Attributes.
So yes the headings should be: Data Element Name and Data Element Type

**Comment by AngelaFaulding** [comment]
Data sets now have: 
Data Element Name | Data Element Type
Ticket closed.
