### ISSUE TITLE
XML Constraints pages not in UPPER CASE

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#68]
The text at the top of all data sets is missing. The overview text is there but nothing else, e.g.

https://modelcatalogue.cs.ox.ac.uk/datadictionary/datasets/clinical_data_sets/diagnostic_imaging_data_set.html and 
https://www.datadictionary.nhs.uk/data_dictionary/messages/clinical_data_sets/data_sets/diagnostic_imaging_data_set_fr.asp?shownav=1

https://modelcatalogue.cs.ox.ac.uk/datadictionary/datasets/clinical_data_sets/radiotherapy_data_set.html and
https://www.datadictionary.nhs.uk/data_dictionary/messages/clinical_data_sets/data_sets/diagnostic_imaging_data_set_fr.asp?shownav=1

Still missing and no XML Constraints pages

**Comment by maxChappell** [comment]
Info is there in DDDataSet/definition element - and up to first table. Is this more of a question re where to place this text - as we are no longer using split screen/frames?

**Comment by AngelaFaulding** [comment]
Agreed, we need to decide where to put the text as it is required.

**Comment by maxChappell** [comment]
Missing text will be resolved in together by dd team.

Please ensure that message documentation folder contents get processed so that xml schema constraints pages etc. are generated

**Comment by AngelaFaulding** [comment]
The Constraints pages are there, however, the PLICS constraints pages are named incorrectly. They should all be PLICS (as in Together) but are showing the beta version as:
Plics Reconciliation Data Set Constraints
Plics Acute Supplementary Information Data Set Constraints
Plics Acute Specialist Ward Care Data Set Constraints
Plics Acute Out-patient Care Data Set Constraints
Plics Acute Emergency Care Data Set Constraints
Plics Acute Admitted Patient Care Data Set Constraints

**Comment by maxChappell** [comment]
PLICS vs Plics should be fixed in next release of knitted files from Likin.

Likin - we will need to re-run for both August and Sept releases as we may initially go-live with the August release.

**Comment by maxChappell** [comment]
Title case conversion needs some form of update? item https://v3.datadictionary.nhs.uk/data_dictionary/messages/message_documentation/data_set_constraints/plics_acute_specialist_ward_care_data_set_constraints_de.asp  

Retrieved title case is <TitleCaseName>Plics Acute Specialist Ward Care Data Set Constraints</TitleCaseName>

**Comment by AngelaFaulding** [comment]
Checked the October release and we still have:
Plics Acute Admitted Patient Care Data Set Constraints
Plics Acute Emergency Care Data Set Constraints
Plics Acute Out-patient Care Data Set Constraints
Plics Acute Specialist Ward Care Data Set Constraints
Plics Acute Supplementary Information Data Set Constraints
Plics Reconciliation Data Set Constraints
