### ISSUE TITLE
Mandation / Multiplicity

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#69]
No mandation (M/R/O/P) on any Data Elements
- Now has Mandatory, Required and Optional but is there an issue with Pilot?
The Neonatal Data Set has an issue with:
PERSON GENOTYPIC SEX (NATIONAL NEONATAL DATA SET)
QUALIFICATION ATTAINMENT LEVEL MOTHER (NATIONAL NEONATAL DATA SET)
CRANIAL ULTRASOUND SCAN PERFORMED INDICATOR 

No mandation on any of the groups (the words define this, e.g. One occurrence of this group is required.)

**Comment by jamesrwelch** [comment]
Therefore, there is no note to describe how the data flows, e.g.

Community:
Service or Team Type Referred To:
To carry details of the Service or Team that the person has been referred to.
One occurrence of this group is permitted for each service or team that a person has been referred to.
Still no group mandation.
Data Element mandation is called Multiplicity. Changes to wording may result in changes to other pages.
Multiple occurrences on Data Elements missing, e.g. COSDS CORE: CANCER METASTATIC DISEASE TYPE
Without the correct mandation, we will never be able to generate an XML Schema from the dictionary.
Need to be able to see where groups are nested, e.g. COSDS which now has choices groups

**Comment by maxChappell** [comment]
P in current DD tables - when table heading only "allows" M/R/O

**Comment by AngelaFaulding** [comment]
This is two things.
I have fixed the P issue in Neonatal and will fix any other that I am notified of.
The occurrences issue is another thing.
I will create a new ticket for that.
