### ISSUE TITLE
Data Sets not grouped correctly

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#70]
Data Sets are not grouped correctly, e.g.

https://modelcatalogue.cs.ox.ac.uk/datadictionary/datasets/supporting_data_sets.html
Should be grouped as:

- Contract Monitoring:
    - Aggregate Contract Monitoring
    - Devices Patient Level Contract Monitoring
    - Drugs Patient Level Contract Monitoring
    - Patient Level Contract Monitoring

- Critical Care:
    - Critical Care
    - Neonatal Critical Care
    - Paediatric Critical Care

- Other:
    - Information Sharing to Tackle Violence

- Patient Level Information Costing:
    - Reconciliation (PLICS)
    - Admitted Patient Care (PLICS)
    - Emergency Care (PLICS)
    - Out-Patient Care (PLICS)
PLICS has: DataSets: Patient Level Information Costing System Acute Data Set

**Comment by AngelaFaulding** [comment]
Now OK.
