### ISSUE TITLE
No navigation between linked data sets

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#71]
No navigation. Navigation between linked data sets is very common, e.g.:

- Maternity, Neonatal and Community
- Cancer Outcomes and Services Data Sets

Not easy to navigate between data sets

**Comment by maxChappell** [comment]
Make use of the txaclass files found in web_site_content/navigation for menus
<property name="Data_Dictionary_Profile_x__y_DD_Navigation_x__y_isNavigationComponent" value="true"/>

**Comment by maxChappell** [comment]
property name="Data_Dictionary_Profile_x__y_DD_Navigation_x__y_isNavigationComponent" value="true"
