### ISSUE TITLE
Attributes with no codes with 'Web Order != '0'

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#76]
Here is a list of Attributes which don't have any codes with non-zero web order.  Some may be intentional, others may not:

 ACTIVITY_COUNT
 ACTIVITY_DATE
 ACTIVITY_DURATION
 ACTIVITY_IDENTIFIER
 AMERICAN_JOINT_COMMITTEE_ON_CANCER_STAGE
 APGAR_SCORE_1_MINUTE
 APGAR_SCORE_5_MINUTES
 BIRTH_ORDER
 CARE_PROFESSIONAL_TYPE_FOR_PREGNANCY_FIRST_CONTACT
 CLINICAL_CLASSIFICATION_CODE
 CLINICAL_INVESTIGATION_RESULT_VALUE
 COUNTRY_CODE
 FETAL_ORDER
 GEOGRAPHIC_AREA_CODE
 GESTATION_LENGTH_IN_WEEKS
 GLEASON_GRADE
 GS1_APPLICATION_IDENTIFIER_(GLOBAL)
 IMMUNISATION_AGE_GROUP
 IMMUNOHISTOCHEMISTRY_NUCLEAR_EXPRESSION_INTACT_INDICATION_CODE
 IMPLANT_MANUFACTURER
 LANGUAGE_CODE
 MAXIMUM_DEPTH_OF_INVASION
 MOLECULAR_DIAGNOSTIC_CODE
 NUMBER_OF_DAUGHTERS_UNDER_18
 ORGANISATION_CODE
 ORGANISATION_IDENTIFIER
 ORGANISATION_SITE_CODE
 PDS_NUMBER_OF_BIRTHS_IN_CONFINEMENT
 PERSON_AGE
 PERSON_COUNT
 PERSON_MARITAL_STATUS
 PERSON_SCORE
 POSITION_STATUS_EFFECTIVE_DATE
 REFERRAL_TO_TREATMENT_PERIOD_STATUS
 RENAL_VEIN_TUMOUR_INDICATOR_FOR_PAEDIATRIC_KIDNEY
 SICKNESS_ABSENCE_INDICATOR
 S_CATEGORY_CODE
 TUMOUR_SIZE
 WARD_DAY_PERIOD_AVAILABILITY
 WARD_NIGHT_PERIOD_AVAILABILITY

**Comment by maxChappell** [comment]
Noted that concepts and code system for REFERRAL_TO_TREATMENT_PERIOD_STATUS are incorrectly set to retired too

**Comment by maxChappell** [comment]
Analysis done. Mixture of reasons - most common being that only default codes are defined. However, in that scenario - we shouldn't/won't be generating them moving forwards.
[Attributes we shouldn't be generating as fhir (current).xlsx](https://github.com/NHSDigital/DataDictionaryPublication/files/4930762/Attributes.we.shouldn.t.be.generating.as.fhir.current.xlsx)

**Comment by maxChappell** [comment]
Broad description of individual patterns/issues:

FHIR items generated incorrectly when:
1) No "National Codes" text present on the attribute (often has linked de with default code/s - but we shouldn't be generating them. 
2) Codes are represented by a complex table - indicating a multi-level code list (we are should not be generating these - currently)
3) Codes/Attributes are retired - app is setting web order to zero incorrectly. Also complicated when an item is resurrected...Note - if an attribute is retired entire code system is retired (concept/codes within should not have status changes).
