### ISSUE TITLE
Format / Length hyperlinks missing

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#78]
Format / Length has now been added to Data Elements but items where the Format / Length is pulled from another item has not worked, e.g.
IMAGING CODE (SNOMED CT): has See SNOMED_CT_CODE
PROCEDURE (OPCS): has See OPCS-4_CODE
WHITE BLOOD CELL COUNT (HIGHEST PRETREATMENT): has See WHITE_BLOOD_CELL_COUNT
CONSULTANT CODE (RESPONSIBLE CONSULTANT): has See CONSULTANT_CODE

**Comment by maxChappell** [comment]
Not sure I fully understand this ticket - is the request for the hyperlink to the other item to be active? @AngelaFaulding

**Comment by AngelaFaulding** [comment]
We need to know what the Format/Length is and currently is doesn't show this:
https://beta.datadictionary.nhs.uk/data_elements/i/i/imaging_code__snomed_ct_.html
https://beta.datadictionary.nhs.uk/data_elements/p/proc/procedure__opcs_.html
https://beta.datadictionary.nhs.uk/data_elements/w/we/white_blood_cell_count__highest_pretreatment_.html
https://beta.datadictionary.nhs.uk/data_elements/c/cons/consultant_code__responsible_consultant_.html

Either the hyperlink needs to work or we need to add the Format/Length.

**Comment by maxChappell** [comment]
Thanks Angela. Over to oxford now.

**Comment by AngelaFaulding** [comment]
There is another ticket for this which I can't find but is down for discussion on Thursday.

**Comment by AngelaFaulding** [comment]
Should be fixed in the new release, needs checking when James has provided the new version.
