### ISSUE TITLE
Short descriptions

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#79]
We would like to take the "title" elements of the menu entries in the existing (old) dictionary and store as a property in Mauro for use in the shortdesc field of the DITA. Suggest using DCAT properties where possible for properties in the model catalogue so that it would also come out on RDF / SPARQL
Tasks -
Extract "title" properties from raw XML
Agree MetaModel property and populate the referred to item with title
Include in the shortdesc of the DITA generated.

**Comment by maxChappell** [comment]
Logic required differs according to the stereotype..
note some sentences "end" with a colon - in this instance extend to first paragraph. (e.g. class Medical Device)

For Attributes - use the first sentence. (Organisation code is a bad example...if bold has carried through pipeline, take the next sentence instead).

For Data Elements - When the first sentence says "is same as" use the short desc from the attribute it links to. Otherwise use 1st sentence. (the data element name provides context)

For Classes first line unless it says "a subtype of", in which case take the 2nd line.

For Business Definitions -  If first sentence has "is a" ,take 2nd sentence - otherwise take first sentence.

**Comment by maxChappell** [comment]
We also need to work out how we do hover text for data sets...

**Comment by maxChappell** [comment]
@oughnic please asses the criticality of this for 3+ (WCAG imperative vs semantic web aspirations).

**Comment by AngelaFaulding** [comment]
Needs discussing on Thursday.

**Comment by maxChappell** [comment]
For data sets - take the first self-referring paragraph from the overview.

**Comment by AngelaFaulding** [comment]
There is an issue with data sets that share the same data set, e.g. https://www.datadictionary.nhs.uk/data_sets/clinical_data_sets/cancer_outcomes_and_services_data_set.html
https://www.datadictionary.nhs.uk/data_sets/clinical_data_sets/national_neonatal_data_set.html

I have already had questions about this, can this be fixed for the October release?

**Comment by AngelaFaulding** [comment]
For Data Sets Maxine asked  "For data sets - take the first self-referring paragraph from the overview."
Can this be the first self-referring paragraph after "Introduction"? Please ensure Introduction is not included in the short description.

**Comment by AngelaFaulding** [comment]
Some of the short descriptions on Data Elements are not working correctly, e.g. 

https://www.datadictionary.nhs.uk/data_elements/nhs_number_status_indicator_code__baby_.html
https://www.datadictionary.nhs.uk/data_elements/nhs_number_status_indicator_code.html
https://www.datadictionary.nhs.uk/data_elements/nhs_number_status_indicator_code__mother_.html

**Comment by maxChappell** [comment]
That doesn't carry COVID-19

**Comment by AngelaFaulding** [comment]
https://datadictionary.nhs.uk/data_elements/administrative_category_code.html has "This is recorded for PATIENTACTIVITY." (space missing)

**Comment by rajabr57** [comment]
5/5 Awaiting update from James

**Comment by AngelaFaulding** [comment]
10/12/21 - many short descriptions will need amending but we can't do this until we have migrated to Mauro

**Comment by AngelaFaulding** [comment]
The information will be added to the Editorial Principles.

**Comment by AngelaFaulding** [comment]
DMDS to sort when Mauro is live.

**Comment by AngelaFaulding** [comment]
@PaulChapmanPM - T shirt label removed.

**Comment by AngelaFaulding** [comment]
A patch will be required to fix short descriptions and any other failed integrity checks before we go live with Mauro.

**Comment by AngelaFaulding** [comment]
This has been superseded by #408
