### ISSUE TITLE
Split sentence in bus def Healthwatch England

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#8]
Short name aliases not being displayed, e.g.
- Department for Work and Pensions
- Healthwatch England
- International Staging System
- Data Coordination Board
- Comment still valid, aliases are still not displayed.
- Healthwatch England has an issue where sentences are split, i.e.

Formerly alias not displayed, e.g.

Local Health Board (Wales) states:
- A Local Health Board (Wales) (formerly known as Local Health Board (Wales)) is an Organisation

It should be:
- A Local Health Board (Wales) (formerly known as Welsh Local Health Board) is an Organisation.

**Comment by AngelaFaulding** [comment]
Short name aliases appear to be working but formerly isn't. E.g.
A Local Health Board (Wales) (formerly known as null ) is an Organisation .
The Department for Education (formerly the null ) is an Organisation .

**Comment by AngelaFaulding** [comment]
Healthwatch England still has an issue where sentences are split, i.e.
Healthwatch England
is the independent consumer champion for health and social care in England.

**Comment by AngelaFaulding** [comment]
Formerly aliases still do not appear to be working, e.g. 
A Local Health Board (Wales) (formerly known as null ) is an Organisation.
The Department for Education (formerly the null ) is an Organisation .

**Comment by maxChappell** [comment]
The Department for Education example (null) is originating from the txaclass files...

Department for Education
Description
The Department for Education (formerly the **null** ) is an Organisation .


txaclass file -

name="$doc" value="&lt;p&gt;The &amp;lt;a href=&amp;quot;http://www.datadictionary.nhs.uk/data_dictionary/nhs_business_definitions/d/department_for_education_de.asp&amp;quot;&amp;gt;Department_for_Education&amp;lt;/a&amp;gt; (formerly the &amp;lt;a href=&amp;quot;http://www.datadictionary.nhs.uk/data_dictionary/nhs_business_definitions/d/department_for_education_de.asp&amp;quot;&amp;gt;null&amp;lt;/a&amp;gt;) is an &amp;lt;a 

Am currently investigating in the truly raw txcclass files (thank you @likin1 )

**Comment by maxChappell** [comment]
Formerly seems to be getting processed OK now for Department of education - but nulls still present for Local Health Board (Wales)

**Comment by maxChappell** [comment]
aliases etc now coming through ok. Just the split sentence left to resolve.

**Comment by jamesrwelch** [comment]
Split sentence now resolved

**Comment by AngelaFaulding** [comment]
Looks OK on the beta site, issued closed.
