### ISSUE TITLE
Links to Supporting Information

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#81]
The plan is to move NHS Business Definitions to web_site_content where the definitions are purely supporting definitions and do not link to a Class.
In the current beta version, Supporting Information items link to the current dictionary but this won't be correct moving forward. How will this be done in the future?

**Comment by arkie-boy** [comment]
We can handle this in the txaclass extraction script, or in the subsequent import processing.  But essentially there are two approaches that immediately spring to mind

1) we can calculate a new URL from the combination of the old one, the business definition name and the new server location.  
2) if we have a table of business definition name and new location, when we process the business definition names we can look up the new URL

**Comment by oughnic** [comment]
There is a third option which you may like to explore - that is to have a DITA keyref / conkeyref reference.  It means we need a persistent ID in the supporting information .txaclass (which I think we have - @maxChappell  / @arkie-boy can confirm) and then use that to let DITA link.
 See also https://learningdita.com/topic/lc_conkeyrefs/

**Comment by arkie-boy** [comment]
So let DITA fix it for us.  I can live with that ...

**Comment by oughnic** [comment]
Quite - It also means we can swap the references independently of the main Mauro content, so the keydef entries could be generated independently of the Mauro work.  Separation of concerns is always valuable.

**Comment by oughnic** [comment]
@arkie-boy @jamesrwelch We could also handle the code lists this way, so that we generate a large file of all the code list tables with ID attributes on each codelist fragment and then conkeyref them into the main dictionary.  It then separates the model dependencies, with the code lists managed independently of the main model in Mauro and gathered together for the publication run.

**Comment by arkie-boy** [comment]
Its definitely an elegant solution to downstream publication.  How does one access the 'non-business definition definitions' - which I'm going to call 'glossary items' for brevity -in Mauro?  Is it another terminology but with some publication metadata that instructs the DITA generator on how to process references to it?

Which means I still need to be able to recognise these glossary items and tag appropriately in the txaclassfiles

**Comment by AngelaFaulding** [comment]
I think we are going to call them Supporting Definitions as we already have a glossary and these don't fit into that.
We are currently doing an exercise to move them out of NHS Business Definitions.

**Comment by arkie-boy** [comment]
Will they have a new stereotype, @AngelaFaulding ?

**Comment by AngelaFaulding** [comment]
After discussions with Maxine, the decision has been made not to move these NHS Business Definitions to web_site_content.

**Comment by AngelaFaulding** [comment]
Nicholas has asked me to move the items to Supporting Information. So I will continue doing that.

**Comment by maxChappell** [comment]
Labelled as 3++ - to be revisited in 3++

**Comment by AngelaFaulding** [comment]
The items will be moved for 3+.

**Comment by AngelaFaulding** [comment]
Some pages still linking to the old version, e.g. https://beta.datadictionary.nhs.uk/supporting_information/supporting_information/nhs_data_model_and_dictionary_service.html

**Comment by AngelaFaulding** [comment]
I will fix NHS DMDS issue in the October release
