### ISSUE TITLE
RENAL VEIN TUMOUR INDICATOR FOR PAEDIATRIC KIDNEY - web order should be fixed by issue 76

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#83]
The Data Element has the correct codes but the Attribute has: 

Code | Description
-- | --
Dummy Enumeration | Dummy

**Comment by maxChappell** [comment]
Code system checked. Apart from web order incorrectly setting every web order to 0 (which should designate as a data element default code), the correct values are there.

Likin is investigating the web order issue.

**Comment by maxChappell** [comment]
Presence of property "Data Attribute" at the concept level could be used to ensure that concepts are correctly listed for the data attribute (albeit with incorrect web order property).

**Comment by maxChappell** [comment]
Fixed now.
