### ISSUE TITLE
Data Set and/or options

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#85]
In the current dictionary we have choices, e.g. DIDS
M | IMAGING CODE (NICIP)
and/or
IMAGING CODE (SNOMED-CT)

The new version has the following which is not correct:
Multiplicity | Attribute Name
-- | -- | --
Mandatory | IMAGING CODE (NICIP) 
Mandatory | IMAGING CODE (SNOMED-CT)
-- | --

Other data sets have the same. We can find other examples if required.

**Comment by maxChappell** [comment]
also #109

**Comment by AngelaFaulding** [comment]
Now fixed
