### ISSUE TITLE
Retired Items - awaiting issue 92

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#86]
I've spoken to Cath and have created a ticket to discuss further.

Issues for discussion:

- The retired Attributes have National Codes and Data Element links.
- The retired Data Elements have Attributes links.
- No retired items are linked to another item; all links are deleted. Are links required?
- There is no way of showing where the items were used.

**Comment by maxChappell** [comment]
Can you point us at an example or two please?

**Comment by AngelaFaulding** [comment]
Attributes:
- https://beta.datadictionary.nhs.uk/attributes/d/d/d29_status_of_extramedullary_disease.html
- https://beta.datadictionary.nhs.uk/attributes/a/a/anaesthesia_type_in_labour_and_delivery.html

Data Elements:
- https://beta.datadictionary.nhs.uk/data_elements/a/a/alcohol_status.html
- https://beta.datadictionary.nhs.uk/data_elements/l/l/last_episode_in_spell_indicator.html

-

**Comment by oughnic** [comment]
Is showing the last set of codes and values a good thing or a bad thing?

**Comment by AngelaFaulding** [comment]
The codes are fine but there is no context to where they were used.
All links are broken when items are retired so they don't show as grey on live items.
Why have the links on the pages when we know there are no links?
 It could look like they have been missed.

**Comment by maxChappell** [comment]
~92

**Comment by maxChappell** [comment]
For 3+ we won't publish retired items (including codes)
