### ISSUE TITLE
Data Element Description

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#88]
In the current dictionary the definition is held under Notes.
In the new version it has the headings shown after the my comments / questions below.

The definition that was under notes is now under the Format/Length section. Is that correct?
We previously said:  The Notes section provides guidance or other information concerning the Data  Element and its usage.
How would you now describe it?

Description

Format / Length
an1

..  is the same as attribute ...

National Codes:
Code	Description
1	??
2	??

Default Codes:
Code	Description
9	Not Known (Not Recorded)

Where Used
Type	Link	How used
Data Element	...

Attribute
...

**Comment by maxChappell** [comment]
21/07/20 - discussed with NO - order is fine. 

CSS to be amended to render and separate format length more clearly

**Comment by AngelaFaulding** [comment]
I have discussed with Cath, can the Format/Length and value be on the same line please?
ie. Format / Length an1
Rather than
Format / Length
an1

**Comment by maxChappell** [comment]
Agreed in workshop this can be addressed after 3+ go-live

**Comment by AngelaFaulding** [comment]
For example, ADMISSION METHOD CODE (HOSPITAL PROVIDER SPELL) now has:
Format / Length: an2
Issue an be closed.
