### ISSUE TITLE
Business Definitions

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#89]
To match the current version should these be NHS Business Definitions?

**Comment by maxChappell** [comment]
For clarity - this request is asking for "NHS" to be added to menu headings/labels.

Cath/Angela - does "NHS" add any value? are we ever likely to also have bus defs from other areas/sectors? how would they be distinguished, and indeed would we distinguish?

**Comment by cach1** [comment]
In current dictionary that is what they are called; although it seems attractive to include definitions from other sectors, practically speaking that becomes a maintenance nightmare - it would be more sensible to point to the external URL for latest definition (as we do now, of course).  DCB covers standards assurance for Health AND Social Care, but we don't have any social care stuff in the dictionary really.  
I don't have any strong feelings either way on this - I don't think people use the 'NHS' in the NHS Business Definitions when they refer to them.....BUT not having it may well have onward impacts to things like our internal work instructions, our Help pages and so on.  So if it is a quick job to amend the name, maybe it should be done.  Angela will probably have further thoughts

**Comment by AngelaFaulding** [comment]
As Cath says they have always been NHS Business Definitions and I thought 3+ was purely an accessibility version of the current dictionary.
I appreciate that names may change in version 4 but for ease now, could they please be NHS Business Definitions. It will mean no changes to work instructions and Help pages as Cath says for this. I have many other changes so if it is easy I would request that they stay as NHS Business Definitions for now.

**Comment by maxChappell** [comment]
Righto, let's make it NHS Business Definitions for 3+

**Comment by maxChappell** [comment]
Results in different hyperlinks than current DD. So better fixed.

**Comment by AngelaFaulding** [comment]
References changed to NHS Business Definitions so issue can be closed.
