### ISSUE TITLE
Healthwatch England - split sentence

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#9]
Healthwatch England has an issue where sentences are split, i.e.

Healthwatch England
is the independent consumer champion for health and social care in England.

**Comment by maxChappell** [comment]
https://beta.datadictionary.nhs.uk/business_definitions/h/healthwatch_england.html vs https://www.datadictionary.nhs.uk/data_dictionary/nhs_business_definitions/h/healthwatch_england_de.asp?shownav=1

**Comment by AngelaFaulding** [comment]
Now OK on the beta version, issue closed.
