### ISSUE TITLE
Retired Items - awaiting issue 93

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#90]
There are no retired Central Return Forms in the beta version.
See https://www.datadictionary.nhs.uk/items_index_K_child.asp and https://beta.datadictionary.nhs.uk/all/k.html
Is it OK that these are missing?

**Comment by maxChappell** [comment]
Can you pop an indicative URL in here from current DD please?

**Comment by maxChappell** [comment]
21/07/20 -  Can retired status of items (any type) be added as otherprop in the DITA please?
isRetired(true)

**Comment by maxChappell** [comment]
#92

**Comment by maxChappell** [comment]
Confirmed they are processed by knitting app and Steve's XSLT

**Comment by maxChappell** [comment]
withdrawn 05/11
