### ISSUE TITLE
Diagrams

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#91]
As the diagrams will not be part of Mauro, should they be removed from Together from the August 2020 release as they will no longer be published?
They are time consuming to maintain and is that effort required if they are not going to be published?

**Comment by maxChappell** [comment]
22/07/20 - NO says - leave them as they are.

**Comment by maxChappell** [comment]
for now

**Comment by AngelaFaulding** [comment]
Happy to leave them as we are dual running the current and beta versions.

**Comment by AngelaFaulding** [comment]
Diagrams removed from the September release.
