### ISSUE TITLE
Collections

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#94]
As agreed with Nicholas, please remove Collections from the front page.

**Comment by maxChappell** [comment]
Is this for 3+ or 3++?

**Comment by AngelaFaulding** [comment]
It's for 3+. I've assigned the 3+ label.
If you look on the front page, there is a Collections link with nothing in it. There is no Collections folder in Together so it needs removing.

**Comment by AngelaFaulding** [comment]
Collections has been removed so the ticket can be closed
