### ISSUE TITLE
RADIOTHERAPY TREATMENT REGION - Missing code 'P'

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#96]
https://beta.datadictionary.nhs.uk/attributes/r/radiot/radiotherapy_treatment_region.html
National Code P Primary missing from the Attribute and Data Element.

**Comment by maxChappell** [comment]
Code P absent on db and in code system.

**Comment by likin1** [comment]
Hi,

this has been fixed.

**Comment by maxChappell** [comment]
agreed.
