### ISSUE TITLE
S CATEGORY CODE - should be fixed under issue 76

### ISSUE THREAD

**Issue by AngelaFaulding** [NHSDigital/DataDictionaryPublication#97]
https://beta.datadictionary.nhs.uk/attributes/s/s/s_category_code.html
There are National Codes on the Data Element but not the Attribute.
Need to ensure the information table is present on the Attribute.

**Comment by maxChappell** [comment]
Linked to issue #76 - db showing same codes twice - one set as retired - the other as active. Web order coming through as 0 for everything. Have not done a machine diff re description difference (active/retired).

**Comment by likin1** [comment]
Hi,
the national codes are present under Attributes. There is something wrong with the processing at oxford end. If you check the data dictionary there are no codes present at data element level. All codes are present at the attribute end.

**Comment by maxChappell** [comment]
The error is still at our end I think. db for version 3.0.0 - generated on 7th of august has all codes as web order ==0. This is incorrect

**Comment by maxChappell** [comment]
Fixed
