### ISSUE TITLE
Potentially incorrect definition in "National Joint Registry Data Set - Ankle"

### ISSUE THREAD

**Issue by jamesrwelch** [NHSDigital/DataDictionaryPublication#99]
The "Bone Graft Used" section within "Ankle Revision" looks incorrect - there are duplicated elements.  Compare with the similar "Bone Graft Used" section defined earlier within "Ankle Primary".

**Comment by AngelaFaulding** [comment]
There are no groups in https://beta.datadictionary.nhs.uk/data_sets/clinical_content/content/national_joint_registry_data_set/national_joint_registry_data_set_-_ankle.html
The current version has groups: https://www.datadictionary.nhs.uk/data_dictionary/messages/clinical_content/content/national_joint_registry_data_set/national_joint_registry_data_set_-_ankle_fr.asp?shownav=1
Is that why there is an issue?

**Comment by jamesrwelch** [comment]
@AngelaFaulding No - it's not to do with groups - it looks incorrect on the live site: https://www.datadictionary.nhs.uk/data_dictionary/messages/clinical_content/content/national_joint_registry_data_set/national_joint_registry_data_set_-_ankle_fr.asp?shownav=1

**Comment by jamesrwelch** [comment]
Duplicated items:  "BONE GRAFT SOURCE (TALAR)" and "BONE GRAFT SOURCE (FIBULAR)"

**Comment by AngelaFaulding** [comment]
Sorry, yes I see it now. I will investigate.

**Comment by AngelaFaulding** [comment]
These should be BONE GRAFT INDICATOR (TALAR) and BONE GRAFT INDICATOR (FIBULAR).
I will fix in the August release.

**Comment by AngelaFaulding** [comment]
Fixed in the August release, issued closed.

**Comment by AngelaFaulding** [comment]
Fixed in the August release, issued closed.
